### ISSUE TITLE
EACCES: permission denied even with sudo npm install

### ISSUE THREAD

**Issue by sw-yx** [blitz-js/blitz#1003]
### What is the problem?

i am failing to install blitz even with `sudo` enabled.

```bash
sudo npm install -g blitz
Password:
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/usr/local/bin/blitz -> /usr/local/lib/node_modules/blitz/bin/blitz

> fsevents@1.2.13 install /usr/local/lib/node_modules/blitz/node_modules/next/node_modules/fsevents
> node install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/wanshawn/Library/Caches/node-gyp/12.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/blitz/node_modules/next/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/blitz/node_modules/next/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/blitz/node_modules/next/node_modules/fsevents
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> fsevents@1.2.13 install /usr/local/lib/node_modules/blitz/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/wanshawn/Library/Caches/node-gyp/12.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/blitz/node_modules/watchpack-chokidar2/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/blitz/node_modules/watchpack-chokidar2/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/blitz/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> ejs@2.7.4 postinstall /usr/local/lib/node_modules/blitz/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> @ampproject/toolbox-optimizer@2.6.0 postinstall /usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer
> node lib/warmup.js



AMP Optimizer ERROR Could not write cache file Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'
    at mkdirSync (fs.js:914:3)
    at FileSystemCache.set (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-core/lib/FileSystemCache.js:61:9)
    at fetchLatestRuntimeData_ (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:185:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchAmpRuntimeVersion_ (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:158:22)
    at async initRuntimeVersion (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:142:29)
    at async fetchRuntimeParameters (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:53:3)
    at async warmupCaches (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/warmup.js:57:5) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'
}




AMP Optimizer ERROR Could not write cache file Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'
    at mkdirSync (fs.js:914:3)
    at FileSystemCache.set (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-core/lib/FileSystemCache.js:61:9)
    at fetchValidatorRulesFromCache_ (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:90:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async initValidatorRules (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:71:8) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'
}




AMP Optimizer ERROR Could not write cache file Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'
    at mkdirSync (fs.js:914:3)
    at FileSystemCache.set (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-core/lib/FileSystemCache.js:61:9)
    at downloadAmpRuntimeStyles_ (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:244:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchAmpRuntimeStyles_ (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:206:18)
    at async initRuntimeStyles (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:114:8)
    at async fetchRuntimeParameters (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/fetchRuntimeParameters.js:55:3)
    at async warmupCaches (/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/lib/warmup.js:57:5) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'
}


AMP OPTIMIZER Downloaded latest AMP runtime data.

> @prisma/sdk@2.6.0 postinstall /usr/local/lib/node_modules/blitz/node_modules/@prisma/sdk
> node scripts/download.js

version: 650b5d0348ec38ae61e1e7db69bb54808418ede4
Error: Can't write to /usr/local/lib/node_modules/blitz/node_modules/@prisma/sdk please make sure you install "@prisma/cli" with the right permissions.
    at downloadBinary (/usr/local/lib/node_modules/blitz/node_modules/@prisma/fetch-engine/dist/download.js:283:19)
    at /usr/local/lib/node_modules/blitz/node_modules/@prisma/fetch-engine/dist/download.js:101:59
    at Array.map (<anonymous>)
    at download (/usr/local/lib/node_modules/blitz/node_modules/@prisma/fetch-engine/dist/download.js:101:46)
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN ts-node@8.9.1 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN ts-node@8.9.0 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-query@2.5.11 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN ink-link@1.1.0 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN ink@2.7.1 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN ink-spinner@3.0.1 requires a peer of react@^16.8.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-reconciler@0.24.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@9.5.3 requires a peer of react@^16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@9.5.3 requires a peer of react-dom@^16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @next/react-dev-overlay@9.5.3 requires a peer of react@^16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @next/react-dev-overlay@9.5.3 requires a peer of react-dom@^16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-jsx@3.3.0 requires a peer of react@15.x.x || 16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN use-subscription@1.4.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @prisma/sdk@2.6.0 postinstall: `node scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @prisma/sdk@2.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanshawn/.npm/_logs/2020-09-03T15_35_11_628Z-debug.log
```

### Steps to Reproduce

1. `npm i -g blitz`

### Versions

current

### Other

![image](https://user-images.githubusercontent.com/6764957/92136392-8e3d8180-ee3e-11ea-8b90-6bd7879f4d53.png)
![image](https://user-images.githubusercontent.com/6764957/92136405-92699f00-ee3e-11ea-91d4-3e3ea51574ac.png)

**Comment by flybayer** [comment]
Whoa, haven't seen that!

Does this work? `npx blitz new myapp`

**Comment by flybayer** [comment]
You can also try `yarn global add blitz` 🤷

**Comment by sw-yx** [comment]
i havent either. `sudo` has always worked for me, which is why its very odd to find it here. but cool i'll try npx

**Comment by sw-yx** [comment]
ok that worked. i'll close for now since i seem to be the only one with this problem but i think the underlying problem isnt solved yet

**Comment by cajotafer** [comment]
Just to mention, I am having the same issue, using `yarn global add blitz` didn't work for me, I am using `npx` instead.
