### ISSUE TITLE
Getting `Error: Invalid hook call` when using `yarn link blitz`

### ISSUE THREAD

**Issue by svobik7** [blitz-js/blitz#1015]
### What is the problem?

When using my local copy of blitz package using `yarn link blitz` I am getting error of ` Invalid hook call` when I try to access `localhost:3000` (even when I am in upstream/canary branch)

### Steps to Reproduce

1. Fork the blitz repo
2. checkout your fork
3. run `yarn link-cli` in your local copy
4. create new blitz app with `blitz new MyApp`
5. `cd MyApp`
6. link local copy of blitz `yarn link blitz`
7. run `blitz db migrate`
8. run `blitz start`
9. open `localhost:3000`

### Versions

```
debug: blitzPkgPath: /Users/jirkasvoboda/Development/packages/blitz/packages/blitz/dist/index.js
debug: cliPkgPath: /Users/jirkasvoboda/Development/packages/blitz/packages/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v12.18.3

blitz: 0.21.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 256.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.6.2 => 2.6.2 
    @prisma/client: 2.6.2 => 2.6.2 
    blitz: 0.21.1 => 0.21.1 
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    typescript: 3.9.7 => 3.9.7 
```

### Other

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/jirkasvoboda/Development/packages/blitz/node_modules/react/cjs/react.development.js:1523:13)
    at useContext (/Users/jirkasvoboda/Development/packages/blitz/node_modules/react/cjs/react.development.js:1531:20)
    at Html (/Users/jirkasvoboda/Development/packages/blitz/node_modules/next/dist/pages/_document.js:7:1049)
    at processChild (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/react-dom/cjs/react-dom-server.node.development.js:3687:14)
    at resolve (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/react-dom/cjs/react-dom-server.node.development.js:3604:5)
    at ReactDOMServerRenderer.render (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/react-dom/cjs/react-dom-server.node.development.js:4085:22)
    at ReactDOMServerRenderer.read (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/react-dom/cjs/react-dom-server.node.development.js:4023:29)
    at renderToStaticMarkup (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/react-dom/cjs/react-dom-server.node.development.js:4686:27)
    at renderDocument (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/next/dist/next-server/server/render.js:3:640)
    at renderToHTML (/Users/jirkasvoboda/Development/playgrounds/blitz-playground/node_modules/next/dist/next-server/server/render.js:52:103)
```

**Comment by flybayer** [comment]
Hey @svobik7 unfortunately we don't have a solution for doing this yet. Currently you have to test this locally by running apps inside `examples/` folder inside the monorepo.

I think the solution will be to use https://github.com/whitecolor/yalc, but I haven't had time to try that. If you want to, try that and let us know where you get.

**Comment by nitaking** [comment]
In my local environment, it starts fine with the yarn link.
Maybe it's a react's error message where the yarn link is not relevant.
