### ISSUE TITLE
Command blitz console broken

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#116]
`yarn blitz console` gives:

```
Welcome to Blitz.js v0.0.1
Type ".help" for more information.
⚡️>Error: Cannot find module '@prisma/client'
Require stack:
- /Users/dylan/dev/blitz/packages/cli/src/utils/module.ts
- /Users/dylan/dev/blitz/packages/cli/src/utils/load-dependencies.ts
- /Users/dylan/dev/blitz/packages/cli/src/commands/console.ts
- /Users/dylan/dev/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/dylan/dev/blitz/node_modules/@oclif/config/lib/config.js
- /Users/dylan/dev/blitz/node_modules/@oclif/config/lib/index.js
- /Users/dylan/dev/blitz/node_modules/@oclif/command/lib/command.js
- /Users/dylan/dev/blitz/node_modules/@oclif/command/lib/index.js
- /Users/dylan/dev/blitz/packages/cli/bin/run
    at invalidateCache (~/dev/blitz/packages/cli/src/utils/module.ts:2:32)
    at exports.forceRequire (~/dev/blitz/packages/cli/src/utils/module.ts:6:3)
    at Array.map (<anonymous>)
    at Object.exports.loadBlitz (~/dev/blitz/packages/cli/src/utils/load-blitz.ts:6:50)
    at Function.loadBlitz (~/dev/blitz/packages/cli/src/commands/console.ts:64:33)
    at Function.loadModules (~/dev/blitz/packages/cli/src/commands/console.ts:56:13)
    at Function.initializeRepl (~/dev/blitz/packages/cli/src/commands/console.ts:50:13)
    at Console.<anonymous> (~/dev/blitz/packages/cli/src/commands/console.ts:35:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by flybayer** [comment]
@quirk0o do you want to look into this? We're at a point now where I think we can make the console command actually work nice since we know our app structure and code.
