### ISSUE TITLE
Not working generated test in 0.23.1-canary.0

### ISSUE THREAD

**Issue by nitaking** [blitz-js/blitz#1164]
### What is the problem?
test fails on apps with `0.23.1-canary.0` installed

```bash
$ yarn test
yarn run v1.22.4
$ jest
 FAIL  app/pages/index.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'createContext' of undefined

      1 | import * as React from "react"
    > 2 | import { RouterContext, BlitzRouter } from "blitz"
        | ^
      3 | import { render as defaultRender } from "@testing-library/react"
      4 | import { renderHook as defaultRenderHook } from "@testing-library/react-hooks"
      5 |

      at Object.<anonymous> (node_modules/react-query/lib/react/ReactQueryCacheProvider.js:12:53)
      at Object.<anonymous> (node_modules/react-query/lib/react/index.js:6:32)
      at Object.<anonymous> (node_modules/react-query/lib/index.js:14:15)
      at Object.<anonymous> (node_modules/@blitzjs/core/dist/core.cjs.development.js:7:18)
      at Object.<anonymous> (node_modules/@blitzjs/core/dist/index.js:7:20)
      at Object.<anonymous> (node_modules/blitz/dist/index.js:5:12)
      at Object.<anonymous> (test/utils.tsx:2:1)
      at Object.<anonymous> (app/pages/index.test.tsx:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.345 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to Reproduce

1. Upgrade the generate app with `0.23.0` to  `0.23.1-canary.0`
2. `yarn test`

### Versions

```
output of `blitz --version --verbose`
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/user2/code/spkb/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/user2/code/spkb/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v14.2.0

blitz: 0.23.0 (global)
blitz: 0.23.1-canary.0 (local)

  Package manager: yarn
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 1.18 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.anyenv/envs/nodenv/versions/14.2.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.anyenv/envs/nodenv/versions/14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1
    @prisma/client: 2.7.1 => 2.7.1
    blitz: ^0.23.1-canary.0 => 0.23.1-canary.0
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.0.3 => 4.0.3
```

### Other

It work in version `0.23.0`

```bash
~/c/spkb (feat/lesson-filter|✚4) $ blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/user2/code/spkb/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/user2/code/spkb/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v14.2.0

blitz: 0.23.0 (global)
blitz: 0.23.0 (local)

  Package manager: yarn
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 204.97 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.anyenv/envs/nodenv/versions/14.2.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.anyenv/envs/nodenv/versions/14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1
    @prisma/client: 2.7.1 => 2.7.1
    blitz: 0.23.0 => 0.23.0
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.0.3 => 4.0.3


~/c/spkb (feat/lesson-filter|✚4) $ yarn test
yarn run v1.22.4
$ jest
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        3.497 s
Ran all test suites.
✨  Done in 4.69s.
~/c/spkb (feat/lesson-filter|✚4) $
```

**Comment by nitaking** [comment]
Related link: https://github.com/kulshekhar/ts-jest/issues/1346

Possibly caused by `import React from" react "` in react-query which was upgraded

**Comment by flybayer** [comment]
@nitaking want to try upgrading react-query and see if that fixes it?

**Comment by engelkes-finstreet** [comment]
Hey @nitaking 
are you still running into this issue. I thought you had the problem with a new app, but it seems that you have some changes on the `index.test.tsx`. Can you give me more hints how to reproduce the problem?

**Comment by ShikChen** [comment]
I had the same issue before and it's fixed by https://github.com/blitz-js/blitz/pull/1323.
