### ISSUE TITLE
Document needed dependency on Ubuntu in WSL

### ISSUE THREAD

**Issue by silversoftwerks** [blitz-js/blitz#121]
When running yarn I get this error:

`user@XPS:/mnt/c/Users/username/code/blitz/examples/store$ yarn
yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > react-query@1.2.1" has unmet peer dependency "react@^16.6.3".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > @testing-library/react@10.0.2" has unmet peer dependency "react@*".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > @testing-library/react@10.0.2" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > next@9.3.4" has unmet peer dependency "react@^16.6.0".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > next@9.3.4" has unmet peer dependency "react-dom@^16.6.0".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/server > null-loader@3.0.0" has unmet peer dependency "webpack@^4.3.0".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > store > react-final-form@6.4.0" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > next > styled-jsx@3.2.5" has unmet peer dependency "react@15.x.x || 16.x.x".
warning "workspace-aggregator-e662dc68-50e6-41da-924c-a61ed6db848e > @blitzjs/core > next > use-subscription@1.1.1" has unmet peer dependency "react@^16.8.0".
[5/5] Building fresh packages...
[-/9] ⠂ waiting...
[-/9] ⠂ waiting...
[6/9] ⠂ @scarf/scarf
[4/9] ⠂ node-pty
error /mnt/c/Users/username/code/blitz/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /mnt/c/Users/username/code/blitz/node_modules/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@13.12.0 | linux | x64
gyp info find Python using Python version 2.7.15 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/mnt/c/Users/username/code/blitz/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/Users/username/code/blitz/node_modules/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/Users/username/code/blitz/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/13.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/13.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/c/Users/username/code/blitz/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/13.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/c/Users/username/code/blitz/node_modules/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/mnt/c/Users/username/code/blitz/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/mnt/c/Users/username/code/blitz/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/mnt/c/Users/username/code/blitz/node_modules/which/which.js:80:29)
gyp ERR! stack     at /mnt/c/Users/username/code/blitz/node_modules/which/which.js:89:16
gyp ERR! stack     at /mnt/c/Users/username/code/blitz/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /mnt/c/Users/username/code/blitz/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:171:21)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/home/user/.nvm/versions/node/v13.12.0/bin/node" "/mnt/c/Users/username/code/blitz/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/c/Users/username/code/blitz/node_modules/node-pty
`

Fixed by installing node-pty dependencies
`sudo apt install -y make python build-essential`

Documentation found here: https://github.com/microsoft/node-pty#dependencies

Should this be installed automatically or should this be added to the blitz installation process documentation?

**Comment by flybayer** [comment]
@silversoftwerks yeah we should document that in CONTRIBUTING.md!

Do you want to submit a PR for that?

**Comment by silversoftwerks** [comment]
Yeah but I think I may have just followed directions incorrectly. I figured having the solution in the issues should be enough if anyone runs into it. But, should I also add it just in case others run into it?

**Comment by flybayer** [comment]
Ok, yeah we should still add it to contributing.md. Maybe add a Troubleshooting section, and under that have a Windows section where you can document this.

**Comment by simonpeterdebbarma** [comment]
I'll add it to the Docs if it hasn't been added.

**Comment by silversoftwerks** [comment]
@simonpeterdebbarma Thanks for grabbing this!

**Comment by simonpeterdebbarma** [comment]
Just installed and created an app on WSL and had no errors, but a lot of warnings popped up. 

Created an app and it worked fine.

```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/serialize-error@4.0.1: This is a stub types definition. serialize-error provides its own type definitions, so you do not need this installed.
npm WARN deprecated path-is-absolute@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/home/samantha/.nvm/versions/node/v12.16.3/bin/blitz -> /home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/bin/blitz

> @scarf/scarf@1.0.4 postinstall /home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/@scarf/scarf
> node ./report.js


> ejs@2.7.4 postinstall /home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> react-query@1.3.0 postinstall /home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/react-query
> node ./scripts/postinstall.js || exit 0


👩‍💻 Use react-query at work?
🎉 Consider sponsoring/supporting its development at:

  https://github.com/sponsors/tannerlinsley

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/blitz/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/blitz/node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ts-node@8.9.1 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-query@1.3.0 requires a peer of react@^16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN next@9.3.6 requires a peer of react@^16.6.0 but none is installed. You must install peer dependencies yourself.npm WARN next@9.3.6 requires a peer of react-dom@^16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-jsx@3.2.5 requires a peer of react@15.x.x || 16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN use-subscription@1.1.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/abbrev' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.abbrev.DELETE'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/ansi-regex' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/aproba' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.aproba.DELETE'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/balanced-match' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.4 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/chownr' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.chownr.DELETE'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/code-point-at' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/concat-map' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/console-control-strings' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/core-util-is' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/deep-extend' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/delegates' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/detect-libc' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/fs.realpath' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/has-unicode' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/inherits' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/ini' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/isarray' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.5 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/minimist' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/ms' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/number-is-nan' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/object-assign' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/os-homedir' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/os-tmpdir' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/path-is-absolute' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/process-nextick-args' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/safe-buffer' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/safer-buffer' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/sax' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/semver' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.semver.DELETE'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/set-blocking' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/signal-exit' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/strip-json-comments' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/util-deprecate' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/wrappy' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.wrappy.DELETE'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/yallist' -> '/home/samantha/.nvm/versions/node/v12.16.3/lib/node_modules/blitz/node_modules/webpack/node_modules/fsevents/node_modules/.yallist.DELETE'
```
