### ISSUE TITLE
Fix CLI test failure — always fails on first test run

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#127]
The cli tests are always failing on the first test run.

**To reproduce:**

1. Checkout canary
2. `git clean -xfd`
3. `yarn`
4. `yarn test` <-- succeeded
5. `git clean -xfd packages`
6. `yarn`
7. `yarn test` <-- failed

```
~/c/blitz> y build
yarn run v1.19.1
$ lerna run build --no-private --stream
tt^C⏎                                                                                                             ~/c/blitz> y test
yarn run v1.19.1
$ yarn run build && lerna run test --parallel
$ lerna run build --no-private --stream
lerna notice cli v3.20.2
lerna info Executing command in 4 packages: "yarn run build"
@blitzjs/server: $ tsdx build
@blitzjs/core: $ tsdx build
✓ Creating entry file 4.7 secs
✓ Creating entry file 4.7 secs
⠹ Building modules
✓ Building modules 12.6 secs
@blitzjs/cli: $ rimraf lib && tsc && yarn build:templates
@blitzjs/cli: $ rimraf templates/**/node_modules && cpy --dot --parents '!/node_modules/' templates lib
blitz: $ rollup -c rollup.config.js
blitz: ./src/index.ts → dist/index.js...
blitz: created dist/index.js in 2.9s
blitz: ./src/bin/cli.ts → ./dist/cli.js...
blitz: created ./dist/cli.js in 476ms
lerna success run Ran npm script 'build' in 4 packages in 32.0s:
lerna success - blitz
lerna success - @blitzjs/cli
lerna success - @blitzjs/core
lerna success - @blitzjs/server
lerna notice cli v3.20.2
lerna info Executing command in 3 packages: "yarn run test"
@blitzjs/cli: $ jest
@blitzjs/server: $ tsdx test
@blitzjs/core: $ tsdx test
@blitzjs/cli: PASS test/commands/new.test.ts
@blitzjs/cli: PASS test/commands/start.test.ts (7.153s)
@blitzjs/core: PASS test/todo.test.ts
@blitzjs/core:   ✓ todo (2ms)
@blitzjs/cli: PASS test/commands/build.test.ts (7.565s)
@blitzjs/core: Test Suites: 1 passed, 1 total
@blitzjs/core: Tests:       1 passed, 1 total
@blitzjs/core: Snapshots:   0 total
@blitzjs/core: Time:        4.846s
@blitzjs/core: Ran all test suites.
@blitzjs/cli: PASS test/commands/db.test.ts (8.062s)
@blitzjs/cli: FAIL test/commands/test.test.ts (8.077s)
@blitzjs/cli:   ● Test command › runs yarn test script
@blitzjs/cli:     : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
@blitzjs/cli:       14 |   })
@blitzjs/cli:       15 |
@blitzjs/cli:     > 16 |   it('runs yarn test script', async () => {
@blitzjs/cli:          |   ^
@blitzjs/cli:       17 |     jest.spyOn(hasYarn, 'default').mockReturnValue(true)
@blitzjs/cli:       18 |
@blitzjs/cli:       19 |     await TestCmd.run([])
@blitzjs/cli:       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@blitzjs/cli:       at Suite.<anonymous> (test/commands/test.test.ts:16:3)
@blitzjs/cli:   ● Test command › runs npm test script
@blitzjs/cli:     expect(jest.fn()).toBeCalledWith(...expected)
@blitzjs/cli:     - Expected
@blitzjs/cli:     + Received
@blitzjs/cli:     - "yarn",
@blitzjs/cli:     + "npm",
@blitzjs/cli:       ["test"],
@blitzjs/cli:       {"stdio": "inherit"},
@blitzjs/cli:     Number of calls: 1
@blitzjs/cli:       16 |   it('runs yarn test script', async () => {
@blitzjs/cli:       17 |     jest.spyOn(hasYarn, 'default').mockReturnValue(true)
@blitzjs/cli:     > 18 |
@blitzjs/cli:          | ^
@blitzjs/cli:       19 |     await TestCmd.run([])
@blitzjs/cli:       20 |
@blitzjs/cli:       21 |     expect(crossSpawn.spawn).toBeCalledWith('yarn', ...testParams)
@blitzjs/cli:       at test/commands/test.test.ts:18:45
@blitzjs/cli:       at fulfilled (../../node_modules/tslib/tslib.js:110:62)
@blitzjs/cli: Uh oh, we don't support that command.
@blitzjs/cli: You can try running a prisma command directly with:
@blitzjs/cli:   `npm run prisma COMMAND` or `yarn prisma COMMAND`
@blitzjs/server: PASS src/synchronizer/pipeline/rules/pages/api.test.ts
@blitzjs/server: PASS src/synchronizer/pipeline/rules/pages/pages.test.ts
@blitzjs/cli: PASS test/commands/console.test.ts (9.913s)
@blitzjs/cli:   ● Console
@blitzjs/cli:     console.log ../server/dist/server.cjs.development.js:647
@blitzjs/cli:       You have entered the Blitz console
@blitzjs/cli:     console.log src/commands/console.ts:39
@blitzjs/cli:       Tips: - Exit by typing .exit or pressing Ctrl-D
@blitzjs/cli:     console.log src/commands/console.ts:40
@blitzjs/cli:             - Use your db like this: await db.user.findMany()
@blitzjs/cli:     console.log src/commands/console.ts:41
@blitzjs/cli:             - Use your queries/mutations like this: await getUsers()
@blitzjs/cli: Test Suites: 1 failed, 5 passed, 6 total
@blitzjs/cli: Tests:       2 failed, 13 passed, 15 total
@blitzjs/cli: Snapshots:   0 total
@blitzjs/cli: Time:        10.704s
@blitzjs/cli: Ran all test suites.
@blitzjs/cli: error Command failed with exit code 1.
@blitzjs/cli: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in '@blitzjs/cli'
lerna ERR! yarn run test stdout:
$ jest

Uh oh, we don't support that command.
You can try running a prisma command directly with:

  `npm run prisma COMMAND` or `yarn prisma COMMAND`

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:
PASS test/commands/new.test.ts
PASS test/commands/start.test.ts (7.153s)
PASS test/commands/build.test.ts (7.565s)
PASS test/commands/db.test.ts (8.062s)
FAIL test/commands/test.test.ts (8.077s)
  ● Test command › runs yarn test script

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      14 |   })
      15 |
    > 16 |   it('runs yarn test script', async () => {
         |   ^
      17 |     jest.spyOn(hasYarn, 'default').mockReturnValue(true)
      18 |
      19 |     await TestCmd.run([])

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/commands/test.test.ts:16:3)

  ● Test command › runs npm test script

    expect(jest.fn()).toBeCalledWith(...expected)

    - Expected
    + Received

    - "yarn",
    + "npm",
      ["test"],
      {"stdio": "inherit"},

    Number of calls: 1

      16 |   it('runs yarn test script', async () => {
      17 |     jest.spyOn(hasYarn, 'default').mockReturnValue(true)
    > 18 |
         | ^
      19 |     await TestCmd.run([])
      20 |
      21 |     expect(crossSpawn.spawn).toBeCalledWith('yarn', ...testParams)

      at test/commands/test.test.ts:18:45
      at fulfilled (../../node_modules/tslib/tslib.js:110:62)

PASS test/commands/console.test.ts (9.913s)
  ● Console

    console.log ../server/dist/server.cjs.development.js:647
      You have entered the Blitz console
    console.log src/commands/console.ts:39
      Tips: - Exit by typing .exit or pressing Ctrl-D
    console.log src/commands/console.ts:40
            - Use your db like this: await db.user.findMany()
    console.log src/commands/console.ts:41
            - Use your queries/mutations like this: await getUsers()


Test Suites: 1 failed, 5 passed, 6 total
Tests:       2 failed, 13 passed, 15 total
Snapshots:   0 total
Time:        10.704s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by flybayer** [comment]
This might be the fix: https://jestjs.io/docs/en/troubleshooting#unresolved-promises

**Comment by sijad** [comment]
I can't reproduce this, is this fixed?

**Comment by flybayer** [comment]
Nope!

**Comment by flybayer** [comment]
I just reproduced again with:

1. `git clean -xfd`
2. `yarn`
3. `yarn test` <-- succeeded
4. `git clean -xfd packages`
5. `yarn`
6. `yarn test` <-- failed

**Comment by flybayer** [comment]
Update: I `skip`ed all the tests in `packages/cli/test/commands/test.test.ts` for now to get past this. Still needs fixed, but not as important now.

**Comment by flybayer** [comment]
Actually that didn't work. Then `commands/db.test.ts` were failing.

So now I'm doing `jest || jest` in the CLI test script 🙄

**Comment by flybayer** [comment]
**Update:** I see two issues here:

- Most of the commands are not retuning a promise that resolves once the task is finished: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/console.ts#L56 (this is a problem regardless of if it fixes the tests)

If that still doesn't fix it, then I think the issue is how we are mocking the async functions.

**Comment by ntgussoni** [comment]
> **Update:** I see two issues here:
> 
> * Most of the commands are not retuning a promise that resolves once the task is finished: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/console.ts#L56 (this is a problem regardless of if it fixes the tests)
> 
> If that still doesn't fix it, then I think the issue is how we are mocking the async functions.

Now I cannot get it to fail on the latest canary, is it still happening?  I should try it on an older computer because I think it depends a lot on the hardware.

**Comment by flybayer** [comment]
Wow yeah, I can't reproduce either!

**Comment by aem** [comment]
https://blitzjs.slack.com/archives/CUM2C68T1/p1588115011207900

**Comment by jeffzh4ng** [comment]
No longer able to reproduce the error I was getting from the slack post ^ 🤔

I initially thought switching my yarn version to `1.19.1` fixed it, but tests still passed even after changing back to a version > `1.19.1` (`1.22.4`).

**Comment by dajinchu** [comment]
I'm able reproduce even on subsequent `yarn test`. `1.19.1` and > `1.19.1` does not appear to make a difference. 

Digging in, I'm noticing that running test in serial fixes it: `lerna run test` instead of `lerna run test --stream --parallel`

**Comment by flybayer** [comment]
This has been fixed for awhile. I forget what fixed it.
