### ISSUE TITLE
Can't install any recipe

### ISSUE THREAD

**Issue by alexturpin** [blitz-js/blitz#1333]
### Steps to Reproduce

1. Run `blitz install tailwind`
2. Go through steps until it says "Dependencies installed! Press ENTER to continue". Press ENTER.
3. This results in `ERROR  Text string "" must be rendered inside <Text> component`

### Versions

```
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: C:\Users\alext\src\cocktails\node_modules\blitz\dist\index.js
debug: cliPkgPath: C:\Users\alext\src\cocktails\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js 

Windows 10 | win32-x64 | Node: v12.16.1

blitz: 0.24.1 (global)
blitz: 0.24.1 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 8.86 GB / 15.93 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.8.1 => 2.8.1
    @prisma/client: 2.8.1 => 2.8.1
    blitz: 0.24.1 => 0.24.1
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.0.3 => 4.0.3
```

### Other

Full stack trace

```
$ blitz install tailwind
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose


  ERROR  Text string "" must be rendered inside <Text> component

 C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/ink/src/reconciler.ts:122:10

 - createTextInstance (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/ink/src/reconciler.ts:122:10)
 - completeWork (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:10915:40)
 - completeUnitOfWork (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:14728:16)
 - performUnitOfWork (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:14704:12)
 - workLoopSync (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:14669:22)
 - performSyncWorkOnRoot (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:14265:11)
 -  (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:1931:24)
 - unstable_runWithPriority (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/scheduler/cjs/scheduler.development.js:697:12)
 - runWithPriority (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:1881:10)
 - flushSyncCallbackQueueImpl (C:/Users/alext/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/node_modules/react-reconciler/cjs/react-reconciler.development.js:1926:7)
Error: Text string "" must be rendered inside <Text> component
    at createTextInstance (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\ink\src\reconciler.ts:122:10)
    at completeWork (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:10915:40)
    at completeUnitOfWork (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:14728:16)
    at performUnitOfWork (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:14704:12)
    at workLoopSync (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:14669:22)
    at performSyncWorkOnRoot (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:14265:11)
    at C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:1931:24
    at unstable_runWithPriority (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\scheduler\cjs\scheduler.development.js:697:12)
    at runWithPriority (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:1881:10)
    at flushSyncCallbackQueueImpl (C:\Users\alext\AppData\Local\Temp\blitz-recipe-blitz-js-blitz\node_modules\react-reconciler\cjs\react-reconciler.development.js:1926:7)
```

**Comment by flybayer** [comment]
Oops, thanks for reporting this!

The issue is somewhere inside [the installer package](https://github.com/blitz-js/blitz/blob/canary/packages/installer/src/index.ts).

**Comment by alexturpin** [comment]
Also, and I'm not sure if this is relevant or should be a different issue, but I decided to just go ahead and try to follow the steps that the installer describes by hand, and by adding the import to `_document.tsx`, I am getting this in the terminal when running my app:

```
CSS cannot be imported within pages/_document.js. Please move global styles to pages/_app.js.
Location: pages\_document.tsx
```

**Comment by nahue** [comment]
Im trying to figure this one out.. since i upgraded ink a few days ago.

**Comment by nahue** [comment]
I found the issue.. im creating a PR for this one

**Comment by engelkes-finstreet** [comment]
Okay, thank you @nahue. I did not have the time to look into it yet.

**Comment by nahue** [comment]
Posted this PR https://github.com/blitz-js/blitz/pull/1339 @engelkes-finstreet @flybayer
