### ISSUE TITLE
some error when setup the blitz \date-fns\differenceInQuarters\index.js

### ISSUE THREAD

**Issue by MohammedALREAI** [blitz-js/blitz#1460]
### What is the problem?
when I try to create the  new app  blitz new app 
after installing the depndance   and  run the application

```
the error  `\haha\node_modules\date-fns\differenceInQuarters\index.js:1
(function (exports, require, module, __filename, __dirname) {


SyntaxError: Invalid or unexpected token
    at new Script (vm.js:100:7)
    at NativeCompileCache._moduleCompile (F:\haha\node_modules\@blitzjs\cli\node_modules\v8-compile-cache\v8-compile-cache.js:242:18)
    at Module._compile (F:\haha\node_modules\@blitzjs\cli\node_modules\v8-compile-cache\v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Module._load (internal/modules/cjs/loader.js:769:14)
    at Function._load (F:\haha\node_modules\@salesforce\lazy-require\lib\LazyLoader.js:99:24)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (F:\haha\node_modules\@blitzjs\cli\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)   
    at Object.<anonymous> (F:\haha\node_modules\date-fns\index.js:1436:39)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haha@1.0.0 start: `blitz start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haha@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mhammed Alreai\AppData\Roaming\npm-cache\_logs\2020-11-14T09_33_37_706Z-debug.log    
```   

### Steps to Reproduce

1.

### Versions
last version 0.25.0

```
debug: blitzPkgPath: F:\haha\node_modules\blitz\dist\index.js
debug: cliPkgPath: F:\haha\node_modules\@blitzjs\cli\lib\src\index.js

Windows 10 | win32-x64 | Node: v14.15.0

blitz: 0.25.0 (global)
blitz: 0.25.0 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 AMD A8-3520M APU with Radeon(tm) HD Graphics
    Memory: 995.38 MB / 5.48 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.x => 2.11.0
    @prisma/client: 2.x => 2.11.0
    blitz: 0.25.0 => 0.25.0
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 4.x => 4.0.5`
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Hmm, this looks like maybe a bug in https://github.com/zertosh/v8-compile-cache (which we use).

For a work around, you should be able to set the environment variable `DISABLE_V8_COMPILE_CACHE=1` to disable that compile cache.

**Comment by MohammedALREAI** [comment]
thank you it works
