### ISSUE TITLE
installing an npm package breaks the app in v0.25

### ISSUE THREAD

**Issue by Kay2dan** [blitz-js/blitz#1470]
### What is the problem?

When I install a npm package, I am unable to run `blitz start`, unless I rebuild the app using `blitz new` command. This has happened both times I installed npm packages post upgrade to v0.25.

### Steps to Reproduce

1. Use existing repo.
2. Install a package (in my case it was `npm i date-fns --save`)
3. Run `blitz start`

### Versions
```
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 4.15 | linux-x64 | Node: v12.18.3

blitz: 0.25.0 (global)
blitz: 1.0.0 (local)

  Package manager: yarn 
  System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 619.79 MB / 15.68 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: Not Found
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 3.9.7 => 3.9.7 
```

### Other

- **Here is the output of installing the above package:**

````
> husky@4.2.5 preuninstall /home/sk/www/aim-high/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky > Done
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/ts-node as it wasn't installed by /home/sk/www/aim-high/node_modules/ts-node
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/ts-node-transpile-only as it wasn't installed by /home/sk/www/aim-high/node_modules/ts-node
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/ts-script as it wasn't installed by /home/sk/www/aim-high/node_modules/ts-node
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/ts-node-script as it wasn't installed by /home/sk/www/aim-high/node_modules/ts-node
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/rimraf as it wasn't installed by /home/sk/www/aim-high/node_modules/rimraf
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/uuid as it wasn't installed by /home/sk/www/aim-high/node_modules/uuid
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/semver as it wasn't installed by /home/sk/www/aim-high/node_modules/semver
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/mkdirp as it wasn't installed by /home/sk/www/aim-high/node_modules/mkdirp
npm WARN rm not removing /home/sk/www/aim-high/node_modules/.bin/json5 as it wasn't installed by /home/sk/www/aim-high/node_modules/json5

> @prisma/cli@2.7.1 preinstall /home/sk/www/aim-high/node_modules/@prisma/cli
> node preinstall/index.js


> sodium-native@3.2.0 install /home/sk/www/aim-high/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> @prisma/cli@2.7.1 install /home/sk/www/aim-high/node_modules/@prisma/cli
> node download-build/index.js


> husky@4.2.5 install /home/sk/www/aim-high/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> core-js-pure@3.6.5 postinstall /home/sk/www/aim-high/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> @prisma/client@2.7.1 postinstall /home/sk/www/aim-high/node_modules/@prisma/client
> node scripts/postinstall.js

warning The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma Schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma Schema file yet, you can ignore this message.


> husky@4.2.5 postinstall /home/sk/www/aim-high/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-environment-jsdom-fourteen/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ date-fns@2.16.1
added 308 packages from 84 contributors, removed 1196 packages, updated 769 packages and audited 1085 packages in 24.662s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
````
-------------------------------------------------------------------------

- **Post npm installation of a package, when I run `blitz start`, I get the following output:**
```
Git config core.excludesFile is unset. Inferring .gitignore file locations.
Error: Cannot find module '@blitzjs/server'
Require stack:
- /home/sk/www/aim-high/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at resolveFileName (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/resolve-from/index.js:46:47)
    at Object.apply (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:183:36)
    at module.exports (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/resolve-cwd/index.js:4:30)
    at Object.apply (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:183:36)
    at resolveBinAsync (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js:687:35)
    at getNextBin (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js:721:28)
    at _temp5 (/home/sk/.nvm/versions/node/v12.18.3/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js:743:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/sk/www/aim-high/noop.js' ]
```

**Comment by flybayer** [comment]
The issue is that somehow you are loosing the blitz version. Your logs show `blitz: 1.0.0 (local)` instead of `0.25.0`.

Not sure what's up. These type of npm errors are so frustrating 🤦‍♂️ There's nothing we can do in blitz to fix it.

**Comment by flybayer** [comment]
So I notice that your logs show `Package manager: yarn` which means you have a `yarn.lock` and should be using `yarn` to install dependencies. However, your other logs looks like you are using `npm` to install dependencies.

**Comment by Kay2dan** [comment]
Thank you Brandon, I don't think this is blitz versioning issue. I uninstalled Yarn (I installed it to try out RedwoodJs & must have forgotten to uninstall it) as it always causes issues with npm for me. 

Post Yarn uninstall, the version says:
````
debug: blitzPkgPath: /home/sk/www/aim-high/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/sk/www/aim-high/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 4.15 | linux-x64 | Node: v12.18.3

blitz: 0.25.0 (global)
blitz: 0.25.0 (local)

  Package manager: yarn 
  System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 9.58 GB / 15.68 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.25.0 => 0.25.0 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 3.9.7 => 3.9.7 
````

After uninstall, I installed a package to test if the problem reported above still persists and unfortunately it does. :(

**Comment by flybayer** [comment]
I guess you tried `rm -rf node_modules && rm yarn.lock && rm package-json.lock` and then run `npm install` again?

What's the output of `blitz -vV` now?

Thirdly, does `npm start` work?

**Comment by Kay2dan** [comment]
I didnt try the npm start command when I had the issue. Thats a good point and I should have tried that. I will try again in a little bit and report back.

Regarding `blitz -vV`, its the same as above:

````
blitz -vV
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /home/sk/www/aim-high/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/sk/www/aim-high/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 4.15 | linux-x64 | Node: v12.18.3

blitz: 0.25.0 (global)
blitz: 0.25.0 (local)

  Package manager: npm 
  System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 7.68 GB / 15.68 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.25.0 => 0.25.0 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 3.9.7 => 3.9.7 
````

**Comment by Kay2dan** [comment]
Success, it was the conflict between yarn & npm. I rebooted my system & installed Lodash & the command `blitz start` works fine as expected. Thank you Brandon.
