### ISSUE TITLE
Unable to start newly generated project

### ISSUE THREAD

**Issue by cmoel** [blitz-js/blitz#1479]
### What is the problem?

Running `npx blitz start` from a newly generated project outputs an error message:

```
$ npx blitz start
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

◢ Preparing for launchError: File not found with singular glob: /Users/cmoel/Desktop/blitz-proj/default.pbxuser (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/cmoel/Desktop/blitz-proj/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob._finish (/Users/cmoel/Desktop/blitz-proj/node_modules/glob/glob.js:197:8)
    at done (/Users/cmoel/Desktop/blitz-proj/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/cmoel/Desktop/blitz-proj/node_modules/glob/glob.js:688:12)
    at /Users/cmoel/Desktop/blitz-proj/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/cmoel/Desktop/blitz-proj/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/cmoel/Desktop/blitz-proj/node_modules/glob/glob.js:764:12)
    at RES (/Users/cmoel/Desktop/blitz-proj/node_modules/inflight/inflight.js:31:16)
```

**NOTE: I put my hacky solution in the Other section below**

### Steps to Reproduce

1. Generate a new blitz project: `npx blitz new blitz-proj`
1. `cd blitz-proj`
1. `npx blitz start`

### Versions

```
$ npx blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/cmoel/Desktop/blitz-proj/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/cmoel/Desktop/blitz-proj/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v14.15.0

blitz: 0.25.0 (local)

  Package manager: yarn
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 2.33 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.11.0 => 2.11.0
    @prisma/client: 2.11.0 => 2.11.0
    blitz: 0.25.0 => 0.25.0
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 4.0.5 => 4.0.5
```

### Other

I wanted to solve this problem and found a hacky solution. To make it work, I opened `node_modules/glob-stream/readable.js` and searched for `allowEmpty`. I then changed line 55:

```diff
-  var allowEmpty = ourOpt.allowEmpty || false
+  var allowEmpty = ourOpt.allowEmpty || true
```

and `npx blitz start` worked successfully and I could successfully load http://localhost:3000/.

**Comment by flybayer** [comment]
Hey, sorry about that. This is a known issue (https://github.com/blitz-js/blitz/issues/1413) with an open PR to fix (https://github.com/blitz-js/blitz/pull/1457). So I'll go ahead and close this one.
