### ISSUE TITLE
Error when adding Capacitorjs

### ISSUE THREAD

**Issue by erlanggaadikara** [blitz-js/blitz#1487]
Hi, I am trying to add Capacitorjs. Everything was just fine, like start server and open android, until I am trying to start the server again. I got this following error:

``` 
\android\app\src\main\assets\public\api\users\queries\getCurrentUser.js✕ Warning: You have created conflicting api 
routes:
- \android\app\src\main\assets\public\api\auth\mutations\login.jsapi/undefined
- \android\app\build\intermediates\merged_assets\debug\out\public\api\auth\mutations\login.jsapi/undefined
× Uh oh something broke
DuplicatePathError: Warning: You have created conflicting api routes:
    at E:\tes-bliz\node_modules\@blitzjs\server\dist\server.cjs.development.js:1269:14
    at processInput (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\dist\file-pipeline.cjs.development.js:220:44)   
    at DestroyableTransform._transform (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\dist\file-pipeline.cjs.development.js:287:30)
    at DestroyableTransform.Transform._read (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at DestroyableTransform.Writable.write (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at DestroyableTransform.ondata (E:\tes-bliz\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at DestroyableTransform.emit (events.js:223:5) {
  pathType: 'api',
  paths: [
    [
      'E:\\tes-bliz\\android\\app\\src\\main\\assets\\public\\api\\auth\\mutations\\login.js',
      'E:\\tes-bliz\\android\\app\\build\\intermediates\\merged_assets\\debug\\out\\public\\api\\auth\\mutations\\login.js'
    ]
  ],
  name: 'DuplicatePathError'
}
```

Is there anything I can do?
Thank you

**Comment by Skn0tt** [comment]
Blitz currently doesn't support building mobile apps. Sorry that I cannot offer a solution.

It's on the roadmap and being discussed in https://github.com/blitz-js/blitz/discussions/1338, though.

**Comment by erlanggaadikara** [comment]
> Blitz currently doesn't support building mobile apps. Sorry that I cannot offer a solution.
> 
> It's on the roadmap and being discussed in #1338, though.

Well, thanks. Can't wait to see it!
