### ISSUE TITLE
`.DS_Store` should be ignore by duplicate page detection

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1508]
### What is the problem?

```
◤ /app/_resolvers/billing/mutations/startMapTestingSubscription.ts✕ Warning: You have created conflicting page routes:
- /app/account/pages/.DS_Store
- /app/testing/proctor/pages/.DS_Store
✖ Uh oh something broke
DuplicatePathError: Warning: You have created conflicting page routes:
    at transformFn (/Users/b/c/blitz/packages/server/src/stages/pages/index.ts:88:14)
    at processInput (/Users/b/c/blitz/packages/file-pipeline/src/transform.ts:92:5)
    at DestroyableTransform._transform (/Users/b/c/blitz/packages/file-pipeline/src/transform.ts:69:11)
    at DestroyableTransform.Transform._read (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DestroyableTransform.Writable.write (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DestroyableTransform.ondata (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at DestroyableTransform.emit (events.js:315:20) {
  pathType: 'pages',
  paths: [
    [
      '/Users/b/c/ahts/homeschool-boss/app/account/pages/.DS_Store',
      '/Users/b/c/ahts/homeschool-boss/app/testing/proctor/pages/.DS_Store'
    ]
  ]
}
```

### Versions

```
    "blitz": "0.25.1-canary.1",
```

### Other

Here's the code for this: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/pages/index.ts#L87

**Comment by piotrski** [comment]
Should we just ignore any paths containing `.DS_Store` and don't display error for them? I'm not sure if they are already ignored when creating other stuff for pages?

**Comment by tpatel** [comment]
This is appearing following #1499. The `.DS_Store` used to be ignore because it didn't have the right file extensions and now it's not ignored.

I see in the code that there is something setup to ignore files based on the `.gitignore` content but it looks like it's not used before the duplication check.

**Comment by tpatel** [comment]
I think we should add something in https://github.com/blitz-js/blitz/blob/94ff1da4de4e2a08dee381d7832476ed4e1b8dae/packages/file-pipeline/src/pipeline.ts#L68 to make sure we ignore files that match any glob pattern in `config.ignore`.
Would that be a good solution to the problem?

**Comment by flybayer** [comment]
@tpatel yeah, I think that should work.
