### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Key - in file-pipeline

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1516]
### What is the problem?

I regularly get errors as shown below when switching git branches or rebases where files are different (added/removed) between them. Have to restart the server to fix.

```
(node:78411) UnhandledPromiseRejectionWarning: Error: Key "/Users/b/c/ahts/homeschool-boss/app/testing/bookings/mutations/submitHomeschoolStep3.tsx" returns
    at Manifest.removeKey (/Users/b/c/blitz/packages/server/src/stages/manifest/index.ts:39:13)
    at transformFn (/Users/b/c/blitz/packages/server/src/stages/manifest/index.ts:93:18)
    at processInput (/Users/b/c/blitz/packages/file-pipeline/src/transform.ts:92:5)
    at DestroyableTransform._transform (/Users/b/c/blitz/packages/file-pipeline/src/transform.ts:69:11)
    at DestroyableTransform.Transform._read (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DestroyableTransform.Writable.write (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DestroyableTransform.ondata (/Users/b/c/blitz/packages/file-pipeline/node_modules/readable-stream/lib/_stream_readable.js:681:20)
(node:78411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:78411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error - ./app/testing/bookings/mutations/submitHomeschoolStep3.tsx
Error: ENOENT: no such file or directory, open '/Users/b/c/ahts/homeschool-boss/.blitz/caches/dev/app/testing/bookings/mutations/submitHomeschoolStep3.tsx'
```

### Steps to Reproduce

Not sure exactly, but I think have a page file present on one branch but not on another. Then start server, access the page, and then switch between the branches.

### Versions

```
0.25.1-canary.1
```

**Comment by Kay2dan** [comment]
I started getting these as well, however, upon upgrade to v0.25.x canary, they just disappeared and now its all clean.
