### ISSUE TITLE
Error: Package exports for '\blitz\node_modules\tslib' do not define a valid '.' target

### ISSUE THREAD

**Issue by nntu** [blitz-js/blitz#1608]
### Steps to Reproduce

1.

### Versions

```
output of `blitz --version --verbose`
```

### Other

Please include applicable logs and screenshots that show your problem.
blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Error: Package exports for 'C:\Users\xxx\AppData\Roaming\npm\node_modules\blitz\node_modules\tslib' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
    at resolveExports (internal/modules/cjs/loader.js:393:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function._load (C:\Users\bidvct\AppData\Roaming\npm\node_modules\blitz\node_modules\@salesforce\lazy-require\lib\LazyLoader.js:112:42)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (C:\Users\bidvct\AppData\Roaming\npm\node_modules\blitz\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\blitz\node_modules\@oclif\parser\lib\index.js:4:17)
    at Module._compile (C:\Users\xxxx\AppData\Roaming\npm\node_modules\blitz\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by flybayer** [comment]
Can you try deleting `node_modules` and re-installing dependencies?

**Comment by nntu** [comment]
ok , i try upgrade nodejs 14. so. it's ok. thanks
