### ISSUE TITLE
DuplicatePathError: Warning: You have created conflicting page routes

### ISSUE THREAD

**Issue by vinaybijanpalli** [blitz-js/blitz#1625]
### What is the problem?
I updated node.js and i am getting this error when starting blitz
```
\.coverage\lcov-report\test\app\auth\components\index.html✕ Warning: You have created conflicting page routes:
- \.coverage\lcov-report\test\app\pages\index.htmlpages/undefined
- \.coverage\lcov-report\test\app\auth\pages\index.htmlpages/undefined
× Uh oh something broke
DuplicatePathError: Warning: You have created conflicting page routes:
    at C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\server\dist\server.cjs.development.js:1236:14
    at processInput (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\dist\file-pipeline.cjs.development.js:222:44)
    at DestroyableTransform._transform (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\dist\file-pipeline.cjs.development.js:289:30)
    at DestroyableTransform.Transform._read (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at DestroyableTransform.Writable.write (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at DestroyableTransform.ondata (C:\Users\vinay\Projects\Blitz.js\test\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at DestroyableTransform.emit (events.js:315:20) {
  pathType: 'pages',
  paths: [
    [
      'C:\\Users\\vinay\\Projects\\Blitz.js\\test\\.coverage\\lcov-report\\test\\app\\pages\\index.html',
      'C:\\Users\\vinay\\Projects\\Blitz.js\\test\\.coverage\\lcov-report\\test\\app\\auth\\pages\\index.html'
    ]
  ]
}
```

### Versions

```
Windows 10 | win32-x64 | Node: v14.15.3

blitz: 0.27.1 (global)
blitz: 0.26.2 (local) 

  Package manager: yarn 
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz
    Memory: 2.22 GB / 7.67 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.x => 2.12.1 
    @prisma/client: 2.x => 2.12.1 
    blitz: latest => 0.26.2 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530     
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.x => 4.1.2
```

**Comment by flybayer** [comment]
@vinaybijanpalli still having this issue? Maybe try deleting `.blitz` and `node_modules`, then install deps again and run blitz

**Comment by vinaybijanpalli** [comment]
@flybayer still getting the same error after deleting and reinstalling `.blitz` & `node_modules`.

Deleting `.coverage` worked for me

**Comment by flybayer** [comment]
Ah, that makes sense. I will fix!
