### ISSUE TITLE
Error: Key ~ returns  crashing

### ISSUE THREAD

**Issue by realSaddy** [blitz-js/blitz#1659]
### What is the problem?
I'm new to Blitz-js, and whenever I am running `blitz start` and delete a file inside the blitz app's folder the entire apparatus crashes with `throw new Error("Key \"" + key + "\" returns");` and `Error: Key "FILE_THAT_WAS_DELETED" returns`.
### Steps to Reproduce

1. Run `blitz start`.
2. While editing some files, delete any that is being used to compile.

### Versions

```
Linux 5.4 | linux-x64 | Node: v15.4.0

blitz: 0.27.1 (global)
blitz: 0.27.1 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 18.64 GB / 31.29 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.10 - /usr/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.12 => 2.12.1 
    @prisma/client: ~2.12 => 2.12.1 
    blitz: 0.27.1 => 0.27.1 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.1.3 => 4.1.3 
```

### Other

(The crash error when I deleted public/index.html)
```
/home/saddy/Projects/JSA-Voting/node_modules/@blitzjs/server/dist/server.cjs.development.js:1007
      throw new Error("Key \"" + key + "\" returns");
            ^

Error: Key "/home/saddy/Projects/JSA-Voting/public/index.html" returns
```
Also, while it will no longer serve the correct files nor show any output in the console, the process continues to run in the background (including taking up the port). This means I have to kill the process in order to continue using my API.

**Comment by realSaddy** [comment]
Here is another one
```
/home/saddy/Projects/JSA-Voting/node_modules/@blitzjs/server/dist/server.cjs.development.js:1007
      throw new Error("Key \"" + key + "\" returns");
            ^

Error: Key "/home/saddy/Projects/JSA-Voting/app/auth/validations.ts" returns
    at Manifest.removeKey (/home/saddy/Projects/JSA-Voting/node_modules/@blitzjs/server/dist/server.cjs.development.js:1007:13)
    at /home/saddy/Projects/JSA-Voting/node_modules/@blitzjs/server/dist/server.cjs.development.js:1074:18
    at processInput (/home/saddy/Projects/JSA-Voting/node_modules/@blitzjs/file-pipeline/dist/file-pipeline.cjs.development.js:222:44)
    at DestroyableTransform._transform (/home/saddy/Projects/JSA-Voting/node_modules/@blitzjs/file-pipeline/dist/file-pipeline.cjs.development.js:289:30)
    at DestroyableTransform.Transform._read (/home/saddy/Projects/JSA-Voting/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/saddy/Projects/JSA-Voting/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/saddy/Projects/JSA-Voting/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/saddy/Projects/JSA-Voting/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/home/saddy/Projects/JSA-Voting/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/home/saddy/Projects/JSA-Voting/node_modules/readable-stream/lib/_stream_readable.js:619:20)
```

**Comment by flybayer** [comment]
That's not good! Haven't seen that before. Thanks for reporting. Maybe it's related to Node 15.

**Comment by flybayer** [comment]
This was fixed in https://github.com/blitz-js/blitz/releases/tag/v0.30.1
