### ISSUE TITLE
chakra recipe is erroring with useCallbackRef

### ISSUE THREAD

**Issue by malkomalko** [blitz-js/blitz#1693]
### What is the problem?

See log below for log when trying the chakra recipe.  More than likely something changed with one of the deps since we're relying on the [latest](https://github.com/blitz-js/blitz/blob/canary/recipes/chakra/index.ts#L39-L44) tag.

The [issue is in chakra](https://github.com/chakra-ui/chakra-ui/issues/3006), however I did want to bring this up to see if we should be in the mindset of locking down versions in recipes instead of relying on things list latest that could make things more error prone.

💭 thoughts? 😄  

### Steps to Reproduce

1. `npm i -g blitz@canary` although this still exists on older versions
2. do your initial setup to migrate and start, everything is fine
3. add chakra recipe with `blitz install chakra`

### Versions

```
output of `blitz --version --verbose`

debug: blitzPkgPath: /Users/malkomalko/projects/courses/hello-blitz/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/malkomalko/projects/courses/hello-blitz/node_modules/@blitzjs/cli/lib/src/index.js

macOS Big Sur | darwin-x64 | Node: v15.3.0

blitz: 0.29.0-canary.0 (global)
blitz: 0.29.0-canary.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 16.00 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.3.0/bin/yarn
    npm: 7.0.14 - ~/.nvm/versions/node/v15.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: ~2.12 => 2.12.1
    @prisma/client: ~2.12 => 2.12.1
    blitz: 0.29.0-canary.0 => 0.29.0-canary.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.3 => 4.1.3
```

### Other

- Output of running `blitz start` after installing chakra with `blitz install chakra`
```
error - /Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/portal/dist/esm/portal.js
Attempted import error: 'useCallbackRef' is not exported from '@chakra-ui/hooks'.
TypeError: (0 , _utils.compose) is not a function
    at logicalTransform (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/utils/logical-prop.js:35:41)
    at Object.logical (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/utils/logical-prop.js:45:16)
    at Object.<anonymous> (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/config/position.js:27:30)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.newLoader [as .js] (/Users/malkomalko/projects/courses/hello-blitz/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/config/index.js:61:17)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.newLoader [as .js] (/Users/malkomalko/projects/courses/hello-blitz/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
TypeError: (0 , _utils.compose) is not a function
    at logicalTransform (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/utils/logical-prop.js:35:41)
    at Object.logical (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/utils/logical-prop.js:45:16)
    at Object.<anonymous> (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/config/position.js:27:30)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.newLoader [as .js] (/Users/malkomalko/projects/courses/hello-blitz/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/malkomalko/projects/courses/hello-blitz/node_modules/@chakra-ui/styled-system/dist/cjs/config/index.js:61:17)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.newLoader [as .js] (/Users/malkomalko/projects/courses/hello-blitz/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
```

**Comment by flybayer** [comment]
Ah, yeah not sure how that slipped through. Recipes are supposed to be pinned to a major version range. Would you want to make a PR to set them to the last working version range?

Code: https://github.com/blitz-js/blitz/blob/canary/recipes/chakra/index.ts#L39-L43
