### ISSUE TITLE
blitz CLI doesn't work in Windows

### ISSUE THREAD

**Issue by wKovacs64** [blitz-js/blitz#175]
**What is the problem?**

Globally installed `blitz` CLI doesn't work in Windows.

**Steps to Reproduce:**

1. `yarn global add blitz@0.5.0-canary.5`
2. `blitz new my-blitz-project`

**Versions:**
 - Blitz: 0.5.0.-canary.5
 - OS: Windows 10

**Supporting Documentation**

```sh
❯ blitz new my-blitz-project
debug: global-linked
debug: pkgPath: C:\Users\Justin\AppData\Local\Yarn\Data\global\node_modules\cli

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'C:\Users\Justin\AppData\Local\Yarn\Data\global\node_modules\cli'
Require stack:
- C:\Users\Justin\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\cli.js
- C:\Users\Justin\AppData\Local\Yarn\Data\global\node_modules\blitz\bin\blitz
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Justin\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\cli.js:46:11)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Justin\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\blitz\\dist\\cli.js',
    'C:\\Users\\Justin\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\blitz\\bin\\blitz'
  ]
}
```

(Note: `blitz` and `blitz -v` also yield the exact same error output, so it's not command specific.)

**Comment by camilo86** [comment]
Yeah, I did a clean install of blitz on windows, and I'm seeing the same issue 😥 I'm looking to see if this could maybe be a problem during the `oclif` release process

**Comment by camilo86** [comment]
Ok, so oddly enough: `blitz` seems to work just fine as long as your terminal is in the `C:\Users\<YOUR-USERNAME-HERE>` path. Trying to use blitz in any other directly yields the same error message in the issue

**Comment by flybayer** [comment]
This is an issue with the `cli.ts` file inside the blitz package. Where global vs local usage is determined and executed.

I'll try to set up a VM and debug this
