### ISSUE TITLE
Blitz console not working

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#180]
**What is the problem?**

Blitz console seems to be broken.

**Steps to Reproduce:**

1. `blitz new app-name`

2. `cd app-name`

3. `blitz start`

4. `blitz console`

**Versions:**

- Blitz: `0.5.0-canary.6`
- OS: macOs

**Supporting Documentation**

```sh
dylan@Dylans-MacBook-Pro candy % blitz console
You have entered the Blitz console
Tips: - Exit by typing .exit or pressing Ctrl-D
      - Use your db like this: await db.user.findMany()
      - Use your queries/mutations like this: await getUsers()
⚡️ > Error: Cannot find module '/Users/dylan/dev/candy/db'
Require stack:
- /Users/dylan/dev/candy/node_modules/@blitzjs/cli/lib/src/utils/module.js
- /Users/dylan/dev/candy/node_modules/@blitzjs/cli/lib/src/utils/load-blitz.js
- /Users/dylan/dev/candy/node_modules/@blitzjs/cli/lib/src/commands/console.js
- /Users/dylan/dev/candy/node_modules/@oclif/config/lib/plugin.js
- /Users/dylan/dev/candy/node_modules/@oclif/config/lib/config.js
- /Users/dylan/dev/candy/node_modules/@oclif/config/lib/index.js
- /Users/dylan/dev/candy/node_modules/@oclif/command/lib/command.js
- /Users/dylan/dev/candy/node_modules/@oclif/command/lib/index.js
- /Users/dylan/dev/candy/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/dylan/.config/yarn/global/node_modules/blitz/dist/cli.js
- /Users/dylan/.config/yarn/global/node_modules/blitz/bin/blitz
    at Function.Module._resolveFilename (~/dev/candy/node_modules/tsconfig-paths/lib/register.js:75:40)
    at invalidateCache (~/dev/candy/node_modules/@blitzjs/cli/lib/src/utils/module.js:4:34)
    at Object.exports.forceRequire (~/dev/candy/node_modules/@blitzjs/cli/lib/src/utils/module.js:7:5)
    at ~/dev/candy/node_modules/@blitzjs/cli/lib/src/utils/load-blitz.js:25:33
    at Array.map (<anonymous>)
    at Object.exports.loadBlitz (~/dev/candy/node_modules/@blitzjs/cli/lib/src/utils/load-blitz.js:19:60)
    at Function.loadBlitz (~/dev/candy/node_modules/@blitzjs/cli/lib/src/commands/console.js:50:50)
    at Function.loadModules (~/dev/candy/node_modules/@blitzjs/cli/lib/src/commands/console.js:44:17)
```

**Comment by flybayer** [comment]
I'm 95% sure this is because we lost TS support in production.

I think we need to use the ts-node repl creator directly? 

In development, oclif automatically loads ts-node if present. I was hoping it would do the same in production, but apparently not!
