### ISSUE TITLE
Upgrade to 0.30.0-canary.6 causes "Cannot read property 'resolver' of undefined"

### ISSUE THREAD

**Issue by kenneho** [blitz-js/blitz#1890]
### Steps to Reproduce

1. Upgrade existing project from 0.30.0-canary.2 to 0.30.0-canary.6
2. Run `blitz dev`
3. Error during startup: 
```

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using external babel configuration from C:\Users\me\projects\myapp\.blitz\caches\dev\babel.config.js
event - compiled successfully
event - build page: /tools/atool/new
wait  - compiling...
event - compiled successfully
TypeError: Cannot read property 'resolver' of undefined
    at Module../app/_resolvers/auth/mutations/login.ts (C:\Users\me\projects\myapp\.blitz\caches\dev\.next\server\pages\_app.js:146:107)
    at __webpack_require__ (C:\Users\me\projects\myapp\.blitz\caches\dev\.next\server\pages\_app.js:23:31)
    at Module../app/auth/mutations/login.ts (C:\Users\me\projects\myapp\.blitz\caches\dev\.next\server\pages\_app.js:312:92)
    at __webpack_require__ (C:\Users\me\projects\myapp\.blitz\caches\dev\.next\server\pages\_app.js:23:31)
    at Module../app/auth/components/LoginForm.tsx (
```

### Versions

```
Windows 10 | win32-x64 | Node: v12.20.1

blitz: 0.30.0-canary.2 (global)
blitz: 0.30.0-canary.6 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 5.61 GB / 15.84 GB
  Binaries:
    Node: 12.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.15 => 2.15.0
    @prisma/client: ~2.15 => 2.15.0
    blitz: 0.30.0-canary.6 => 0.30.0-canary.6
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.3 => 4.1.3
```

### Other

I have not checked the versions between canary 3 and 5, so I don't know in which version the bug was introduced.

**Comment by kenneho** [comment]
I downgraded to canary 5, then 4, 3 and 2. When I was back at 2 it started working again. So something apparently happened in canary-3.

**Comment by bacongravy** [comment]
0.30.0-canary.3 includes the following breaking change:

    Rename resolver pipe fns: pipe.resolver to resolver.pipe, pipe.zod to resolver.zod, etc: #1821

To resolve this issue in your project you'll need to find all occurrences of `pipe.resolver` and replace them with `resolver.pipe`. (According to the error message you included, at least one occurrence is in `auth/mutations/login.ts`.)

**Comment by flybayer** [comment]
@bacongravy is correct. That should fix your problem. Make sure you pay close attention to the release notes when upgrading!
