### ISSUE TITLE
`blitz start|build` broken on windows

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#193]
**What is the problem?**

`blitz start` fails with:
```
C:\Users\b\myapp>blitz s
✔ Blitz is ready
(node:6836) UnhandledPromiseRejectionWarning: Error: Unable to start terminal process: CreateProcess failed
    at new WindowsPtyAgent (C:\Users\b\myapp\node_modules\node-pty\lib\windowsPtyAgent.js:77:36)
    at new WindowsTerminal (C:\Users\b\myapp\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\b\myapp\node_modules\node-pty\lib\index.js:28:12)
    at nextStartDev (C:\Users\b\myapp\node_modules\@blitzjs\server\dist\server.cjs.development.js:1417:18)
    at C:\Users\b\myapp\node_modules\@blitzjs\server\dist\server.cjs.development.js:1505:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`blitz build` fails with:
```
C:\Users\b\myapp>blitz b
✔ Blitz is ready
Warning: You have enabled experimental feature(s).
Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry


> Build error occurred
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at findPagesDir (C:\Users\b\myapp\node_modules\next\dist\lib\find-pages-dir.js:3:170)
    at build (C:\Users\b\myapp\node_modules\next\dist\build\index.js:4:451)
Creating an optimized production build .
```

**Versions:**

- Blitz: 0.5.0-canary.6
- OS: Windows 10

**My troubleshooting**

I was able to fix the first part of `next start` with the following on windows:
```diff
export async function nextStartDev(nextBin: string, cwd: string, manifest: Manifest, devFolder: string) {
  const cb = pty
--    .spawn(nextBin, ['dev'], {
++    .spawn('powershell.exe', [`node ${nextBin} dev`], {
      cwd,
    })
    .on('data', transformOutput(manifest, devFolder))

  return Promise.resolve(cb)
}
```

After this change, then `blitz start` fails with the same error as `blitz build`

**More info**

`next dev` is setting the project directory here: https://github.com/zeit/next.js/blob/91adb8661d/packages/next/next-server/server/next-server.ts#L150

For some reason this isn't resolving the same as on mac/linux

**Comment by DevanB** [comment]
>For some reason this isn't resolving the same as on mac/linux

I'm assuming this isn't working still, because when I run `now dev` I get an error about the `pages` directory not being in the project root.

**Comment by simonpeterdebbarma** [comment]
I wanted to test and see what errors I get on my system. They seem to be a little different than what's documented above and saving these messages here for reference.

System: `Windows 10 | win32-x64 | Node: v12.16.3`
Blitz: `blitz 07.0 and 0.8.1`

---

**Blitz 0.7.0**

```
`Module not found: Can't resolve 'child_process' in '...\myapp\node_modules\@prisma\client\runtime'`
```
![image](https://user-images.githubusercontent.com/31207418/80896057-91b1d800-8ca7-11ea-94ec-495e04b157ad.png)

---

**Blitz 0.8.1**

```
Module not found: Can't resolve 'app/projects/queries/getProjects' in '...\blitz\myapp\.blitz\caches\dev\pages\projects'
ModuleNotFoundError: Module not found: Error: Can't resolve 'app/projects/queries/getProjects' in '...\myapp\.blitz\caches\dev\pages\projects'
```
![image](https://user-images.githubusercontent.com/31207418/80896316-4baa4380-8caa-11ea-9310-460aa8b5c03a.png)
