### ISSUE TITLE
Weird error if no name field in package.json

### ISSUE THREAD

**Issue by lcswillems** [blitz-js/blitz#1957]
### Steps to Reproduce

Create a new Blitzjs app: `npx blitz new blitz-app`

Remove the `name` field from the `package.json` file.

Run `yarn build`.

This gives this error:

```
TypeError: Cannot read property 'replace' of undefined
    at ee (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/@blitzjs/core/dist/core.cjs.production.min.js:1:5987)
    at re (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/@blitzjs/core/dist/core.cjs.production.min.js:1:6380)
    at d (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:498)
    at bb (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:37:16)
    at a.b.render (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:48)
    at a.b.read (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:83)
    at exports.renderToStaticMarkup (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:446)
    at renderDocument (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/next/dist/next-server/server/render.js:3:715)
    at renderToHTML (/mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/next/dist/next-server/server/render.js:56:103)
    at async /mnt/Data/Documents/Travail/Personnel/Projets/Ouverts/Miple/Code/lab/blitz-app/node_modules/next/dist/export/worker.js:26:6
```

**Comment by flybayer** [comment]
Hey thanks!

Here's the line that needs fixed: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/blitz-data.tsx#L14

If package.json name isn't available, we should default to "blitz" as the name

**Comment by lcswillems** [comment]
Thank you for the fix!

**Comment by lcswillems** [comment]
I don't know if it is a good idea to base the name of the cookies on the name of the project. It is an unexpected behavior from my side. I would have never expected that changing the name of the project would log out all my users...

**Comment by flybayer** [comment]
@lcswillems excellent point. I opened an issue for that: https://github.com/blitz-js/blitz/issues/1972
