### ISSUE TITLE
Internal Server Error after fresh install on macOS

### ISSUE THREAD

**Issue by coreybrown89** [blitz-js/blitz#204]
**What is the problem?**
After creating a new project and running `blitz start` 

**Steps to Reproduce:**

1. Create a new project `blitz new etc`
2. Run `blitz start` (project builds fine)
3. Head over to `localhost:3000` 
4. Internal Server Error & console errors

**Versions:**

Blitz: 0.6.0-canary.0
Node: v12.16.1
OSX: 10.14.6 (18G103)
yarn: 1.19.1

```
debug: local
debug: pkgPath: /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/cli
env: darwin-x64 node-v12.16.1
blitz: 0.6.0-canary.0 (global)
blitz: 0.6.0-canary.0 (local)
```

**Supporting Documentation**
```
 error ] Error: Cannot find module 'next/dist/next-server/lib/fid.js'
Require stack:
- /Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/load-components.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/api-utils.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/next-server.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/next.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/lib/start-server.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/cli/next-dev.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/bin/next
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/bin/next-patched
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.../next-server/lib/fid (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2793:18)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/server/node_modules/next/dist/pages/_document.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2061:35)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/server/node_modules/next/document.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2747:18)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/core/dist/core.cjs.development.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:124:16)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/core/dist/index.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:369:20)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2841:71)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/next.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/lib/start-server.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/cli/next-dev.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/bin/next',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/bin/next-patched'
  ]
}
Error: Cannot find module 'next/dist/next-server/lib/fid.js'
Require stack:
- /Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/load-components.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/api-utils.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/next-server.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/next.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/lib/start-server.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/cli/next-dev.js
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/bin/next
- /Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/bin/next-patched
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.../next-server/lib/fid (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2793:18)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/server/node_modules/next/dist/pages/_document.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2061:35)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/server/node_modules/next/document.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2747:18)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/core/dist/core.cjs.development.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:124:16)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Object.../../../node_modules/@blitzjs/core/dist/index.js (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:369:20)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:2841:71)
    at __webpack_require__ (/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js:23:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cbrown/Sites/hello-world/restaurant/.blitz/caches/dev/.next/server/static/development/pages/_document.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/next.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/server/lib/start-server.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/cli/next-dev.js',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/node_modules/next/dist/bin/next',
    '/Users/cbrown/Sites/hello-world/restaurant/node_modules/@blitzjs/server/bin/next-patched'
  ]
}
```

**Comment by flybayer** [comment]
This could be related to #193

**Comment by flybayer** [comment]
This could be macOS 10.14 Mojave

**Comment by coreybrown89** [comment]
So I’ve updated to Catalina 10.15.4 and ran a fresh new install of blitz cli, ran the blitz new and am experiencing the same issue when trying to go to localhost:3000 after running blitz start .

**Comment by ryardley** [comment]
Hmm I am having trouble reproducing. macOs 10.15.4

Error appears related to a missing next dependency. What version of next did it install?

**Comment by ryardley** [comment]
Does `node_modules/next/dist/next-server/lib/fid.js` exist in the installation? What happens if you clean your yarn cache?

**Comment by flybayer** [comment]
In slack @coreybrown89 said switching from default macos Node to using nvm fixed this

But @aem said he's using default node and it works fine.

If someone else runs into this, you should try this and report back:

1. Run `blitz build`, let it fail
2. Move `node_modules` into `.blitz/caches/build/`
3. `cd .blitz/caches/build`
4. `yarn run next build`

And see if that succeeds or fails.

**Comment by jimthedev** [comment]
Not sure if related but when I updated my OS I also had to go do some things in XCode (signing license again, making sure right version of the command line tools was being used) that blocked me from using Node native modules.

**Comment by CarterMcAlister** [comment]
I ran into this issue on Catalina and was able to resolve it by removing and then reinstalling `next` in my project.

**Comment by flybayer** [comment]
Going to go ahead and close this, as it doesn't seem Blitz specific.
