### ISSUE TITLE
Cannot create a new project with node 14.0.0

### ISSUE THREAD

**Issue by michaelspeed** [blitz-js/blitz#2046]
### What is the problem?

Creating a new blitz project with blitz new app throws an error

### What are detailed steps to reproduce this?

1.npm install -g blitz
2. blitz new myAppName

error Log = 
```
 UnhandledPromiseRejectionWarning: Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/michaelspeed/.nvm/versions/node/v14.0.0/lib/node_modules/blitz/node_modules/p-cancelable/index.js:46:12)
    at makeRequest (/Users/michaelspeed/.nvm/versions/node/v14.0.0/lib/node_modules/blitz/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/Users/michaelspeed/.nvm/versions/node/v14.0.0/lib/node_modules/blitz/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (events.js:422:26)
    at Request.emit (events.js:315:20)
    at Timeout.retry (/Users/michaelspeed/.nvm/versions/node/v14.0.0/lib/node_modules/blitz/node_modules/got/dist/source/core/index.js:1264:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60867) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:60867) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Run `blitz -v` and paste the output here:

```
macOS Catalina | darwin-x64 | Node: v14.0.0

blitz: 0.30.6 (global)

  Package manager: npm
  System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 1.97 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.0.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by michaelspeed** [comment]
Works ok with node 15.5.0

**Comment by flybayer** [comment]
Can you try with the latest node 14.x version?

**Comment by michaelspeed** [comment]
Works with 14.15.5
