### ISSUE TITLE
Blitz cli crash on windows

### ISSUE THREAD

**Issue by nestoralonsovina** [blitz-js/blitz#2084]
### What is the problem?

After installing the cli it crashes on Windows 10 , if I select the form type fast It will crash afterwards, it seems to be unable to perform any type of request.

### Paste all your error logs here:

```
? Pick a form library (you can switch to something else later if you want) ... (node:15664) UnhandledPromiseRejectionWarning: Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\p-cancelable\index.js:46:12)    at makeRequest (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\got\dist\source\as-promise\index.js:38:13)
    at Request.<anonymous> (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\got\dist\source\as-promise\index.js:143:17)
    at Object.onceWrapper (events.js:422:26)
    at Request.emit (events.js:315:20)
    at Timeout.retry (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\got\dist\source\core\index.js:1264:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:292
      throw er; // Unhandled 'error' event
      ^

RequestError: Timeout awaiting 'request' for 3000ms
    at ClientRequest.<anonymous> (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\got\dist\source\core\index.js:956:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:461:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:96:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Timeout.timeoutHandler [as _onTimeout] (C:\Users\alons\AppData\Roaming\nvm\v14.0.0\node_modules\blitz\node_modules\got\dist\source\core\utils\timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Request instance at:
    at emitErrorNT (internal/streams/destroy.js:96:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1615123033383,
    socket: 1615123033383,
    lookup: 1615123033385,
    connect: 1615123033395,
    secureConnect: 1615123033418,
    upload: 1615123033419,
    response: 1615123033463,
    end: undefined,
    error: 1615123036389,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 2,
      tcp: 10,
      tls: 23,
      request: 1,
      firstByte: 44,
      download: undefined,
      total: 3006
    }
  },
  event: 'request'
}
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Install the cli
2. run blitz new appName

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.0.0

blitz: 0.31.1 (global)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 17.90 GB / 31.92 GB
  Binaries:
    Node: 14.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found```

**Comment by nestoralonsovina** [comment]
It seems to be good if I use node 15.0.0

**Comment by flybayer** [comment]
Can you try on a later version of v14? Likely 14.0.0 has some bugs fixed in later releases
