### ISSUE TITLE
Webpack can't load css

### ISSUE THREAD

**Issue by Julien-e** [blitz-js/blitz#2107]
### What is the problem?

Hello error with new version of blitz 0.32.1
Can't launch blitz dev pages-manifest.js not found
I have clear .blitz folder change nothing.

### Paste all your error logs here:

```
√ Compiled
Loaded env from D:\workspace\blitzjs\.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using external babel configuration from D:\workspace\blitzjs\babel.config.js
error - ./app/auth/components/LoginForm.module.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-2-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-2-2!./app/auth/components/LoginForm.module.css)
TypeError: getProcessedPlugins is not a function
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./app/auth/components/LoginForm.module.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-2-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-2-2!./app/auth/components/LoginForm.module.css)
TypeError: getProcessedPlugins is not a function
Error: Cannot find module 'D:\workspace\blitzjs\.next\server\pages-manifest.json'
Require stack:
- D:\workspace\blitzjs\node_modules\next\dist\next-server\server\require.js
- D:\workspace\blitzjs\node_modules\next\dist\next-server\server\api-utils.js
- D:\workspace\blitzjs\node_modules\next\dist\next-server\server\next-server.js
- D:\workspace\blitzjs\node_modules\next\dist\server\next.js
√ Compiled
Loaded env from D:\workspace\blitzjs\.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using external babel configuration from D:\workspace\blitzjs\babel.config.js
error - ./app/auth/components/LoginForm.module.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-2-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-2-2!./app/auth/components/LoginForm.module.css)
TypeError: getProcessedPlugins is not a function
```

### Paste all relevant code snippets here:

blitz dev

### What are detailed steps to reproduce this?

Update from 0.30

### Run `blitz -v` and paste the output here:

```
blitz -v
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Windows 10 | win32-x64 | Node: v15.8.0

blitz: 0.32.1 (global)
blitz: 0.32.1 (local) 

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 17.47 GB / 31.92 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0
    blitz: 0.32.1 => 0.32.1
    prisma: ~2.17 => 2.17.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0     
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: ~4.1 => 4.1.5
```

**Comment by flybayer** [comment]
Looks like there's an issue with your css config 🤔 

Can you post the contents of your `blitz.config.js` file?

**Comment by Julien-e** [comment]
Hello, i clear all my project remake blitz new now i have this error .

```
PS D:\workspace\*****> blitz build        
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

√ Compiled
Loaded env from D:\workspace\*****\.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Creating an optimized production build...
info  - Using external babel configuration from D:\workspace\*****\babel.config.js
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'app/articles/pages/articles.module.css' in 'D:\workspace\*****\pages\actualites'


> Build error occurred
Error: > Build failed because of webpack errors
    at D:\workspace\*****\node_modules\next\dist\build\index.js:15:918
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async D:\workspace\*****\node_modules\next\dist\build\tracer.js:3:470
```

**Comment by Julien-e** [comment]
i have try to create next-env.d.ts but not working.

**Comment by Julien-e** [comment]
Ok i found why css not working.

If the css file is not in same folder of pages it's not working.

**Comment by flybayer** [comment]
@Julien-e Ok probably a bug. Can you list the exact file paths that cause it to break?
