### ISSUE TITLE
Files Using Spread Syntax ([...auth].tsx) can't be copied by recipes

### ISSUE THREAD

**Issue by mattfwood** [blitz-js/blitz#2183]
### What is the problem?

When trying to create a recipe that copies a file using the Next.js "spread" syntax `[...auth].tsx`, the file can't be found.

However, if I change the file name to something like `auth.tsx`, it works as expected.

### Paste all your error logs here:

```
blitz-google-oauth-recipe/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: blitz-google-oauth-recipe/templates/api/auth/[...auth].tsx
    at EditionInterface.exports.copy (blitz-google-oauth-recipe/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at blitz-google-oauth-recipe/node_modules/@blitzjs/generator/dist/blitzjs-generator.cjs.dev.js:624:21
    at TempGenerator.write (blitz-google-oauth-recipe/node_modules/@blitzjs/generator/dist/blitzjs-generator.cjs.dev.js:619:9)
    at TempGenerator.run (blitz-google-oauth-recipe/node_modules/@blitzjs/generator/dist/blitzjs-generator.cjs.dev.js:681:5)
    at createNewFiles (blitz-google-oauth-recipe/node_modules/@blitzjs/installer/dist/blitzjs-installer.cjs.dev.js:565:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

### Paste all relevant code snippets here:

Here is my recipe builder step:

```
.addNewFilesStep({
    stepId: 'addAuth',
    stepName: 'Add API Auth Config',
    explanation: 'Add [...auth].tsx File to Allow Google OAuth Sign Up',
    targetDirectory: './app/api/auth',
    templatePath: join(__dirname, 'templates', 'api', 'auth'),
    templateValues: {}
  })
```

### What are detailed steps to reproduce this?

1. Create new recipe
2. Add a step that copies a file using spread syntax `[...auth].tsx`

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v15.4.0

blitz: 0.33.1 (global)
blitz: 1.0.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 116.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - ~/.nodenv/shims/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - ~/.nodenv/shims/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

I can see it's happening at this line in the `mem-fs-editor` package:

https://github.com/SBoudrias/mem-fs-editor/blob/e29735506b7d6997d93d958bb49672b2d4e2e05d/lib/actions/copy.js#L49

So i imagine it's doing something to filter out dots from file path names or something similar?

**Comment by flybayer** [comment]
That's weird!
