### ISSUE TITLE
First attempt to start a blitz app failed

### ISSUE THREAD

**Issue by taylorosbourne** [blitz-js/blitz#220]
**What is the problem?**
Console output after running:

```bash
npm i -g blitz
blitz new myApp
```

console output:

```bash
/usr/local/lib/node_modules/blitz/dist/cli.js:75
    cli.run();
        ^

TypeError: cli.run is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/blitz/dist/cli.js:75:9)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/blitz/bin/blitz:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
```

**Steps to Reproduce:**

```bash
npm i -g blitz
blitz new myApp
```

**Versions:**

```
blitz -v => 0.6.1
node -v => 13.5.0
postgres -V => 12.1
```

**Supporting Documentation**
Please include applicable logs and screenshots that show your problem.

**Comment by merelinguist** [comment]
What is your OS?

**Comment by taylorosbourne** [comment]
mac os

**Comment by flybayer** [comment]
@taylorosbourne What is the output of `blitz -v` ?

**Comment by taylorosbourne** [comment]
```bash
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose
Also, this CLI may be slow as it's not yet optimized for speed

debug: global-linked
debug: pkgPath: /usr/local/lib/node_modules/cli

macOS Catalina darwin-x64 node-v13.5.0

blitz: 0.6.1 (global)
```

**Comment by flybayer** [comment]
Ok I see a problem. Working on a fix

**Comment by taylorosbourne** [comment]
@flybayer thanks very much!  excited to try this out

**Comment by flybayer** [comment]
Ok, try `npm i -g blitz@canary` and tell me if that works or not.

If it doesn't work, post the output of `blitz -v` again

**Comment by taylorosbourne** [comment]
@flybayer your fix is working!  thanks

**Comment by flybayer** [comment]
Awesome!

Closed in https://github.com/blitz-js/blitz/commit/55fdaa05306852a10d0d4e636c3bfa091698e2a1
