### ISSUE TITLE
Npm upgrade and build issue with blitz@0.34.0-canary.3

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#2206]
### What is the problem?

Error with npm upgrade and doesn't build on blitz dev

### Paste all your error logs here:

npm upgrade
```
> blitz@0.34.0-canary.3 postinstall /Users/paul/Share/development/[project]/node_modules/blitz
> node scripts/postinstall.js

Failed to load config in getConfig() TypeError: sessionMiddleware is not a function
    at Object.<anonymous> (/Users/paul/Share/development/[project]/blitz.config.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.getConfig (/Users/paul/Share/development/[project]/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:90:40)
    at _getBlitzRuntimeData (/Users/paul/Share/development/[project]/node_modules/@blitzjs/core/dist/blitz-data-080e83b6.cjs.dev.js:29:25)
    at Object.getBlitzRuntimeData (/Users/paul/Share/development/[project]/node_modules/@blitzjs/core/dist/blitz-data-080e83b6.cjs.dev.js:40:31)
(node:28696) Warning: Accessing non-existent property 'sessionMiddleware' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28696) Warning: Accessing non-existent property 'simpleRolesIsAuthorized' of module exports inside circular dependency
```

blitz dev:
```
TypeError: _chalk.default.constructor is not a constructor
    at Object.<anonymous> (/Users/paul/Share/development/[project]/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseBabel.js:1:277)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/Users/paul/Share/development/[project]/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/paul/Share/development/[project]/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:174)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/Users/paul/Share/development/[project]/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

### Paste all relevant code snippets here:

```
N/A
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
blitz: 0.34.0-canary.2 (global)
blitz: 0.34.0-canary.3 (local)

  Package manager: npm
  System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 155.48 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.0-canary.3 => 0.34.0-canary.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by flybayer** [comment]
@paulm17 I'm unable to reproduce this. Can you please provide more details?

**Comment by paulm17** [comment]
Now that I know removing node_modules is the ultimate fix.  I just upgraded the blitz version, remove node_modules and did a re-install via npm install.  

No issues, so closing.

**Comment by flybayer** [comment]
Ok yeah probably was a leftover issue from that old symlink method which I got rid of
