### ISSUE TITLE
`npm i -g blitz` ==> `Cannot find module 'react-dom'`

### ISSUE THREAD

**Issue by skotchpine** [blitz-js/blitz#2261]
### What is the problem?

a postinstall script throws an error

### Paste all your error logs here:

```
/Users/tyler/.nvm/versions/node/v14.16.1/bin/blitz -> /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/bin/blitz

> sodium-native@3.2.1 install /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> @prisma/engines@2.19.0-39.c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d postinstall /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/@prisma/engines
> node download/index.js


> core-js-pure@3.11.0 postinstall /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> blitz@0.34.3 postinstall /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz
> node scripts/postinstall.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'react-dom'
Require stack:
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/reactBatchedUpdates.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/setBatchUpdatesFn.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/index.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/index.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/dist/blitz.cjs.dev.js
- /Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/dist/blitz.cjs.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/reactBatchedUpdates.js:8:40)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/reactBatchedUpdates.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/setBatchUpdatesFn.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/react/index.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/react-query/lib/index.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/dist/blitz.cjs.dev.js',
    '/Users/tyler/.nvm/versions/node/v14.16.1/lib/node_modules/blitz/dist/blitz.cjs.js'
  ]
}
```

### Paste all relevant code snippets here:

`npm i -g blitz`

### What are detailed steps to reproduce this?

0. `nvm install 14.16.1`
1. `nvm use 14.16.1`
2. `npm i -g blitz`

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.34.3 (global)

  Package manager: npm
  System:
    OS: macOS 11.2.2
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 2.87 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found

```

**Comment by markhughes** [comment]
Possibly related to peer dependencies as in https://github.com/blitz-js/blitz/issues/2227

**Comment by markhughes** [comment]
@skotchpine can you try removing it first, and then installing it with `yarn global`? Curious if your issue is isolated to npm

**Comment by skotchpine** [comment]
Spot on, yes it doesn't happen with my yarn.

**Comment by flybayer** [comment]
@skotchpine does it work with `npm i -g blitz --legacy-peer-deps`?

**Comment by Anjianto** [comment]
> @skotchpine does it work with `npm i -g blitz --legacy-peer-deps`?

this remains the same. I get the same error


![Screenshot from 2021-05-03 19-45-26](https://user-images.githubusercontent.com/61521141/116877547-4890bd00-ac48-11eb-814c-6d4220b8f3ec.png)

**Comment by flybayer** [comment]
Ok I can reproduce. You should be able to safely ignore that error.
