### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by fernvilla** [blitz-js/blitz#2288]
### What is the problem?

Was testing out the latest canary release (v0.35.0-canary.3) and when attempting to generate a new app when I received this error.

Not an issue when I downgrade to v0.34.3 or v0.35.0-canary.2.

### Paste all your error logs here:

```
(node:3808) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at Object.buildConfig (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:58:59)
    at Object.run (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js:14:14)
    at main (/usr/local/lib/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js:94:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js:118:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Paste all relevant code snippets here:

```
N/A
```

### What are detailed steps to reproduce this?

1. Update to latest canary version (0.35.0-canary.3): `npm install -g blitz@canary --legacy-peer-deps`
2. Attempt to generate a new blitz app

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.35.0-canary.3 (global)

  Package manager: npm 
  System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
    Memory: 251.76 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found


```

**Comment by flybayer** [comment]
Thanks @fernvilla!
