### ISSUE TITLE
You are trying to `import` a file after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by cj** [blitz-js/blitz#2334]
### What is the problem?

If all tests are skipped jest throws an error.

### Paste all your error logs here:

```
➜ yarn test
yarn run v1.22.4
$ jest

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at getConfig (node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:48:18)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at getConfig (node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:90:40)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at getConfig (node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:48:18)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at getConfig (node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:90:40)

Test Suites: 3 skipped, 0 of 3 total
Tests:       4 skipped, 4 total
Snapshots:   0 total
Time:        6.497 s, estimated 18 s
Ran all test suites in 2 projects.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. blitz new testapp
2. cd testapp
3. change `it` to `it.skip` in all tests.
4. run `yarn test`

### Run `blitz -v` and paste the output here:

```
➜ blitz -v
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.34.3 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 171.30 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.asdf/installs/nodejs/14.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.12.1 - ~/.asdf/installs/nodejs/14.16.1/.npm/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.3 => 0.34.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by juan-manuel-alberro** [comment]
Same here, the tests are passing but this `ReferenceError` is killing my CI with the exit code 1.

**Comment by divpreet** [comment]
Not sure if this helps anyone, but I think this seems to be happening when there are tests for queries or mutations as I am seeing in my case. I haven't found a solution for it yet.
