### ISSUE TITLE
Error when calling getSession from getServerSideProps after deployment

### ISSUE THREAD

**Issue by acornellier** [blitz-js/blitz#2365]
### What is the problem?

Both 0.34.3 and 0.35.0 cause an error. It works fine in dev, it only fails in prod after I deploy with Vercel.

### Paste all your error logs here:

```
2021-05-19T17:34:39.658Z	aef8d865-d9a6-4de0-ab00-a6c0d4fdc5dd	ERROR	Unhandled error during request: TypeError: Cannot read property 'sameSite' of undefined
    at setAnonymousSessionCookie (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:959:36)
    at createNewSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1146:5)
    at createAnonymousSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1224:16)
    at getSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:686:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /var/task/.next/serverless/pages/index.js:1409:19
2021-05-19T17:34:39.667Z	aef8d865-d9a6-4de0-ab00-a6c0d4fdc5dd	ERROR	TypeError: Cannot read property 'sameSite' of undefined
    at setAnonymousSessionCookie (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:959:36)
    at createNewSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1146:5)
    at createAnonymousSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1224:16)
    at getSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:686:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /var/task/.next/serverless/pages/index.js:1409:19
2021-05-19T17:34:39.668Z	aef8d865-d9a6-4de0-ab00-a6c0d4fdc5dd	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'sameSite' of undefined","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'sameSite' of undefined","stack":["TypeError: Cannot read property 'sameSite' of undefined","    at setAnonymousSessionCookie (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:959:36)","    at createNewSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1146:5)","    at createAnonymousSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1224:16)","    at getSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:686:27)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async /var/task/.next/serverless/pages/index.js:1409:19"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'sameSite' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred
```

### Paste all relevant code snippets here:

```ts
export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await getSession(req, res)

  if (session.userId) {
    return {
      redirect: {
        destination: `/dashboard`,
        permanent: false,
      },
    }
  }

  return { props: {} }
}
```

### What are detailed steps to reproduce this?

1. Call `getSession` from `getServerSideProps`
2. Deploy with Vercel

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.34.3 (global)
blitz: 0.35.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/28884_1621442823210/bin/node
    Yarn: 1.22.10 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/28884_1621442823210/bin/yarn
    npm: 7.12.0 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/28884_1621442823210/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.23.0 => 2.23.0
    blitz: 0.35.0 => 0.35.0
    prisma: 2.23.0 => 2.23.0
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: 4.2.4 => 4.2.4
```

**Comment by acornellier** [comment]
Looks like I'm getting more errors on 0.35.0, even without `getServerSideProps`. For example, when trying to log in I get
```
2021-05-19T17:38:13.374Z	f372188f-cf99-4dd6-945e-87e87d293b7c	ERROR	Error: Missing Blitz sessionMiddleware!
    at assert (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1460:25)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1511:11
    at dispatch (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:151:32)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:183:41
    at SessionStrategy.strategy.pass (/var/task/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at SessionStrategy.authenticate (/var/task/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/var/task/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/var/task/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:182:5
    at new Promise (<anonymous>)
2021-05-19T17:38:13.374Z	f372188f-cf99-4dd6-945e-87e87d293b7c	ERROR	Error: Missing Blitz sessionMiddleware!
    at assert (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1460:25)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1511:11
    at dispatch (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:151:32)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:183:41
    at SessionStrategy.strategy.pass (/var/task/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at SessionStrategy.authenticate (/var/task/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/var/task/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/var/task/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:182:5
    at new Promise (<anonymous>)
2021-05-19T17:38:13.374Z	f372188f-cf99-4dd6-945e-87e87d293b7c	ERROR	Unhandled Promise Rejection 	{"stack":"Runtime.UnhandledPromiseRejection: Error: Missing Blitz sessionMiddleware!\n    at process.<anonymous> (/var/runtime/index.js:35:15)\n    at process.emit (events.js:327:22)\n    at processPromiseRejections (internal/process/promises.js:245:33)\n    at processTicksAndRejections (internal/process/task_queues.js:94:32)","message":"Error: Missing Blitz sessionMiddleware!","reason":{"stack":"Error: Missing Blitz sessionMiddleware!\n    at assert (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1460:25)\n    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1511:11\n    at dispatch (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:151:32)\n    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:183:41\n    at SessionStrategy.strategy.pass (/var/task/node_modules/passport/lib/middleware/authenticate.js:343:9)\n    at SessionStrategy.authenticate (/var/task/node_modules/passport/lib/strategies/session.js:75:10)\n    at attempt (/var/task/node_modules/passport/lib/middleware/authenticate.js:366:16)\n    at authenticate (/var/task/node_modules/passport/lib/middleware/authenticate.js:367:7)\n    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:182:5\n    at new Promise (<anonymous>)","message":"Missing Blitz sessionMiddleware!"},"promise":{}}
Unknown application error occurred
```

Here's my `blitz.config.js`
```js
const { sessionMiddleware } = require(`blitz`)

const isAuthorized = ({ ctx, args }) => {
  const requirements = args[0]
  if (!requirements) return true

  const { roles: requiredRoles, userId: requiredUserId } = requirements

  if (
    requiredRoles &&
    !ctx.session.roles.some((role) => requiredRoles.includes(role))
  ) {
    return false
  }

  if (requiredUserId !== undefined && ctx.session.userId !== requiredUserId) {
    return false
  }

  return true
}

module.exports = {
  experimental: {
    reactMode: `legacy`,
  },
  middleware: [
    sessionMiddleware({
      isAuthorized,
    }),
  ],
  images: {
    domains: [
      `${process.env.AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com`,
      `${process.env.AWS_STORAGE_BUCKET_NAME}.s3.ca-central-1.amazonaws.com`,
      `avatars.githubusercontent.com`,
    ],
  },
  async headers() {
    return [
      {
        source: `/:all*(svg|jpg|png)`,
        locale: false,
        headers: [
          {
            key: `Cache-Control`,
            value: `public, max-age=9999999999, must-revalidate`,
          },
        ],
      },
    ]
  },
}
```

**Comment by flybayer** [comment]
Sounds like it's the same issue as this: https://github.com/blitz-js/blitz/issues/794 Can you try the workaround there?

**Comment by acornellier** [comment]
That worked, thanks!

**Comment by acornellier** [comment]
OK, turns out that fixes part of the problem, which is using `getServerSideProps` + `getSession` with vercel. But there's something else going wrong with 0.35, that causes either `Cannot read property 'sameSite' of undefined` or `Error: Missing Blitz sessionMiddleware!`

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/releases/tag/v0.36.3!
