### ISSUE TITLE
Error: Cannot find module 'next/constants' in Vercel deployment

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2387]
### What is the problem?

`blitz build` fails in Vercel but suceeds locally and in CI.

Similar issue: https://github.com/blitz-js/blitz/issues/2195

### Paste all your error logs here:

Relevant logs from Vercel:

```
20:48:45.120 | &gt; blitz@0.35.0 postinstall /vercel/path0/packages/website/node_modules/blitz
-- | --
20:48:45.120 | &gt; node scripts/postinstall.js
20:48:45.470 | internal/modules/cjs/loader.js:883
20:48:45.470 | throw err;
20:48:45.470 | ^
20:48:45.470 | Error: Cannot find module 'next/constants'
20:48:45.470 | Require stack:
20:48:45.471 | - /vercel/path0/packages/website/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js
20:48:45.471 | - /vercel/path0/packages/website/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.js
20:48:45.471 | - /vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitz-data-f63b7a88.cjs.dev.js
20:48:45.471 | - /vercel/path0/packages/website/node_modules/@blitzjs/core/document/dist/blitzjs-core-document.cjs.dev.js
20:48:45.471 | - /vercel/path0/packages/website/node_modules/@blitzjs/core/document/dist/blitzjs-core-document.cjs.js
20:48:45.471 | - /vercel/path0/packages/website/node_modules/blitz/dist/blitz.cjs.dev.js
20:48:45.472 | - /vercel/path0/packages/website/node_modules/blitz/dist/blitz.cjs.js
20:48:45.472 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
20:48:45.472 | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
20:48:45.472 | at Module.require (internal/modules/cjs/loader.js:952:19)
20:48:45.472 | at require (internal/modules/cjs/helpers.js:88:18)
20:48:45.472 | at Object.getConfig (/vercel/path0/packages/website/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:114:18)
20:48:45.472 | at _getBlitzRuntimeData (/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitz-data-f63b7a88.cjs.dev.js:29:25)
20:48:45.472 | at Object.getBlitzRuntimeData (/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitz-data-f63b7a88.cjs.dev.js:43:12)
20:48:45.472 | at initializeQueryClient (/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js:216:26)
20:48:45.472 | at Object.&lt;anonymous&gt; (/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js:235:32)
20:48:45.472 | at Module._compile (internal/modules/cjs/loader.js:1063:30) {
20:48:45.472 | code: 'MODULE_NOT_FOUND',
20:48:45.472 | requireStack: [
20:48:45.472 | '/vercel/path0/packages/website/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js',
20:48:45.473 | '/vercel/path0/packages/website/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.js',
20:48:45.473 | '/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitz-data-f63b7a88.cjs.dev.js',
20:48:45.473 | '/vercel/path0/packages/website/node_modules/@blitzjs/core/document/dist/blitzjs-core-document.cjs.dev.js',
20:48:45.473 | '/vercel/path0/packages/website/node_modules/@blitzjs/core/document/dist/blitzjs-core-document.cjs.js',
20:48:45.473 | '/vercel/path0/packages/website/node_modules/blitz/dist/blitz.cjs.dev.js',
20:48:45.473 | '/vercel/path0/packages/website/node_modules/blitz/dist/blitz.cjs.js'
20:48:45.473 | ]
20:48:45.473 | }
...
20:49:09.060 | Warning: Could not identify Next.js version, ensure it is defined as a project dependency.
-- | --
20:49:09.066 | Error: No Next.js version could be detected in your project. Make sure `"next"` is installed in "dependencies" or "devDependencies"
```

### What are detailed steps to reproduce this?

 `blitz build` in Vercel

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.15.5

blitz: 0.34.3 (global)
blitz: 0.35.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 5.96 GB / 15.94 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.35.0 => 0.35.0
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by ajwgeek** [comment]
I am experiencing a similar issue, but with the "next" package and Cloud Run. I was in the process of upgrading to 0.35, but I don't have many clues beyond that yet :/. I will certainly check back if I can get this solved!

**Comment by remjx** [comment]
Looking back at my Vercel deployment history it was definitely caused by something during the upgrade from 0.34 to 0.35.

I'm trying to pinpoint it now.

**Comment by remjx** [comment]
Installing `next@10.2.0` as a dependency resolves this error, but the build is still failing with other errors. I've created a separate issue for the new errors: https://github.com/blitz-js/blitz/issues/2388

If `next` is required as a dependency for Vercel deployments, should we update the "Deploy Serverless to Vercel" guide in the docs? 

Should I keep this issue open in case there is another solution to this problem besides installing a redundant dependency?

**Comment by flybayer** [comment]
Yeah keep this open. Installing next as a dependency will likely break in unexpected ways. Could be an issue with Vercel. I'll try to look into this soon (this week)

**Comment by flybayer** [comment]
I think the temporary workaround is to change your install command in the Vercel project settings to be `rm -rf node_modules && npm install`

**Comment by ajwgeek** [comment]
Same situation on Cloud Run. It's as if the node modules folder isn't being created from `npm install` even though there are no errors.

**Comment by flybayer** [comment]
Ok please try https://github.com/blitz-js/blitz/releases/tag/v0.36.2 — hopefully fixed!
