### ISSUE TITLE
"TypeError: Cannot read property 'asPath' of null" during Vercel build

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2388]
### What is the problem?

Build step fails in Vercel deployment.

Note: This is only after installing `next` as a dependency as described here https://github.com/blitz-js/blitz/issues/2387

### Paste all your error logs here:

```
10:10:54.262  	info  - Creating an optimized production build...
10:10:55.249  	info  - Using external babel configuration from /vercel/path0/packages/website/babel.config.js
10:11:34.376  	info  - Compiled successfully
10:11:34.376  	info  - Collecting page data...
10:11:38.864  	info  - Generating static pages (0/15)
10:11:41.442  	Unhandled error during request: TypeError: Cannot read property 'asPath' of null
10:11:41.442  	    at useRouterQuery (/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.prod.js:43:14)
10:11:41.442  	    at useRouter (/vercel/path0/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.prod.js:185:15)
10:11:41.442  	    at App (/vercel/path0/packages/website/.next/serverless/pages/pay-widget.js:3729:44)
10:11:41.442  	    at d (/vercel/path0/packages/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
10:11:41.442  	    at $a (/vercel/path0/packages/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
10:11:41.442  	    at a.b.render (/vercel/path0/packages/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:48)
10:11:41.442  	    at a.b.read (/vercel/path0/packages/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
10:11:41.442  	    at exports.renderToString (/vercel/path0/packages/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:138)
10:11:41.442  	    at Object.renderPage (/vercel/path0/packages/website/node_modules/next/dist/next-server/server/render.js:54:854)
10:11:41.442  	    at Function.getInitialProps (/vercel/path0/packages/website/node_modules/@blitzjs/core/node_modules/next/dist/pages/_document.js:7:159)
```

A similar error is generated for each page it's trying to prerender.

### What are detailed steps to reproduce this?

`blitz build` in Vercel

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.16.1

blitz: 0.34.1 (global)
blitz: 0.35.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 3.08 GB / 15.42 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.35.0 => 0.35.0
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by flybayer** [comment]
Is this after you added `next` as a dependency of your app?

**Comment by remjx** [comment]
> Is this after you added `next` as a dependency of your app?

Yes, sorry I forgot to include that little tidbit.

**Comment by flybayer** [comment]
Ok, then closing as unsupported. Will fix the underlying issue
