### ISSUE TITLE
"TypeError: Cannot read property 'asPath' of null" on pages with useRouter during static prerendering

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2423]
### What is the problem?

My project builds successfully locally (Windows 10) and in production (Vercel), but in CI (GitHub Actions, Ubuntu 20.04.2) I am getting this error during the static prerendering phase:

```
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'asPath' of null
    at useRouterQuery (/home/runner/work/my-app/my-app/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js:44:14)
```

I'm not sure how applicable this is, but for completeness, note that my local environment and CI are installed & built with my blitz app as part of a lerna monorepo but no dependencies are hoisted. When I deploy to Vercel, my blitz app is deployed by itself and references the published npm packages.

### Paste all your error logs here:

```
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'asPath' of null
    at useRouterQuery (/home/runner/work/my-app/my-app/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js:44:14)
    at useRouter (/home/runner/work/my-app/my-app/packages/website/node_modules/@blitzjs/core/dist/blitzjs-core.cjs.dev.js:186:15)
    at App (/home/runner/work/my-app/my-app/packages/website/.next/server/pages/_app.js:1039:44)
    at processChild (/home/runner/work/my-app/my-app/packages/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3367:14)
    at resolve (/home/runner/work/my-app/my-app/packages/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3284:5)
    at ReactDOMServerRenderer.render (/home/runner/work/my-app/my-app/packages/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3767:22)
    at ReactDOMServerRenderer.read (/home/runner/work/my-app/my-app/packages/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3704:29)
    at renderToString (/home/runner/work/my-app/my-app/packages/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:4349:27)
    at Object.renderPage (/home/runner/work/my-app/my-app/packages/website/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/home/runner/work/my-app/my-app/packages/website/node_modules/@blitzjs/core/node_modules/next/dist/pages/_document.js:9:159)
```

A similar error is generated for any page with `useRouter` hook.

### What are detailed steps to reproduce this?

1. `blitz build` in CI

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.16.1

blitz: 0.36.3 (global)
blitz: 0.36.3 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 4.64 GB / 15.42 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.36.3 => 0.36.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by remjx** [comment]
Just had a passing build so doesn't seem like a Blitz issue. Not sure what caused this. Closing for now. Will report back here with any findings.

**Comment by remjx** [comment]
So this error happens in CI when my Lerna monorepo leaf package versions are set in the leaf package-lock.json files (I had to do this to get deployment to work, but didn't realize it was breaking CI). My solution for now is to continue to generate lockfiles with `lerna bootstrap` (which does not put leaf packages in package-lock.json) and in deployment/Vercel change the install script to first run `npm install --package-lock-only` which adds the latest version of leaf packages to package-lock before install.

**Comment by flybayer** [comment]
If you can, I highly recommend not using lerna for the monorepo linking. Instead use yarn or npm workspaces. You can still use lerna for running scripts with this setup.
