### ISSUE TITLE
`Error: @prisma/client did not initialize yet` when using pnpm

### ISSUE THREAD

**Issue by vjpr** [blitz-js/blitz#2437]
### What is the problem?

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/xxx/node_modules/.pnpm/@prisma+client@2.20.1_prisma@2.20.1/node_modules/.prisma/client/index.js:3:11)
    at Object._construct (/xxx/node_modules/.pnpm/@blitzjs+core@0.36.3_2fc1fc8f84c8fdf725b301b2ee1bb31e/node_modules/@blitzjs/core/dist/constants-39a4c092.cjs.dev.js:121:21)
```

`@blitzjs/core` depends on `@prisma/client`, but in pnpm this doesn't resolve to the local project `node_modules` which is where `prisma generate` puts it.

This is caused mostly by prisma's practice of placing generating code into a project's `node_modules` dir.

The fix is usually to set the prisma client generated location in `schema.prisma`. Something like this:

```
generator client {
  provider = "prisma-client-js"
  output = "./client"
}
```

Blitz should not depend on `@prisma/client` as a dependency, but should rather generate it inside the project directory.

Otherwise, prisma will look for `.prisma` directory.

**Comment by vjpr** [comment]
I didn't see `db`...
