### ISSUE TITLE
Image domain error when using SSR

### ISSUE THREAD

**Issue by acornellier** [blitz-js/blitz#2440]
### What is the problem?
https://codesandbox.io/s/heuristic-frog-qzvhy?file=/blitz.config.js

When I use `getServerSideProps`, and I render an `<Image />`, an error is thrown that says 
```
Error: Invalid src prop (https://storage.googleapis.com/[...].jpg) on `next/image`, hostname "storage.googleapis.com" is not configured under images in your `next.config.js`
```

But I definitely have the domain configured in `blitz.config.js`
```
  images: {
    domains: [`storage.googleapis.com`],
  },
```

Interestingly, it works after deploying with Vercel...

### Paste all your error logs here:

```
Error: Invalid src prop (https://storage.googleapis.com/coleuspics/photos/user-Monkey/IMG_2756.jpg) on `next/image`, hostname "storage.googleapis.com" is not configured under images in your `next.config.js`
See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
    at defaultLoader (/Users/acornellier/git/Leaflet/node_modules/next/dist/client/image.js:43:830)
    at defaultImageLoader (/Users/acornellier/git/Leaflet/node_modules/next/dist/client/image.js:17:260)
    at /Users/acornellier/git/Leaflet/node_modules/next/dist/client/image.js:11:410
    at Array.map (<anonymous>)
    at generateImgAttrs (/Users/acornellier/git/Leaflet/node_modules/next/dist/client/image.js:11:396)
    at Image (/Users/acornellier/git/Leaflet/node_modules/next/dist/client/image.js:32:1038)
    at processChild (/Users/acornellier/git/Leaflet/node_modules/react-dom/cjs/react-dom-server.node.development.js:3367:14)
    at resolve (/Users/acornellier/git/Leaflet/node_modules/react-dom/cjs/react-dom-server.node.development.js:3284:5)
    at ReactDOMServerRenderer.render (/Users/acornellier/git/Leaflet/node_modules/react-dom/cjs/react-dom-server.node.development.js:3767:22)
    at ReactDOMServerRenderer.read (/Users/acornellier/git/Leaflet/node_modules/react-dom/cjs/react-dom-server.node.development.js:3704:29)
    at renderToString (/Users/acornellier/git/Leaflet/node_modules/react-dom/cjs/react-dom-server.node.development.js:4349:27)
    at renderPage (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/render.js:54:854)
    at Object.ctx.renderPage (webpack-internal:///./app/pages/_document.tsx:52:28)
    at Function.getInitialProps (/Users/acornellier/git/Leaflet/node_modules/next/dist/pages/_document.js:9:159)
    at Function.getInitialProps (webpack-internal:///./app/pages/_document.tsx:63:96)
    at loadGetInitialProps (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/lib/utils.js:5:101)
```

### Paste all relevant code snippets here:

```
  images: {
    domains: [`storage.googleapis.com`],
  },
```

```
export const getServerSideProps = async ({
  params,
  req,
  res,
}: GetServerSidePropsContext<{ speciesName: string }>) => {
  const species = await invokeWithMiddleware(
    getSpecies,
    { name: params!.speciesName },
    { req, res },
  )

  return { props: { initialData: species } }
}
```

### What are detailed steps to reproduce this?

1. Write a page that uses an `<Image />` with a configured domain
2. Render the page using `getServerSideProps

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.36.3 (global)
blitz: 0.36.3 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 347.57 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/832_1622145390038/bin/node
    Yarn: 1.22.10 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/832_1622145390038/bin/yarn
    npm: 7.12.0 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/832_1622145390038/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.24.0 => 2.24.0
    blitz: 0.36.3 => 0.36.3
    prisma: 2.24.0 => 2.24.0
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: 4.2.4 => 4.2.4
```

### Please include below any other applicable logs and screenshots that show your problem:

Rolling back to 0.34 did not help. 
Deleting `node_modules`, `.blitz`, and `.next` did not help.

This does not help:
```
  path.resolve(`next.config.js`)
  path.resolve(`blitz.config.js`)
  path.resolve(`.next/blitz/db.js`)
```

Seems like the same issue as https://github.com/blitz-js/blitz/issues/1737

**Comment by Roesh** [comment]
I ran into this same issue when I was working on the Blitz docs. Locally it didn't work, but when Vercel bot made a preview deployment it worked: 
https://github.com/blitz-js/blitzjs.com/pull/474#issuecomment-839672652

**Comment by flybayer** [comment]
Thanks for the report @acornellier — this is odd. 

Ready for someone to investigate

**Comment by acornellier** [comment]
After some investigation, it seems that image config is loaded when `next/image` is imported here
https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/client/image.tsx#L94

The file is being imported before the environment variable is set up here
https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/build/webpack-config.ts#L1085

Not sure how to progress from here @flybayer.

**Comment by mabadir** [comment]
Hi @acornellier, thanks for the additional context and information, I have assigned the issue to myself, I will be digging a bit. Please feel free to share any other findings.

**Comment by flybayer** [comment]
@mabadir This should be fixed with two changes.

```diff
-Image: '@blitzjs/core/image',
+Image: '@blitzjs/core/image',
```


https://github.com/blitz-js/blitz/blob/canary/packages/babel-preset/src/rewrite-imports.ts#L11
