### ISSUE TITLE
Error when installing Passport Twitter Auth in NPM - ERR! No matching version found for next@10.2.3-0.36.3.

### ISSUE THREAD

**Issue by AxDSan** [blitz-js/blitz#2442]
### What is the problem?

I'm trying to complete the passport authentication guide, but I'm unable to complete this as `passport-twitter` fails to install in my system.

### Paste all your error logs here:

```
2295 verbose stack next: No matching version found for next@10.2.3-0.36.3.
2295 verbose stack     at pickManifest (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
2295 verbose stack     at C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:43:18
2295 verbose stack     at tryCatcher (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2295 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
2295 verbose stack     at Promise._settlePromise (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
2295 verbose stack     at Promise._settlePromise0 (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
2295 verbose stack     at Promise._settlePromises (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
2295 verbose stack     at _drainQueueStep (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
2295 verbose stack     at _drainQueue (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
2295 verbose stack     at Async._drainQueues (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
2295 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\NullByte\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
2295 verbose stack     at processImmediate (internal/timers.js:456:21)
2296 verbose cwd C:\Users\NullByte\Desktop\blitztest
2297 verbose Windows_NT 10.0.19041
2298 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\NullByte\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "passport-twitter"
2299 verbose node v12.18.4
2300 verbose npm  v6.14.11
2301 error code ETARGET
2302 error notarget No matching version found for next@10.2.3-0.36.3.
2303 error notarget In most cases you or one of your dependencies are requesting
2303 error notarget a package version that doesn't exist.
2303 error notarget
2303 error notarget It was specified as a dependency of '@blitzjs/core'
2304 verbose exit [ 1, true ]

```

### Paste all relevant code snippets here:

```
npm i passport-twitter
```

### What are detailed steps to reproduce this?

1. Install Blitz with: `> npm i -g blitz --legacy-peer-deps`
2. Make a new app project: `> blitz new myapp`
3. Add the [skeleton](https://blitzjs.com/docs/passportjs#2-add-a-passport-strategy) for adding passport-twitter to authentication.
4. Add passport-twitter with: `> npm i passport-twitter`
5. Error should come up.

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v12.18.4

blitz: 0.36.3 (global)
blitz: 0.36.3 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19041
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 11.64 GB / 31.93 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.36.3 => 0.36.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by AxDSan** [comment]
Solved this by doing: `> npm update`
