### ISSUE TITLE
 Warning: You have created conflicting page routes:

### ISSUE THREAD

**Issue by raghav0622** [blitz-js/blitz#2460]
### What is the problem?

After upgrading version of blitz by running blitz new app-name and skipping the undesired differences. there is this error without -  

```
 Warning: You have created conflicting page routes:
  err.paths.forEach(function (page) {
            ^
```
....

I have tried deleting node_modules, .blitz folder, and complete fresh installation, restarting server, re-installing windows and what not.
There is no other error with previouse version

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
\app\pages\login.tsx✕ Warning: You have created conflicting page routes:
C:\dev\chanakya\node_modules\@blitzjs\server\dist\blitzjs-server.cjs.dev.js:1134
  err.paths.forEach(function (page) {
            ^

TypeError: Cannot read property 'forEach' of undefined
    at renderDuplicatePathError (C:\dev\chanakya\node_modules\@blitzjs\server\dist\blitzjs-server.cjs.dev.js:1134:13)
    at Transform.<anonymous> (C:\dev\chanakya\node_modules\@blitzjs\server\dist\blitzjs-server.cjs.dev.js:1105:7)
    at Transform.emit (events.js:388:22)
    at addChunk (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_readable.js:280:11)        
    at Transform.Readable.push (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_readable.js:241:10) 
    at Transform.push (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Transform.afterTransform (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:88:10)
    at Transform.transform [as _transform] (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\through2\through2.js:22:39)
    at Transform._read (C:\dev\chanakya\node_modules\@blitzjs\file-pipeline\node_modules\readable-stream\lib\_stream_transform.js:177:10)        
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\dev\chanakya> 
```

### What are detailed steps to reproduce this?

1. cd..
2. blitz new app-name
3. skip the undesired diffrence
4. yarn
5. blitz prisma migrate dev
6. yarn dev
7.

### Run `blitz -v` and paste the output here:

```

blitz: 0.36.4 (global)
blitz: 0.36.4 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.35 GB / 7.88 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.36.4 => 0.36.4
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

### Please include below any other applicable logs and screenshots that show your problem:

![Capture](https://user-images.githubusercontent.com/29769428/120956981-6e8f0d00-c772-11eb-961e-4d26a28a4e1f.PNG)

**Comment by flybayer** [comment]
Ok two issues here. Sounds like you have duplicate pages and secondly for some reason the error reporting for this is broken on, maybe, just Windows.

Do you have two `login.tsx` pages? Like for example both `\app\pages\login.tsx` and `\app\auth\pages\login.tsx`

**Comment by raghav0622** [comment]
> Ok two issues here. Sounds like you have duplicate pages and secondly for some reason the error reporting for this is broken on, maybe, just Windows.
> 
> Do you have two `login.tsx` pages? Like for example both `\app\pages\login.tsx` and `\app\auth\pages\login.tsx`

No i double checked for duplicate names for files, componentes and exports

**Comment by flybayer** [comment]
Ok then can you provide a repo that reproduces this problem?

**Comment by flybayer** [comment]
Actually one thing for you to try: delete `.blitz` folder and see if you still have the issue

**Comment by MrLeebo** [comment]
Closing this for staleness and a repro was never provided
