### ISSUE TITLE
RedirectError should be caught by default

### ISSUE THREAD

**Issue by thangngoc89** [blitz-js/blitz#2518]
### What is the problem?

RedirectError introduced since version 0.38.0 should be caught by default instead of throwing error in console.
Problems with this is end-to-end testing framework like Cypress treats this as error.
Error reporting service like Sentry also treats this as error and showing red in all over the places.

### Paste all your error logs here:

```
Uncaught RedirectError: /
Wrapper @ constants-378dbd5c.esm.js?1ace:153
RedirectError @ constants-378dbd5c.esm.js?1ace:340
BlitzInnerRoot @ blitzjs-core.esm.js?4e31:787
renderWithHooks @ react-dom.development.js?a814:15471
updateFunctionComponent @ react-dom.development.js?a814:18539
beginWork @ react-dom.development.js?a814:20476
callCallback @ react-dom.development.js?a814:4006
invokeGuardedCallbackDev @ react-dom.development.js?a814:4055
invokeGuardedCallback @ react-dom.development.js?a814:4117
beginWork$1 @ react-dom.development.js?a814:25884
performUnitOfWork @ react-dom.development.js?a814:24995
workLoopSync @ react-dom.development.js?a814:24917
renderRootSync @ react-dom.development.js?a814:24885
performConcurrentWorkOnRoot @ react-dom.development.js?a814:24294
workLoop @ scheduler.development.js?e22e:253
flushWork @ scheduler.development.js?e22e:226
performWorkUntilDeadline @ scheduler.development.js?e22e:516
react_devtools_backend.js:2560 The above error occurred in the <BlitzInnerRoot> component:

    at BlitzInnerRoot (webpack-internal:///../../node_modules/@blitzjs/core/dist/blitzjs-core.esm.js:871:5)
    at Layout (webpack-internal:///./app/core/layouts/Layout.tsx:14:20)
    at ErrorBoundary (webpack-internal:///../../node_modules/@blitzjs/core/dist/blitzjs-core.esm.js:520:35)
    at Suspense
    at App (webpack-internal:///./pages/_app.tsx:28:25)
    at Hydrate (webpack-internal:///../../node_modules/react-query/es/hydration/react.js:28:23)
    at QueryClientProvider (webpack-internal:///../../node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at BlitzProvider (webpack-internal:///../../node_modules/@blitzjs/core/dist/blitzjs-core.esm.js:469:21)
    at BlitzOuterRoot (webpack-internal:///../../node_modules/@blitzjs/core/dist/blitzjs-core.esm.js:934:15)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:160:5)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:649:24)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:785:25)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Paste all relevant code snippets here:

none

### What are detailed steps to reproduce this?

1. `blitz new reproduce`
2. `blitz dev`
3. Go to http://localhost:3000/signup
4. After sign up, errors will appear in browser's console.

### Run `blitz -v` and paste the output here:

```
macOS Mojave | darwin-x64 | Node: v14.15.2

blitz: 0.38.1 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 191.40 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.15.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.25.0 => 2.25.0 
    blitz: 0.38.1 => 0.38.1 
    prisma: 2.25.0 => 2.25.0 
    react: alpha => 18.0.0-alpha-568dc3532 
    react-dom: alpha => 18.0.0-alpha-568dc3532 
    typescript: ~4.3 => 4.3.4 

```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/3049054/122663349-ed993200-d1c3-11eb-97e0-b00d84f46f01.png)

**Comment by flybayer** [comment]
@thangngoc89 I've opened a PR that I think will fix this for you. Can you install `blitz@0.38.2-danger.f25aac1ff.7` and let me know if it does or not?

**Comment by thangngoc89** [comment]
I can confirm that `blitz@0.38.2-danger.f25aac1ff.7` fixes this error.
Thank you very much

**Comment by akbo** [comment]
Hi there,

It appears that this error is present in `blitz@0.38.6`. Strangely, the error doesn't show up in Console, but still fails my Cypress test (see screenshot), which as far as I understand means that I cannot test anything involving `BlitzPage.redirectAuthenticatedTo`.

<img width="1787" alt="Screenshot 2021-08-03 at 10 20 25" src="https://user-images.githubusercontent.com/1926271/127986142-89739e48-4e36-436b-ba1f-7cccc4d9b9c9.png">

### Steps to reproduce what you see on the above screenshot

1. `blitz new reproduce`
2. `cd reproduce`
2. `blitz dev`
3. Run the following Cypress test

```
const random = (length = 8) => {
  return Math.random().toString(16).substr(2, length)
}

describe("Blitz Sign Up", () => {
  it("Signs up", () => {
    cy.visit("http://localhost:3000")

    cy.contains("Sign Up").click()

    // Use a random email address so we can run this test many times from any Cypress instance without having to reset the database.
    cy.get("input[name=email]").type(random() + "@example.com")
    cy.get("input[name=password").type("0123456789")
    cy.get("button").click()

    // Do a random thing so Cypress test fails (it apparently doesn't fail if only the very last thing you do throws an uncaught exception).
    cy.contains("Documentation").click()
  })
})
```

### Output of `blitz -v`
```
macOS Big Sur | darwin-x64 | Node: v14.17.4

blitz: 0.38.6 (global)
blitz: 0.38.6 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.18 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.28.0 => 2.28.0
    blitz: 0.38.6 => 0.38.6
    prisma: 2.28.0 => 2.28.0
    react: alpha => 18.0.0-alpha-e3b76a85c-20210802
    react-dom: alpha => 18.0.0-alpha-e3b76a85c-20210802
    typescript: ~4.3 => 4.3.5
```

**Comment by flybayer** [comment]
@akbo can you please open a new issue for that?

**Comment by akbo** [comment]
Sure, you can find the new issue here: #2633
