### ISSUE TITLE
Blitz start is crashing on compile errors with UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#263]
### What is the problem?

`blitz start` fails on some type of compile error, like trying to import a non-existent dependency.

The actual `blitz start` process keeps running, but the spawned `next` process crashes and isn't restarted

### Steps to Reproduce: 

1. Checkout latest canary
2. `yarn`
3. `yarn build`
4. `cd examples/tailwind`
5. `yarn remove tailwindcss`
6. `blitz start`
7. See error

### Supporting Documentation

```
Warning: You have enabled experimental feature(s).
Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Error: Cannot find module 'tailwindcss' from '/Users/b/c/blitz/examples/tailwind/.blitz/caches/dev/'
    at Function.e.exports [as sync] (/Users/b/c/blitz/node_modules/next/dist/compiled/resolve/index.js:1:1388)
    at resolveRequest (/Users/b/c/blitz/node_modules/next/dist/lib/resolve-request.js:4:287)
    at loadPlugin (/Users/b/c/blitz/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:1:1667)
    at /Users/b/c/blitz/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:7:1761
    at Array.map (<anonymous>)
    at getPostCssPlugins (/Users/b/c/blitz/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:7:1754)
    at async __overrideCssConfiguration (/Users/b/c/blitz/node_modules/next/dist/build/webpack/config/blocks/css/overrideCssConfiguration.js:1:272)
    at async getBaseWebpackConfig (/Users/b/c/blitz/node_modules/next/dist/build/webpack-config.js:101:120)
    at async Promise.all (index 0)
    at async HotReloader.start (/Users/b/c/blitz/node_modules/next/dist/server/hot-reloader.js:14:1788)
    at async DevServer.prepare (/Users/b/c/blitz/node_modules/next/dist/server/next-dev-server.js:10:1565)
    at async /Users/b/c/blitz/node_modules/next/dist/cli/next-dev.js:21:359 {
  code: 'MODULE_NOT_FOUND'
}
(node:44344) UnhandledPromiseRejectionWarning: 'next build' failed with status code: 1
(node:44344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Processing file...package.json
```

**Comment by flybayer** [comment]
This same crash occurs if you are using a component from `app/components/Thing.js` and you change the code inside `Thing.js` while blitz is running

**Comment by ryardley** [comment]
Having reproducability issues. Is it possible to be more explicit about steps to reproduce?

**Comment by ryardley** [comment]
Oh is this in a `js` project?

**Comment by ryardley** [comment]
I am still struggling to reproduce within the example app in the monorepo. Perhaps you can share a repository?

**Comment by flybayer** [comment]
@ryardley I just updated the issue with exact steps — sorry about that

**Comment by ryardley** [comment]
Ok great will try

**Comment by flybayer** [comment]
Also I just verified that Next.js **does** exit with an error for this, so we need to just exit too.

**Comment by flybayer** [comment]
And I can't reproduce the error I saw when changing the component file

**Comment by ryardley** [comment]
Issue is a missing `await`

**Comment by flybayer** [comment]
While you are at it, it looks like the log for this prints `next build` but it should be `next dev`, right?

**Comment by ryardley** [comment]
Yep I am onto that. Just making tests work with passing in a mock synchronizer
