### ISSUE TITLE
passportAuth - provide better error message if `req.query.auth` is undefined

### ISSUE THREAD

**Issue by Nfinished** [blitz-js/blitz#2717]
## Updated Issue

The below issue was caused because the file was not named `[...auth].js`, it was named something like `passport.js`. And in this case `auth` is not a dynamic param and so `req.query.auth` is undefined.

We need to provide helpful error in these two cases:
1. `req.query.auth` not defined - page must be named `[...auth].js/ts`
2. `req.query.auth` is defined, but not array - page must be named `[...auth].js/ts`

This should be added just before this line: https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib-server/passport-adapter.ts#L104

- updated by @flybayer 

### What is the problem?

`req.query.auth` is undefined [here](https://github.com/blitz-js/blitz/blob/cefb5c18ce659d29f8c916e16bd8fa512dc4f168/nextjs/packages/next/stdlib-server/passport-adapter.ts#L104) when it's expected to be a string or string[]. In fact, `req.query` is an empty object. I'm seeing this behavior regardless of strategy, including a straight copy of the twitter example in the [docs](https://blitzjs.com/docs/passportjs)

### Paste all your error logs here:

```
TypeError: Cannot read property 'length' of undefined
    at authHandler (/Users/***/Nfinished/***/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.dev.js:1548:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async apiResolver (/Users/***/Nfinished/***/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/Users/***/Nfinished/***/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/Users/***/Nfinished/***/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/Users/***/Nfinished/***/node_modules/next/dist/next-server/server/router.js:26:67)
    at async DevServer.run (/Users/***/Nfinished/***/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/Users/***/Nfinished/***/node_modules/next/dist/next-server/server/next-server.js:32:504)
```

### Paste all relevant code snippets here:

```ts
// app/api/auth/[...auth].ts
import { passportAuth } from "blitz"
import db from "db"
import EveOnlineStrategy from "passport-eveonline-v2"

export default passportAuth({
  successRedirectUrl: "/",
  errorRedirectUrl: "/",
  strategies: [
    {
      authenticateOptions: {
        scope: "publicData",
      },
      strategy: new EveOnlineStrategy(
        {
          clientID: process.env.EVEONLINE_CLIENT_ID as string,
          secretKey: process.env.EVEONLINE_SECRET_KEY as string,
          callbackURL: `${process.env.BASE_URL}/api/auth/eveonline-v2/callback`,
        },
        async function (accessToken, refreshToken, profile, done) {
          console.log("profile", profile)
          done(undefined, { publicData: profile })
        }
      ),
    },
  ],
})

```

or code from docs https://blitzjs.com/docs/passportjs

### What are detailed steps to reproduce this?

1. Create any passport auth strategy
2. visit page in browser (api/auth/\<whatever\>)
3. 500

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v16.4.2

blitz: 0.39.0 (global)
blitz: 0.39.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 1.59 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - ~/.asdf/installs/nodejs/16.4.2/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.18.1 - ~/.asdf/installs/nodejs/16.4.2/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.31.0-integration-undici-4.3 => 2.31.0-integration-undici-4.3
    blitz: 0.39.0 => 0.39.0
    prisma: 2.31.0-integration-undici-4.3 => 2.31.0-integration-undici-4.3
    react: alpha => 18.0.0-alpha-50263d327-20210914
    react-dom: alpha => 18.0.0-alpha-50263d327-20210914
    typescript: ~4.3 => 4.3.5
```

**Comment by Nfinished** [comment]
Closing, pebcak

**Comment by Nfinished** [comment]
reopening re: @flybayer (only _mostly_ pebcak). Nuking `.blitz` eventually worked.

**Comment by prosoftwaredev** [comment]
> TypeError: Cannot read property 'length' of undefined
    at authHandler (D:\WorkSpace\test\node_modules\@blitzjs\core\server\dist\blitzjs-core-server.cjs.dev.js:1544:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async apiResolver (D:\WorkSpace\test\node_modules\next\dist\next-server\server\api-utils.js:8:1)
    at async DevServer.handleApiRequest (D:\WorkSpace\test\node_modules\next\dist\next-server\server\next-server.js:66:462)
    at async Object.fn (D:\WorkSpace\test\node_modules\next\dist\next-server\server\next-server.js:58:580)      
    at async Router.execute (D:\WorkSpace\test\node_modules\next\dist\next-server\server\router.js:26:67)       
    at async DevServer.run (D:\WorkSpace\test\node_modules\next\dist\next-server\server\next-server.js:68:1042) 
    at async DevServer.handleRequest (D:\WorkSpace\test\node_modules\next\dist\next-server\server\next-server.js:32:504)

same here

**Comment by martinsaxa** [comment]
hi, I would be happy to help with this one.

**Comment by beerose** [comment]
Please go ahead @martinsaxa!

**Comment by beerose** [comment]
Fixed in https://github.com/blitz-js/blitz/pull/2766
