### ISSUE TITLE
CSRFTokenMismatchError when logout

### ISSUE THREAD

**Issue by Vahor** [blitz-js/blitz#2746]
**Edit :** It's maybe not related to logout, I got this same error message on first load, just after starting production. And this multiples times in a row. And after some time, while I was looking in local if I hadn't broke something, it worked again ( I've cleared my cache directly after the first crash )

### What is the problem?

Hello, I have a `CSRFTokenMismatchError` error with the logout method
It's a bit random but it always happens during/after a logout

- I have already tried deleting the node_module and the .next folder and rebuilding.
- Clearing cache does not change anything
- Using development / production ( on different machines ) gives the same error

### Paste all your error logs here:

As It is a bit random, I have added logs from before the crash ( removed dates for readability )

```
login() Finished: resolver:442ms serializer:2ms total:447ms 

getCurrentUser() Starting with input: null 
getCurrentUser() Finished: resolver:89ms serializer:2ms total:91ms 
 
getNotifications() Starting with input: null 
getNotifications() Finished: resolver:30ms serializer:1ms total:31ms 

logout() Starting with input: undefined 
logout() Finished: resolver:151ms serializer:1ms total:153ms 
 
getCurrentUser() Starting with input: null 
getCurrentUser() Finished: resolver:0ms serializer:0ms total:1ms 
 
getNotifications() Starting with input: null 
getNotifications() Finished: resolver:0ms serializer:1ms total:1ms 
 
getCurrentUser() Starting with input: null 
getCurrentUser() Finished: resolver:0ms serializer:0ms total:1ms 
 
getNotifications() Starting with input: null 
getNotifications() Finished: resolver:0ms serializer:1ms total:1ms 

2021-09-25 20:41:52.813 ERROR Error while processing the request 

 CSRFTokenMismatchError  
details:
{
  name: 'CSRFTokenMismatchError',
  statusCode: 401
} 
[CSRFTokenMismatchError] { statusCode: 401 }
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END] [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:694:15)
    at ServerResponse.end (_http_outgoing.js:815:7)
    at ServerResponse.end (/home/site/node_modules/next/dist/compiled/compression/index.js:1:4179)
    at ServerResponse.apiRes.end (/home/site/node_modules/next/dist/server/api-utils.js:83:25)
    at sendError (/home/site/node_modules/next/dist/server/api-utils.js:490:9)
    at Object.apiResolver (/home/site/node_modules/next/dist/server/api-utils.js:127:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server.handleApiRequest (/home/site/node_modules/next/dist/server/next-server.js:766:9)
    at async Object.fn (/home/site/node_modules/next/dist/server/next-server.js:657:37)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:753:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

Maybe related, I got this message sooner ( only once )
```
0|site  | This request is missing the anti-csrf header. You can learn about adding this here: https://blitzjs.com/docs/session-management#manual-api-requests
```
However, I am not using any api route and this message was displayed when I called the logout method

### Paste all relevant code snippets here:

The Logout and login method are the default
The login method has a larger public data than the default one 
 

### What are detailed steps to reproduce this?

Login -> Logout

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v16.8.0

blitz: 0.39.0 (global)
blitz: 0.40.0-canary.9 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 245.10 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.1.1 => 3.1.1 
    blitz: 0.40.0-canary.9 => 0.40.0-canary.9 
    prisma: 3.1.1 => 3.1.1 
    react: alpha => 18.0.0-alpha-cb8a50619-20210909 
    react-dom: alpha => 18.0.0-alpha-cb8a50619-20210909 
    typescript: ~4.4.2 => 4.4.2 
```

**Comment by flybayer** [comment]
Would be interesting to know if it changes between `0.39.0` and `0.40.0-canary.9`

**Comment by flybayer** [comment]
Could be related to or same bug as https://github.com/blitz-js/blitz/issues/2718

**Comment by Vahor** [comment]
Hi ! @flybayer
I have created a small repro on https://github.com/Vahor/BlitzCSRFTokenMismatchError
On here I am using 0.40.0-canary.9 ; I haven't had time to try other versions yet.
But if I found something I'll let you know

**Comment by flybayer** [comment]
@Vahor awesome thanks, taking a look

**Comment by flybayer** [comment]
Ok I've reproduced and found the cause.

It happens when you have two queries in the same render and do login/logout dance.
```ts
const resA = useQuery(getA, {})
const resB = useQuery(getB, {})
```

It's a race condition where getA query creates an anon session, but getB fires off before that anon session has been fully saved on the client. So getB request has no session. And therefore getB response creates a new anon session. And then somehow wires get crossed, and csrf cookie does not match the anon session jwt.


```
17:40:30.322 INFO logout() Starting with input: undefined
  blitz:session Revoking session v2iko5zhkpMpWhTaUYrwEwcn9yfwgUil:ots +0ms
  blitz:session setCSRFCookie  +2ms
17:40:30.324 DEBUG logout() Result: undefined
17:40:30.325 DEBUG logout() Next.js serialization:1ms
17:40:30.325 INFO logout() Finished: resolver:2ms serializer:1ms total:3ms

  blitz:middleware [getAndValidateMiddleware] config.middleware [
  [Function (anonymous)] {
    config: {
      name: 'blitzSessionMiddleware',
      cookiePrefix: 'BlitzCSRFTokenMismatchError'
    }
  }
] +119ms
  blitz:middleware [getAndValidateMiddleware] resolverModule.middleware undefined +0ms
  blitz:middleware [] Starting handler... +0ms
  blitz:session Starting sessionMiddleware... +117ms
  blitz:session cookiePrefix BlitzCSRFTokenMismatchError +0ms
  blitz:session No session found, creating anonymous session +0ms
  blitz:session Creating new anonymous session +1ms
  blitz:session setCSRFCookie oMqUrLTrdrIMM_cn0lBvCGl-_0CODCUp +0ms
  blitz:middleware [] Starting handler... +1ms
17:40:30.442 INFO getCurrentUser() Starting with input: null
17:40:30.442 DEBUG getCurrentUser() Result: null
17:40:30.443 DEBUG getCurrentUser() Next.js serialization:0ms
17:40:30.443 INFO getCurrentUser() Finished: resolver:0ms serializer:0ms total:1ms

  blitz:middleware [getAndValidateMiddleware] config.middleware [
  [Function (anonymous)] {
    config: {
      name: 'blitzSessionMiddleware',
      cookiePrefix: 'BlitzCSRFTokenMismatchError'
    }
  }
] +2ms
  blitz:middleware [getAndValidateMiddleware] resolverModule.middleware undefined +0ms
  blitz:middleware [] Starting handler... +0ms
  blitz:session Starting sessionMiddleware... +2ms
  blitz:session cookiePrefix BlitzCSRFTokenMismatchError +0ms
  blitz:session No session found, creating anonymous session +1ms
  blitz:session Creating new anonymous session +0ms
  blitz:session setCSRFCookie 6ZEb52qMKKRIE7CNQOeqswIRkTaAtYE6 +0ms
  blitz:middleware [] Starting handler... +2ms
17:40:30.446 INFO getSettings() Starting with input: null
17:40:30.447 DEBUG getSettings() Result: null
17:40:30.447 DEBUG getSettings() Next.js serialization:0ms
17:40:30.448 INFO getSettings() Finished: resolver:0ms serializer:0ms total:1ms


>>>>>>> LOGOUT STARTS HERE
  blitz:middleware [getAndValidateMiddleware] config.middleware [
  [Function (anonymous)] {
    config: {
      name: 'blitzSessionMiddleware',
      cookiePrefix: 'BlitzCSRFTokenMismatchError'
    }
  }
] +10ms
  blitz:middleware [getAndValidateMiddleware] resolverModule.middleware undefined +1ms
  blitz:middleware [] Starting handler... +0ms
  blitz:session Starting sessionMiddleware... +12ms
  blitz:session cookiePrefix BlitzCSRFTokenMismatchError +0ms
  blitz:session Request has anonymousSessionToken +0ms

17:40:30.460 ERROR Error while processing the request

 CSRFTokenMismatchError
details:
{
  name: 'CSRFTokenMismatchError',
  statusCode: 401
}
[CSRFTokenMismatchError] { statusCode: 401 }
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END] [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.end (node:_http_outgoing:849:15)
    at ServerResponse.end (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/compiled/compression/index.js:1:4179)
    at ServerResponse.apiRes.end (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/server/api-utils.js:83:25)
    at sendError (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/server/api-utils.js:490:9)
    at Object.apiResolver (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/server/api-utils.js:127:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async DevServer.handleApiRequest (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/server/next-server.js:766:9)
    at async Object.fn (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/server/next-server.js:657:37)
    at async Router.execute (/private/tmp/BlitzCSRFTokenMismatchError/node_modules/next/dist/server/router.js:206:32)
Emitted 'error' event on ServerResponse instance at:
    at emitErrorNt (node:_http_outgoing:729:9)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```
