### ISSUE TITLE
Latest blitz version on Windows does not work

### ISSUE THREAD

**Issue by Roesh** [blitz-js/blitz#2765]
### What is the problem?

After installing the latest blitz version using `npm i -g blitz@latest`, there is an error preventing running any global blitz commands.

This occurred with my Windows PC. I removed blitz and reinstalled it, but still had the same issue. I then tried to do the same on my laptop and ran into the same issue.

EDIT: Current latest version is 0.39.0

### Paste all your error logs here:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\manue> blitz -v
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Windows 10 | win32-x64 | Node: v12.18.3

blitz: 0.33.1 (global)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 7.37 GB / 13.92 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found


PS C:\Users\manue> npm i -g blitz@latest
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/blitz/node_modules/react
npm WARN   peer react@"*" from @testing-library/react@11.2.5
npm WARN   node_modules/blitz/node_modules/@testing-library/react
npm WARN     @testing-library/react@"11.2.5" from blitz@0.39.0
npm WARN     node_modules/blitz
npm WARN   2 more (react-dom, @testing-library/react-hooks)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.1" from react-test-renderer@17.0.1
npm WARN node_modules/blitz/node_modules/react-test-renderer
npm WARN   react-test-renderer@"17.0.1" from blitz@0.39.0
npm WARN   node_modules/blitz
npm WARN   1 more (@testing-library/react-hooks)
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 317 packages, removed 197 packages, changed 1363 packages, and audited 1681 packages in 2m

149 packages are looking for funding
  run `npm fund` for details

7 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 7.6.3 -> 7.24.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.24.1
npm notice Run npm install -g npm@7.24.1 to update!
npm notice
PS C:\Users\manue> blitz -v
Error: Cannot find module 'next/dist/next-server/server/config-shared'
Require stack:
- C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js
- C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\cli\dist\blitz-cli.cjs.dev.js
- C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\cli\dist\blitz-cli.cjs.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Module._load (internal/modules/cjs/loader.js:841:27)
    at Function._load (C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\node_modules\@salesforce\lazy-require\lib\LazyLoader.js:99:24)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\manue\\AppData\\Roaming\\npm\\node_modules\\blitz\\node_modules\\@blitzjs\\cli\\lib\\src\\index.js',
    'C:\\Users\\manue\\AppData\\Roaming\\npm\\node_modules\\blitz\\cli\\dist\\blitz-cli.cjs.dev.js',
    'C:\\Users\\manue\\AppData\\Roaming\\npm\\node_modules\\blitz\\cli\\dist\\blitz-cli.cjs.js'
  ]
}
PS C:\Users\manue> npm i -g blitz@0.33.1
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
... ... ...
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 1802 packages, and audited 1803 packages in 2m

143 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\manue> blitz -v
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Windows 10 | win32-x64 | Node: v12.18.3

blitz: 0.33.1 (global)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 6.88 GB / 13.92 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found

blitz: 0.33.1 (global)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 6.88 GB / 13.92 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. On Windows, upgrade to the latest blitz version
2. Try to use any Windows commands

### Run `blitz -v` and paste the output here:

```
Error: Cannot find module 'next/dist/next-server/server/config-shared'
Require stack:
- C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js
- C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\cli\dist\blitz-cli.cjs.dev.js
- C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\cli\dist\blitz-cli.cjs.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Module._load (internal/modules/cjs/loader.js:841:27)
    at Function._load (C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\node_modules\@salesforce\lazy-require\lib\LazyLoader.js:99:24)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\manue\AppData\Roaming\npm\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\manue\\AppData\\Roaming\\npm\\node_modules\\blitz\\node_modules\\@blitzjs\\cli\\lib\\src\\index.js',
    'C:\\Users\\manue\\AppData\\Roaming\\npm\\node_modules\\blitz\\cli\\dist\\blitz-cli.cjs.dev.js',
    'C:\\Users\\manue\\AppData\\Roaming\\npm\\node_modules\\blitz\\cli\\dist\\blitz-cli.cjs.js'
  ]
}
```

**Comment by Roesh** [comment]
Next steps: check latest canary release.

0.40.0-canary.9 actually does not have this issue

**Comment by flybayer** [comment]
@Roesh `Cannot find module 'next/dist/server/lib/logging'` indicates that the `next` package inside your global node_modules is corrupted.

Try deleting `blitz` (not just `.blitz`), `@blitzjs`, and `next` from your global node_modules

**Comment by Roesh** [comment]
Oh, so I'm looking at my global node_modules and I don't actually see a next folder or `@blitzjs` folder, I have a .blitz folder and a blitz folder.

Though I'd confirm again, so I uninstalled blitz with `npm uninstall -g blitz`, and the global node_modules looked like this:
```
PS C:\Users\Roshan\AppData\Roaming\npm\node_modules> ls


    Directory: C:\Users\Roshan\AppData\Roaming\npm\node_modules


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/27/2021   1:01 PM                @angular
d-----          3/5/2021   5:50 PM                @preconstruct
d-----          7/7/2021  11:23 AM                expo
d-----         7/24/2021   2:16 AM                expo-cli
d-----         7/30/2021   7:24 PM                node
d-----        11/28/2020   5:20 PM                node-gyp
d-----         3/30/2021   5:22 PM                npkill
d-----         9/29/2021   9:33 PM                npm
d-----         2/14/2021   4:46 PM                npm-windows-upgrade
d-----          3/9/2021   7:58 PM                prettier
d-----          2/2/2021   7:17 PM                pwabuilder
d-----         7/10/2021   6:39 AM                redis-cli
d-----          3/8/2021   2:55 PM                typescript
d-----         7/30/2021   7:24 PM                yarn


PS C:\Users\Roshan\AppData\Roaming\npm\node_modules> ls -h
PS C:\Users\Roshan\AppData\Roaming\npm\node_modules>
```

After installation of blitz@0.40.0, I have the following folders, but still no next or `@blitzjs` folder:
```
PS C:\Users\Roshan\AppData\Roaming\npm\node_modules> ls


    Directory: C:\Users\Roshan\AppData\Roaming\npm\node_modules


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         10/3/2021   1:00 AM                .blitz
d-----         8/27/2021   1:01 PM                @angular
d-----          3/5/2021   5:50 PM                @preconstruct
d-----         10/3/2021  12:59 AM                blitz
d-----          7/7/2021  11:23 AM                expo
d-----         7/24/2021   2:16 AM                expo-cli
d-----         7/30/2021   7:24 PM                node
d-----        11/28/2020   5:20 PM                node-gyp
d-----         3/30/2021   5:22 PM                npkill
d-----         9/29/2021   9:33 PM                npm
d-----         2/14/2021   4:46 PM                npm-windows-upgrade
d-----          3/9/2021   7:58 PM                prettier
d-----          2/2/2021   7:17 PM                pwabuilder
d-----         7/10/2021   6:39 AM                redis-cli
d-----          3/8/2021   2:55 PM                typescript
d-----         7/30/2021   7:24 PM                yarn


PS C:\Users\Roshan\AppData\Roaming\npm\node_modules> ls -h
PS C:\Users\Roshan\AppData\Roaming\npm\node_modules>
```

I'm really curious why some versions work then though. I'm able to keep upgrading and downgrading blitz versions until I hit a release where blitz -v stops working.
I started with 0.33.1 which worked, 
switched to 0.37.0 which also worked, 
then 0.38.3 which didn't work, 
0.38.3-canary.0 worked, 
0.38.3-canary.1 which didn't work

I'm sure there's likely a release between 0.39.0 and 0.40.0 where blitz -v starts working but the errors with blitz new start occurring, but haven't tested which transition it occurs in.

I don't know too much about how npm on Windows differs from npm on linux so I'm having a hard time knowing where to start troubleshooting.

To make sure, I downgraded to 0.33.1 again, and looked at the folder structure, sure enough, no next or `@blitzjs` folders:
```
PS D:\QuickDocs> blitz -v
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Windows 10 | win32-x64 | Node: v15.8.0

blitz: 0.33.1 (global)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 7.78 GB / 15.93 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```
```
PS C:\Users\Roshan\AppData\Roaming\npm\node_modules> ls


    Directory: C:\Users\Roshan\AppData\Roaming\npm\node_modules


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         10/3/2021   1:00 AM                .blitz
d-----         8/27/2021   1:01 PM                @angular
d-----          3/5/2021   5:50 PM                @preconstruct
d-----         10/3/2021   1:06 AM                blitz
d-----          7/7/2021  11:23 AM                expo
d-----         7/24/2021   2:16 AM                expo-cli
d-----         7/30/2021   7:24 PM                node
d-----        11/28/2020   5:20 PM                node-gyp
d-----         3/30/2021   5:22 PM                npkill
d-----         9/29/2021   9:33 PM                npm
d-----         2/14/2021   4:46 PM                npm-windows-upgrade
d-----          3/9/2021   7:58 PM                prettier
d-----          2/2/2021   7:17 PM                pwabuilder
d-----         7/10/2021   6:39 AM                redis-cli
d-----          3/8/2021   2:55 PM                typescript
d-----         7/30/2021   7:24 PM                yarn


PS C:\Users\Roshan\AppData\Roaming\npm\node_modules> ls -h
PS C:\Users\Roshan\AppData\Roaming\npm\node_modules>
```

**Comment by flybayer** [comment]
Ok, so `@blitzjs` probably lives under `node_modules/blitz/`. Package managers keep changing where nested packages actually live. But either way, that should be fine.

Real issue here is missing `next` package which should be installed because it's set as a dependency of `@blitzjs/core` using an npm alias. However sometimes npm is broken and doesn't install that correctly, so [we have postinstall script](https://github.com/blitz-js/blitz/blob/canary/packages/blitz/scripts/postinstall.js#L84-L92) to patch it. But seems this is failing now too.

Maybe we can fix the postinstall script for now.

Beyond that, this should totally go away with coming monorepo refactor where we remove the current `blitz` package and rename current `next` package to `blitz`
