### ISSUE TITLE
0.40 canary blitz generator tests failing

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#2806]
### What is the problem?

fresh install of 0.40 fails unit tests in the generator subpackage

### Paste all your error logs here:

```
$ yarn test
yarn run v1.22.10
$ jest
 PASS  test/utils/match-between.test.ts
 PASS  test/utils/inflector.test.ts
 FAIL  test/prisma/model.test.ts   
  ● Test suite failed to run

    Cannot find module '@blitzjs/display' from 'src/prisma/field.ts'

    Require stack:
      src/prisma/field.ts
      test/prisma/model.test.ts

    > 1 | import {log} from "@blitzjs/display"
        | ^
      2 | import * as ast from "@mrleebo/prisma-ast"
      3 | import {capitalize, singlePascal, uncapitalize} from "../utils/inflector"
      4 |

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (src/prisma/field.ts:1:1)

 FAIL  test/prisma/field.test.ts
  ● Test suite failed to run

    Cannot find module '@blitzjs/display' from 'src/prisma/field.ts'

    Require stack:
      src/prisma/field.ts
      test/prisma/field.test.ts

    > 1 | import {log} from "@blitzjs/display"
        | ^
      2 | import * as ast from "@mrleebo/prisma-ast"
      3 | import {capitalize, singlePascal, uncapitalize} from "../utils/inflector"
      4 |

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (src/prisma/field.ts:1:1)

 FAIL  test/generators/app-generator.test.ts
  ● Test suite failed to run

    Cannot find module '@blitzjs/display' from 'test/generators/app-generator.test.ts'

       7 | jest.spyOn(global.console, "log").mockImplementation()
       8 | // Mocks the log output
    >  9 | jest.mock(
         |      ^
      10 |   "@blitzjs/display",
      11 |   jest.fn(() => {
      12 |     return {

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (test/generators/app-generator.test.ts:9:6)

 FAIL  test/generator.test.ts
  ● Test suite failed to run

    Cannot find module '@blitzjs/display' from 'src/generator.ts'

    Require stack:
      src/generator.ts
      test/generator.test.ts

      2 | // @ts-ignore TS wants types for this module but none exist
      3 | import babelTransformTypescript from "@babel/plugin-transform-typescript"
    > 4 | import {log} from "@blitzjs/display"
        | ^
      5 | import Enquirer from "enquirer"
      6 | import {EventEmitter} from "events"
      7 | import * as fs from "fs-extra"

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (src/generator.ts:4:1)

 FAIL  test/generators/page-generator.test.ts
  ● Test suite failed to run

    Cannot find module '@blitzjs/display' from 'src/generator.ts'

    Require stack:
      src/generator.ts
      src/generators/page-generator.ts
      test/generators/page-generator.test.ts

      2 | // @ts-ignore TS wants types for this module but none exist
      3 | import babelTransformTypescript from "@babel/plugin-transform-typescript"
    > 4 | import {log} from "@blitzjs/display"
        | ^
      5 | import Enquirer from "enquirer"
      6 | import {EventEmitter} from "events"
      7 | import * as fs from "fs-extra"

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (src/generator.ts:4:1)

Test Suites: 5 failed, 2 passed, 7 total
Tests:       26 passed, 26 total        
Snapshots:   0 total
Time:        5.084 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Paste all relevant code snippets here:

My unit test process seems unable to access the below import, although I've confirmed it's in the package.json and in my node_modules

```
import {log} from "@blitzjs/display"
```

![image](https://user-images.githubusercontent.com/5559355/136060636-b3433788-cf90-44d3-8eb0-3512314a65f8.png)

### What are detailed steps to reproduce this?

1. clone fresh 0.40 canary
2. yarn in the `blitz/packages/generator` folder and also at repo top
3. `yarn test` within `blitz/packages/generator`

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v16.2.0

blitz: 0.39.0 (global)
blitz: 0.40.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 8.27 GB / 19.86 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by flybayer** [comment]
Hey, same as the other issue, did you first run `yarn dev` or `yarn build` as it states [in the contributing docs](https://blitzjs.com/docs/contributing#development-setup)?
