### ISSUE TITLE
Cannot use multiple prisma clients

### ISSUE THREAD

**Issue by Andreychik32** [blitz-js/blitz#2974]
### What is the problem?

I want to develop a project, which will actively use 4 MySQL database connections.
As Prisma doesn't support more than one database schema connections in one `.schema` file, I've decided to follow the second advice from this GitHub issue comment: https://github.com/prisma/prisma/issues/2443#issuecomment-630679118

In the project root, I've created `db-one`, `db-two` and `db-three` directories (in real, the names are different, but this doesn't matter) and left out the default `db` directory. In this directories, I've created one `.prisma` file and one `index.js` file. The contents of these files can be seen below. Then, I've executed these commands:
`blitz prisma db pull --schema ./db-one/schema.prisma && blitz prisma generate --schema ./db-one/schema.prisma`
`blitz prisma db pull --schema ./db-two/schema.prisma && blitz prisma generate --schema ./db-two/schema.prisma`
`blitz prisma db pull --schema ./db-three/schema.prisma && blitz prisma generate --schema ./db-three/schema.prisma`

After that, I've started dev server with `yarn dev`, and got an error, which can be seen below.

### Paste all your error logs here:

Full log after running `yarn dev` and visiting root page.
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/andrii/project-name/.env.local
info  - Loaded env from /home/andrii/project-name/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - ./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
info  - ready on http://localhost:3000
event - build page: /
wait  - compiling...
info  - Using external babel configuration from /home/andrii/project-name/babel.config.js
warn  - ./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
info  - ready on http://localhost:3000
event - build page: /_error
wait  - compiling...
warn  - ./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
info  - ready on http://localhost:3000
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
event - build page: /404
wait  - compiling...
warn  - ./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./db/client/runtime/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
info  - ready on http://localhost:3000
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'os'
    at webpackEmptyContext (/home/andrii/project-name/.next/server/pages/_app.js:14:10)
    at ../../node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:41115)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/andrii/project-name/.next/server/pages/_app.js:768:48014)
    at __require2 (/home/andrii/project-name/.next/server/pages/_app.js:768:3298)
    at Object../db/client/runtime/index.js (/home/andrii/project-name/.next/server/pages/_app.js:805:750)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/client/index.js (/home/andrii/project-name/.next/server/pages/_app.js:602:5)
    at __webpack_require__ (/home/andrii/project-name/.next/server/webpack-runtime.js:25:42)
    at Object../db/index.js (/home/andrii/project-name/.next/server/pages/_app.js:1059:65) {
  code: 'MODULE_NOT_FOUND'
```

### Paste all relevant code snippets here:

`db/schema.prisma`:
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "./client" // <- look at this parameter
}

// ... below are the database models
```

`db-X/schema.prisma`:
```
generator client {
  provider = "prisma-client-js"
  output   = "./client"
}

datasource db {
  provider = "mysql"
  url      = env("DB_X_DATABASE_URL")
}

// ... below are the database models
```

`db-X/index.js`:
```
import { enhancePrisma } from "blitz"
import { PrismaClient } from "./client"
const EnhancedPrisma = enhancePrisma(PrismaClient)
export * from "./client"
export default new EnhancedPrisma()
```

### What are detailed steps to reproduce this?

1. Create fresh blitzjs project from CLI using `Full` preset.
2. Create `db-one`, `db-two`, `db-three` directories.
3. Change `.prisma` and `index.js` files to be like provided above.
4. Run prisma commands provided above.
5. Run `yarn dev`.

### Run `blitz -v` and paste the output here:

```
Linux 5.4 | linux-x64 | Node: v14.17.5

blitz: 0.42.4 (global)
blitz: 0.42.4 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 19.73 GB / 25.02 GB
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.17.5 - ~/.config/nvm/14.17.5/bin/node
    Yarn: 1.22.11 - ~/.config/nvm/14.17.5/bin/yarn
    npm: 6.14.14 - ~/.config/nvm/14.17.5/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.4.2 => 3.4.2 
    blitz: 0.42.4 => 0.42.4 
    prisma: 3.4.2 => 3.4.2 
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    typescript: Not Found
```

**Comment by flybayer** [comment]
Hey @Andreychik32, I don't *think* there's a bug in Blitz causing this. Not sure what's happening, but I would suggest backing out all your changes until it starts working, then one by one make a change to see what breaks it. 

Then feel free to post more information here

**Comment by Andreychik32** [comment]
Isn't it caused by some kind of babel config issue? Or maybe my implementation of 4 clients is completely wrong? To use 4 prisma clients, I've specified `output   = "./client"` in `schema.prisma` files, which, after generation, results in this directory tree _(please note the `-L 2` flag in command to limit introspecting subdirectories)_:

```fish
andrii@wsl ~/project-name (master)> tree db/ db-one/ db-two/ db-three/
db/
├── client
│   ├── index-browser.js
│   ├── index.d.ts
│   ├── index.js
│   ├── libquery_engine-debian-openssl-1.1.x.so.node
│   ├── runtime
│   │   ├── esm
│   │   │   ├── index-browser.mjs
│   │   │   ├── index.mjs
│   │   │   └── proxy.mjs
│   │   ├── index-browser.d.ts
│   │   ├── index-browser.js
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── proxy.d.ts
│   │   └── proxy.js
│   └── schema.prisma
├── index.js
├── migrations
│   ├── 20211117171811_changes
│   │   └── migration.sql
│   └── migration_lock.toml
└── schema.prisma
db-one/
├── client
│   ├── index-browser.js
│   ├── index.d.ts
│   ├── index.js
│   ├── libquery_engine-debian-openssl-1.1.x.so.node
│   ├── runtime
│   │   ├── esm
│   │   │   ├── index-browser.mjs
│   │   │   ├── index.mjs
│   │   │   └── proxy.mjs
│   │   ├── index-browser.d.ts
│   │   ├── index-browser.js
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── proxy.d.ts
│   │   └── proxy.js
│   └── schema.prisma
├── index.js
└── schema.prisma
db-two/
├── client
│   ├── index-browser.js
│   ├── index.d.ts
│   ├── index.js
│   ├── libquery_engine-debian-openssl-1.1.x.so.node
│   ├── runtime
│   │   ├── esm
│   │   │   ├── index-browser.mjs
│   │   │   ├── index.mjs
│   │   │   └── proxy.mjs
│   │   ├── index-browser.d.ts
│   │   ├── index-browser.js
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── proxy.d.ts
│   │   └── proxy.js
│   └── schema.prisma
├── index.js
└── schema.prisma
db-three/
├── client
│   ├── index-browser.js
│   ├── index.d.ts
│   ├── index.js
│   ├── libquery_engine-debian-openssl-1.1.x.so.node
│   ├── runtime
│   │   ├── esm
│   │   │   ├── index-browser.mjs
│   │   │   ├── index.mjs
│   │   │   └── proxy.mjs
│   │   ├── index-browser.d.ts
│   │   ├── index-browser.js
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── proxy.d.ts
│   │   └── proxy.js
│   └── schema.prisma
├── index.js
└── schema.prisma

14 directories, 66 files
```

I assume, that in the `client` directories, there is some files, that require `os` and babel can't find it at runtime.
The good example of such file is `db/client/runtime/index.js`, where `os` is imported 16 times in my case.

**Comment by Andreychik32** [comment]
Also found this prisma issue: https://github.com/prisma/prisma/issues/10058

I've tried to run `yarn add prisma@3.5.0 @prisma/client@3.5.0` and regenerated all prisma clients.
After that, I've got this error:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/andrii/project-name/.env.local
info  - Loaded env from /home/andrii/project-name/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Using external babel configuration from /home/andrii/project-name/babel.config.js
[BABEL] Note: The code generator has deoptimised the styling of /home/andrii/project-name/db/client/runtime/index.js as it exceeds the max of 500KB.
error - ./db/client/runtime/index.js:27212:17
Module not found: Can't resolve '_http_common'
  27210 |   "../../node_modules/.pnpm/undici@3.3.6/node_modules/undici/lib/node/http-parser.js"(exports2, module2) {
  27211 |     "use strict";
> 27212 |     var common = require("_http_common");
        |                 ^
  27213 |     if (common.HTTPParser) {
  27214 |       module2.exports = common.HTTPParser;
  27215 |     } else {

Import trace for requested module:
./db/client/index.js
./db/index.js

https://nextjs.org/docs/messages/module-not-found
```

Now I've found this issue https://github.com/prisma/prisma/issues/6899#issuecomment-849126557 (also prisma) and added this snippet to `blitz.config.js`.

And now, I get this error:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/andrii/project-name/.env.local
info  - Loaded env from /home/andrii/project-name/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Using external babel configuration from /home/andrii/project-name/babel.config.js
[BABEL] Note: The code generator has deoptimised the styling of /home/andrii/project-name/db/client/runtime/index.js as it exceeds the max of 500KB.
event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
event - build page: /_error
wait  - compiling...
event - build page: /
TypeError: Cannot destructure property 'components' of 'object null' as it is null.
    at DevServer.renderToResponseWithComponents (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:975:90)
    at DevServer.renderErrorToResponse (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:1411:35)
    at async pipe.req.req (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:1372:30)
    at async DevServer.pipe (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:855:25)
event - compiled successfully
TypeError: Cannot destructure property 'components' of 'object null' as it is null.
    at DevServer.renderToResponseWithComponents (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:975:90)
    at DevServer.renderErrorToResponse (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:1411:35)
    at async DevServer.pipe (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:855:25)
    at async Object.fn (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:662:21)
    at async Router.execute (/home/andrii/project-name/node_modules/next/dist/server/router.js:206:32)
    at async DevServer.run (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:831:29)
    at async DevServer.handleRequest (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:295:20)
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/home/andrii/project-name/.next/cache/webpack/client-development/1.pack_' -> '/home/andrii/project-name/.next/cache/webpack/client-development/1.pack'
TypeError: Cannot destructure property 'components' of 'object null' as it is null.
    at DevServer.renderToResponseWithComponents (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:975:90)
    at DevServer.renderErrorToResponse (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:1411:35)
    at async DevServer.pipe (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:855:25)
    at async Object.fn (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:662:21)
    at async Router.execute (/home/andrii/project-name/node_modules/next/dist/server/router.js:206:32)
    at async DevServer.run (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:831:29)
    at async DevServer.handleRequest (/home/andrii/project-name/node_modules/next/dist/server/next-server.js:295:20)
```

And now I'm completely lost...

**Comment by Andreychik32** [comment]
I suppose that Babel should not bundle generated prisma client if it was generated inside the project directories.

**Comment by tuvshinbayar-coinhub** [comment]
> I suppose that Babel should not bundle generated prisma client if it was generated inside the project directories.

Did you manage to solve it?

I am using multiple databases so generated 3 clients for it and when I import the generated clients then run the code. It says
```
[BABEL] Note: The code generator has deoptimised the styling of /Users/giva/dev/coinhub/cgw-management/prisma/generated/ex_user/index.js as it exceeds the max of 500KB.
```
and API is very slow on the first call.

**Comment by giva9712** [comment]
> I suppose that Babel should not bundle generated prisma client if it was generated inside the project directories.

Did you manage to solve it?

I am using multiple databases so generated 3 clients for it and when I import the generated clients then run the code. It says
```
[BABEL] Note: The code generator has deoptimised the styling of /Users/giva/dev/coinhub/cgw-management/prisma/generated/ex_user/index.js as it exceeds the max of 500KB.
```
and API is very slow on the first call.

**Comment by andyjy** [comment]
Might help, potentially - how I worked through a bunch of the issues above to get multiple prisma schemas working in a npm workspaces monorepo with multiple packages and Next.JS: https://github.com/prisma/prisma/issues/9435#issuecomment-974576800

**Comment by flybayer** [comment]
@Andreychik32 sorry for delay here. I recommend generating the clients inside `node_modules`, but using custom names. For example `node_modules/.prisma1/`. That way it's excluded from babel processing.

**Comment by talesmgodois** [comment]
Hi guys, this is happening to me as well, I am trying to use prisma with serverless.

✖ TypeError: __assign is not a function
      at ../../node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (/home/tales/projects/bolico/bolico-auth-svc/.esbuild/.build/.build/dist/handlers/index.js:45011:29)                   
      at __require (/home/tales/projects/bolico/bolico-auth-svc/.esbuild/.build/.buil

this error happens when simple trying to instantiate prismaClient

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({});

export const prismaClient = prisma;
```

**Comment by flybayer** [comment]
Hey @talesmgodois, this doesn't _look_ like it has anything to do with Blitz. Can you check with Prisma support on this one?

**Comment by talesmgodois** [comment]
Hi @flybayer, alright, I just  saw  the same error happening so I though that might  be helpful.

Anyway I was able to "fix" by myself. The reason I quoted fiz is because i was using some serverless plugins that I didn't control where my built javascript should be. I removed  those, and generate only using tsc and worked like a charm.
