### ISSUE TITLE
Blitz builds failing on Vercel

### ISSUE THREAD

**Issue by Nfinished** [blitz-js/blitz#3064]
### What is the problem?

As posted here: https://github.com/vercel/vercel/discussions/7185, Vercel builds are failing with error `Build optimization failed: found pages without a React Component as default export`. I'd create an issue in Vercel/nextjs but as this is a Blitz project I'd definitely get bounced back here.

Builds complete locally, but during Vercel deployments the above error occurs. Below is one of the relevant pages in its entirety, it's definitely default exporting a React component. Could this be due to some Blitz-specific step of the build process?

### Paste all your error logs here:

(Vercel deployment logs)

```
> Build error occurred
--
12:31:24.978 | Error: Build optimization failed: found pages without a React Component as default export in
12:31:24.978 | pages/projects/[id]
12:31:24.978 | pages/projects
12:31:24.978 |  
12:31:24.978 | See https://nextjs.org/docs/messages/page-without-valid-component for more info.
12:31:24.980 |  
12:31:24.980 | at /vercel/path0/node_modules/next/dist/build/index.js:604:19
12:31:24.981 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
12:31:25.060 | error Command failed with exit code 1.
```

### Paste all relevant code snippets here:

```tsx
// app/pages/projects/index.tsx

import { BlitzPage, Head } from 'blitz'
import React, { Suspense } from 'react'

import AppLayout from 'app/core/layouts/AppLayout'
import ProjectTable from 'app/Projects/components/ProjectTable'

const ProjectsPage: BlitzPage = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
      </Head>

      <Suspense fallback={<div>Loading...</div>}>
        <ProjectTable />
      </Suspense>
    </>
  )
}

ProjectsPage.suppressFirstRenderFlicker = true
ProjectsPage.authenticate = true
ProjectsPage.getLayout = (page) => <AppLayout>{page}</AppLayout>

export default ProjectsPage

```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
Linux 5.10 | linux-x64 | Node: v16.9.0

blitz: 0.44.4 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 12.77 GB / 15.60 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.9.0 - /tmp/yarn--1639462279966-0.25328662260217283/node
    Yarn: 1.22.15 - /tmp/yarn--1639462279966-0.25328662260217283/yarn
    npm: 7.21.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.6.0 => 3.6.0 
    blitz: 0.44.4 => 0.44.4 
    prisma: 3.6.0 => 3.6.0 
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    typescript: ~4.5.4 => 4.5.4 
```

**Comment by Nfinished** [comment]
It appears to be a `useMutation` hook in a descendant causing the problem, Vercel won't build with this snippet.

```ts
const [createProjectMutation, { isLoading: isSubmitting }] = useMutation(
    createProject,
    {
      onSuccess: () => {
        onClose()
        invalidateQuery(getProjects)
      },
    }
  )
  ```

**Comment by blakeley** [comment]
@Nfinished How did you resolve the issue? Is there a resolution other than removing that snippet?

**Comment by Nfinished** [comment]
Turned out it was actually a project dependency that was doing something vercel didn't like. My issue was unrelated to blitz
