### ISSUE TITLE
Can't dockerise my app

### ISSUE THREAD

**Issue by romakoch** [blitz-js/blitz#3128]
### What is the problem?

There is an error after trying to dockerize my app, using the official tutorial

### Paste all your error logs here:

```
 > [builder 9/9] RUN yarn build:
#16 2.810 yarn run v1.22.17
#16 2.916 $ blitz build
#16 4.021 Loaded env from /app/.env.local
#16 4.022 Loaded env from /app/.env
#16 4.738 /app/node_modules/esbuild/lib/main.js:1209
#16 4.738         return callback(new Error(error), null);
#16 4.738                         ^
#16 4.738
#16 4.738 Error: The service was stopped
#16 4.738     at /app/node_modules/esbuild/lib/main.js:1209:25
#16 4.738     at /app/node_modules/esbuild/lib/main.js:606:9
#16 4.738     at Socket.afterClose (/app/node_modules/esbuild/lib/main.js:584:7)
#16 4.738     at Socket.emit (node:events:402:35)
#16 4.738     at endReadableNT (node:internal/streams/readable:1343:12)
#16 4.738     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#16 4.738
#16 4.738 Node.js v17.3.1
#16 4.760 error Command failed with exit code 1.
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by beerose** [comment]
Hi, could you try with Node version 16 or lower?

**Comment by Alfxjx** [comment]
same error using node v16 
successfully build in windows env
but failed in docker

```
/usr/src/app/node_modules/esbuild/esbuild.exe: 1: /usr/src/app/node_modules/esbuild/esbuild.exe: MZ����@���: not found
/usr/src/app/node_modules/esbuild/esbuild.exe: 1: /usr/src/app/node_modules/esbuild/esbuild.exe: Syntax error: end of file unexpected (expecting ")")
```

**Comment by Alfxjx** [comment]
[link-esbuild](https://esbuild.github.io/getting-started/#:~:text=However%2C%20people%20sometimes,your%20package%20manager%3A)

 this may help cause I copy the node_modules from outer to the docker
