### ISSUE TITLE
TypeError when running blitz dev

### ISSUE THREAD

**Issue by talcohen100** [blitz-js/blitz#3154]
### What is the problem?

Blitz has been working fine for some time, but today I ran my project and got this error message:

I tried re-installing Blitz, deleting node_modules and .blitz but nothing seems to help.. 

### Paste all your error logs here:

```
TypeError: Cannot use 'in' operator to search for 'props' in undefined
    at /Users/bila/WebstormProjects/booqsi/web/node_modules/babel-plugin-superjson-next/dist/tools.js:79:39
    at step (/Users/bila/WebstormProjects/booqsi/web/node_modules/babel-plugin-superjson-next/dist/tools.js:44:23)
    at Object.next (/Users/bila/WebstormProjects/booqsi/web/node_modules/babel-plugin-superjson-next/dist/tools.js:25:53)
    at fulfilled (/Users/bila/WebstormProjects/booqsi/web/node_modules/babel-plugin-superjson-next/dist/tools.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. blitz dev

### Run `blitz -v` and paste the output here:

```
macOS Monterey | darwin-x64 | Node: v16.0.0

blitz: 0.45.2 (global)
blitz: 0.38.4 (local)

  Package manager: yarn 
  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 943.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.26.0 => 2.26.0 
    blitz: 0.38.4 => 0.38.4 
    prisma: 2.30.2 => 2.30.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ~4.3 => 4.3.5 

```

**Comment by beerose** [comment]
I see that you're using an older Blitz version in your project (local). Could you try upgrading the latest?

**Comment by talcohen100** [comment]
@beerose  - tried that, and it looks like it's breaking other parts of the code, @blitz/core module cannot be found.

**Comment by beerose** [comment]
Hmm, we don't expose a `@blitz/core` module. Can you paste the logs?

**Comment by beerose** [comment]
Closing due to inactivity.
