### ISSUE TITLE
Getting this error on a new blitz toolkit app => Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by achaconm2001** [blitz-js/blitz#3354]
### What is the problem?

Hi. I just created a brand new Blitz application using the toolkit alpha (Blitz.js v2.0.0-alpha.22). I started the app with blitz dev and got this error.

![image](https://user-images.githubusercontent.com/28637127/167959519-683bcfca-1c79-4a7a-81c8-d6e59ee5fc19.png)
![image](https://user-images.githubusercontent.com/28637127/167959587-8dadf2cf-ac1c-42ab-876f-798f9e282f8c.png)
![image](https://user-images.githubusercontent.com/28637127/167959620-1305be00-3915-45c9-8408-0c54e9fdc38f.png)
![image](https://user-images.githubusercontent.com/28637127/167959680-870270b5-a123-4adc-b68e-50f9be05fcef.png)

Also at the server console:
![image](https://user-images.githubusercontent.com/28637127/167959734-0bffc8fa-26ef-4e6e-bace-078a8c16ce55.png)

I did some debugging and removing the UserInfo component, it works.

### Paste all your error logs here:

```
utils.js?e7ff:86 Image with src "/_next/static/media/logo.f0bc5c0b.png" was detected as the Largest Contentful Paint (LCP). Please add the "priority" property if this image is above the fold.
Read more: https://nextjs.org/docs/api-reference/next/image#priority
warnOnce @ utils.js?e7ff:86
:3000/api/rpc/getCurrentUser:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
next-dev.js?3515:25 Error: Internal Server Error
window.console.error @ next-dev.js?3515:25
useBaseQuery.js?d49a:90 Uncaught Error: Internal Server Error
next-dev.js?3515:25 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ErrorPage`.
    at ErrorComponent (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:203:1)
    at RootErrorFallback (webpack-internal:///./pages/_app.tsx:97:23)
    at ErrorBoundary (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:96:5)
    at MyApp (webpack-internal:///./pages/_app.tsx:129:27)
    at Hydrate (webpack-internal:///./node_modules/react-query/es/hydration/react.js:28:23)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at BlitzProvider (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:286:3)
    at BlitzOuterRoot (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:269:111)
    at WithSuperJSON (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:79:10)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:822:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:946:27)
window.console.error @ next-dev.js?3515:25
react-dom.development.js?ac89:28221 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ErrorPage`.
    at createFiberFromTypeAndProps (react-dom.development.js?ac89:28221:1)
    at createFiberFromElement (react-dom.development.js?ac89:28247:1)
    at createChild (react-dom.development.js?ac89:14933:1)
    at reconcileChildrenArray (react-dom.development.js?ac89:15237:1)
    at reconcileChildFibers (react-dom.development.js?ac89:15657:1)
    at reconcileChildren (react-dom.development.js?ac89:19909:1)
    at updateHostComponent$1 (react-dom.development.js?ac89:20658:1)
    at beginWork (react-dom.development.js?ac89:22373:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:4206:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4270:1)
    at beginWork$1 (react-dom.development.js?ac89:27243:1)
    at performUnitOfWork (react-dom.development.js?ac89:26392:1)
    at workLoopConcurrent (react-dom.development.js?ac89:26378:1)
    at renderRootConcurrent (react-dom.development.js?ac89:26340:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25577:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
useBaseQuery.js?d49a:90 Uncaught Error: Internal Server Error
next-dev.js?3515:25 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ErrorPage`.
    at ErrorComponent (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:203:1)
    at RootErrorFallback (webpack-internal:///./pages/_app.tsx:97:23)
    at ErrorBoundary (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:96:5)
    at MyApp (webpack-internal:///./pages/_app.tsx:129:27)
    at Hydrate (webpack-internal:///./node_modules/react-query/es/hydration/react.js:28:23)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at BlitzProvider (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:286:3)
    at BlitzOuterRoot (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:269:111)
    at WithSuperJSON (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:79:10)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:822:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:946:27)
window.console.error @ next-dev.js?3515:25
react-dom.development.js?ac89:28221 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ErrorPage`.
    at createFiberFromTypeAndProps (react-dom.development.js?ac89:28221:1)
    at createFiberFromElement (react-dom.development.js?ac89:28247:1)
    at createChild (react-dom.development.js?ac89:14933:1)
    at reconcileChildrenArray (react-dom.development.js?ac89:15237:1)
    at reconcileChildFibers (react-dom.development.js?ac89:15657:1)
    at reconcileChildren (react-dom.development.js?ac89:19909:1)
    at updateHostComponent$1 (react-dom.development.js?ac89:20658:1)
    at beginWork (react-dom.development.js?ac89:22373:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:4206:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4270:1)
    at beginWork$1 (react-dom.development.js?ac89:27243:1)
    at performUnitOfWork (react-dom.development.js?ac89:26392:1)
    at workLoopSync (react-dom.development.js?ac89:26303:1)
    at renderRootSync (react-dom.development.js?ac89:26271:1)
    at recoverFromConcurrentError (react-dom.development.js?ac89:25689:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25589:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
next-dev.js?3515:25 The above error occurred in the <div> component:

    at div
    at ErrorComponent (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:203:1)
    at RootErrorFallback (webpack-internal:///./pages/_app.tsx:97:23)
    at ErrorBoundary (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:96:5)
    at MyApp (webpack-internal:///./pages/_app.tsx:129:27)
    at Hydrate (webpack-internal:///./node_modules/react-query/es/hydration/react.js:28:23)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at BlitzProvider (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:286:3)
    at BlitzOuterRoot (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:269:111)
    at WithSuperJSON (webpack-internal:///./node_modules/@blitzjs/next/dist/chunks/index-browser.mjs:79:10)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:822:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:946:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. npm install -g blitz@alpha
2. blitz new appname
3. Select Typescript, Full, Final Form
4. cd appname
5. blitz dev

### Run `blitz -v` and paste the output here:

```
Blitz.js v2.0.0-alpha.22
```

**Comment by beerose** [comment]
Thanks for the report, @achaconm2001. We'll fix the templates — in the meantime, can you set `@types/react` version to `18.0.1`?

**Comment by achaconm2001** [comment]
Done, but the errors are the same. I also tried with next@12.1.6 and react@18.1.0 and also the same react dom version and the errors were the same.

**Comment by dillonraphael** [comment]
@achaconm2001 Can you try with Blitz.js v2.0.0-alpha.45

**Comment by achaconm2001** [comment]
This time it doesn't show NextJS error modal, but the error page.
![image](https://user-images.githubusercontent.com/28637127/176726977-18b45cdc-099c-470a-b154-6c7c2eb9e32d.png)
At both console, the error continues being the same.

I tried with the Blitz.js v2.0.0-alpha.45 and also the Blitz.js v2.0.0-alpha.46. With NextJS 12.1.6

**Comment by beerose** [comment]
Hey @achaconm2001,

I spent some time trying to reproduce this issue, and unfortunately couldn't. I have a few follow up questions/suggestions:

1. Is there an `[[...blitz]].ts` file in `<app root>/pages/api/rpc`?
2. What's your Node version?
3. Could you try the latest Blitz alpha **and** Next in version 12.2.0?

**Comment by authentiqdigital** [comment]
> Hey @achaconm2001,
> 
> I spent some time trying to reproduce this issue, and unfortunately couldn't. I have a few follow up questions/suggestions:
> 
> 1. Is there an `[[...blitz]].ts` file in `<app root>/pages/api/rpc`?
> 2. What's your Node version?
> 3. Could you try the latest Blitz alpha **and** Next in version 12.2.0?

Hi @beerose, thanks for looking into this.

We have the same issue, when we generate the app via `blitz new <project>` with the latest blitz version and Next 12.2.0. The `[[...blitz]].ts` is present in `<app root>/pages/api/rpc` too. We generated a JavaScript and a TypeScript version, both are not working.

```
Blitz version: 2.0.0-alpha.55 (local)
Windows 11 | win32-x64 | Node: v16.15.1
```

The error in the console:
```
[blitzSessionMiddleware] Starting handler...
Starting sessionMiddleware...
error - Error: No query or mutation resolvers found
    at Object.assert (C:\...\blitz2\node_modules\blitz\dist\index-browser.cjs:113:11)
    at handleRpcRequest (C:\...\blitz2\node_modules\@blitzjs\rpc\dist\index-server.cjs:122:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/api/rpc/[[...blitz]]'
}
```

Might be a Windows related issue? Happy to help if you have further questions.

**Comment by beerose** [comment]
Hey, I'm sorry for the inconvenience — I finally managed to reproduce it, and it is, in fact, only in Windows. I have a fix and tested it on Windows so a new release should be out later today :)

**Comment by authentiqdigital** [comment]
> Hey, I'm sorry for the inconvenience — I finally managed to reproduce it, and it is, in fact, only in Windows. I have a fix and tested it on Windows so a new release should be out later today :)

Works like a charm now, thanks @beerose 👍
