### ISSUE TITLE
Test fail in Blitz (pivotal) alpha due to SyntaxError or misisng TS-config for jest

### ISSUE THREAD

**Issue by kivi** [blitz-js/blitz#3413]
### What is the problem?

Two of two test fail with `yarn test`
I just installed a fresh Blitz app with `blitz new`

Copied lines from package.json for an overview of configured dependencies

```
  "dependencies": {
    "@blitzjs/auth": "latest",
    "@blitzjs/next": "alpha",
    "@blitzjs/rpc": "latest",
    "@prisma/client": "3.9.0",
    "blitz": "2.0.0-alpha.33",
    "next": "12.1.6",
    "prisma": "3.9.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "zod": "3.10.1",
    "final-form": "4.20.7",
    "react-final-form": "6.5.9"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "12.0.8",
    "@types/jest": "27.4.1",
    "@types/node": "17.0.16",
    "@types/preview-email": "2.0.1",
    "@types/react": "18.0.1",
    "eslint": "7.32.0",
    "husky": "7.0.4",
    "jest": "27.5.1",
    "lint-staged": "12.1.7",
    "prettier": "^2.5.1",
    "prettier-plugin-prisma": "3.8.0",
    "pretty-quick": "3.1.3",
    "preview-email": "3.0.5",
    "typescript": "^4.5.3"
  },
```` 

### Paste all your error logs here:

```
yarn test
yarn run v1.22.17
$ jest
 FAIL  app/auth/mutations/forgotPassword.test.ts
  ● Test suite failed to run

    SyntaxError: ...../blitzalpha/app/auth/mutations/forgotPassword.test.ts: Unexpected token, expected "," (13:46)

      11 | const generatedToken = "plain-token"
      12 | jest.mock("blitz", () => ({
    > 13 |   ...jest.requireActual<Record<string, unknown>>("blitz")!,
         |                                               ^
      14 |   generateToken: () => generatedToken,
      15 | }))
      16 | jest.mock("preview-email", () => jest.fn())

      at instantiate (node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
      at toParseError (node_modules/@babel/parser/src/parse-error.js:58:12)
      at Parser.raise (node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
      at Parser.unexpected (node_modules/@babel/parser/src/tokenizer/index.js:1781:16)
      at Parser.expect (node_modules/@babel/parser/src/parser/util.js:153:28)
      at Parser.parseObjectLike (node_modules/@babel/parser/src/parser/expression.js:1953:14)
      at Parser.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1152:21)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:684:23)
      at Parser.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:663:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:632:23)

 FAIL  app/auth/mutations/resetPassword.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    SyntaxError: ..../blitzalpha/app/auth/mutations/resetPassword.test.ts: Missing initializer in const declaration. (9:13)

       7 | })
       8 |
    >  9 | const mockCtx: any = {
         |              ^
      10 |   session: {
      11 |     $create: jest.fn,
      12 |   },

      at instantiate (node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
      at toParseError (node_modules/@babel/parser/src/parse-error.js:58:12)
      at Parser.raise (node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
      at Parser.parseVar (node_modules/@babel/parser/src/parser/statement.js:1240:16)
      at Parser.parseVarStatement (node_modules/@babel/parser/src/parser/statement.js:903:10)
      at Parser.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:391:21)
      at Parser.parseStatement (node_modules/@babel/parser/src/parser/statement.js:329:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/src/parser/statement.js:1082:25)
      at Parser.parseBlockBody (node_modules/@babel/parser/src/parser/statement.js:1058:10)
      at Parser.parseProgram (node_modules/@babel/parser/src/parser/statement.js:214:10)

Test Suites: 2 failed, 2 total```


### Paste all relevant code snippets here:

```
yarn --version
1.22.17

```


### What are detailed steps to reproduce this?

1. `blitz new`
2. `yarn test`


follwoing commands work fine

```
blitz dev
blitz build 
```

### Run `blitz -v` and paste the output here:

```
blitz -v
Loaded env from /home/vikas/code/blitzalpha/.env.local
Loaded env from /home/vikas/code/blitzalpha/.env
Blitz version: 2.0.0-alpha.33 (global)
Blitz version: 2.0.0-alpha.33 (local)
Linux 5.13 | linux-x64 | Node: v16.13.1

 Package manager: npm

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.26 GB / 23.25 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  npmPackages:
    @prisma/client: 3.9.0 => 3.9.0 
    blitz: 2.0.0-alpha.33 => 2.0.0-alpha.33 
    next: 12.1.6 => 12.1.6 
    prisma: 3.9.0 => 3.9.0 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript: ^4.5.3 => 4.7.3 
```


### Please include below any other applicable logs and screenshots that show your problem:

_No response_

**Comment by beerose** [comment]
Thanks for the report! We'll try to fix it soon.

**Comment by Zeko369** [comment]
On this topic, maybe default to vitest for toolkit generated projects?

**Comment by zubeir-Abubakar** [comment]
@beerose what about if your using typescript? i have similar error 
` Support for the experimental syntax 'jsx' isn't currently enabled (1:1)`
kindly can you tell me how to solve it ?
