### ISSUE TITLE
`blitz new` fails when creating minimal project

### ISSUE THREAD

**Issue by DmacMcgreg** [blitz-js/blitz#3534]
### What is the problem?

`blitz new <project name>` fails when creating minimal project. Everything works when creating a full project with auth and db.

### Paste all your error logs here:

```
➜  6_Code cd blitz-alpha-test 
➜  blitz-alpha-test git:(master) code .
➜  blitz-alpha-test git:(master) cd ..
➜  6_Code blitz new test-project           
✔ Pick which language you'd like to use for your new blitz project › TypeScript
✔ Pick which template you'd like to use for your new blitz project › minimal
✔ Install dependencies? › npm
Hang tight while we set up your new Blitz app!
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/d/Documents/6_Code/test-project/pages/api/rpc/blitzrpcroute.ts
    at EditionInterface.exports.copy (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as move] (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at AppGenerator.preCommit (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:782:13)
    at AppGenerator.run (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:386:16)
    at async newApp (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/dist/chunks/new.cjs:239:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

```

### Paste all relevant code snippets here:

```
blitz new projectname
```

### What are detailed steps to reproduce this?

1. Go to any folder
2. blitz new test-project
3. Typescript
4. yarn or npm
5. minimal
6. error

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.53 (global)
macOS Monterey | darwin-x64 | Node: v16.13.0


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 32.18 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by beerose** [comment]
Thanks for the report! We'll look into it soon
