### ISSUE TITLE
Error type in publicData

### ISSUE THREAD

**Issue by karimsx** [blitz-js/blitz#3549]
### What is the problem?

![image](https://user-images.githubusercontent.com/71076673/179405868-e6b333ea-7020-4230-8e25-b078d86d5b21.png)

### Paste all your error logs here:

```
./app/auth/mutations/login.ts:29:48
Type error: Argument of type '{ userId: number; role: Role; }' is not assignable to parameter of type '{ userId: unknown; }'.
  Object literal may only specify known properties, and 'role' does not exist in type '{ userId: unknown; }'.

  27 |   const user = await authenticateUser(email, password)
  28 | 
> 29 |   await ctx.session.$create({ userId: user.id, role: user.role as Role })
     |                                                ^
  30 | 
  31 |   return user
  32 | })

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/karim/Projects/lustypics/web/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/home/karim/Projects/lustypics/web/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ~/Projects/lustypics/web    main !4                     
```

### Paste all relevant code snippets here:

```
import { SecurePassword } from "@blitzjs/auth"
import { resolver } from "@blitzjs/rpc"
import { AuthenticationError } from "blitz"
import db from "db"
import { Role } from "types"
import { Login } from "../validations"

export const authenticateUser = async (rawEmail: string, rawPassword: string) => {
  const { email, password } = Login.parse({ email: rawEmail, password: rawPassword })
  const user = await db.user.findFirst({ where: { email } })
  if (!user) throw new AuthenticationError()

  const result = await SecurePassword.verify(user.hashedPassword, password)

  if (result === SecurePassword.VALID_NEEDS_REHASH) {
    // Upgrade hashed password with a more secure hash
    const improvedHash = await SecurePassword.hash(password)
    await db.user.update({ where: { id: user.id }, data: { hashedPassword: improvedHash } })
  }

  const { hashedPassword, ...rest } = user
  return rest
}

export default resolver.pipe(resolver.zod(Login), async ({ email, password }, ctx) => {
  // This throws an error if credentials are invalid
  const user = await authenticateUser(email, password)

  await ctx.session.$create({ userId: user.id, role: user.role as Role })

  return user
})

```

### What are detailed steps to reproduce this?

1. blitz new
2. yarn run build

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.53 (local)
Linux 5.15 | linux-x64 | Node: v17.7.1


 Package manager: npm

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 10.95 GB / 15.62 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.7.1 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.5.4 - /usr/bin/npm
  npmPackages:
    @prisma/client: 3.9.0 => 3.9.0 
    blitz: 2.0.0-alpha.53 => 2.0.0-alpha.53 
    next: 12.2.0 => 12.2.0 
    prisma: 4.0.0 => 4.0.0 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript: 4.7.4 => 4.7.4 

```

**Comment by Zeko369** [comment]
Could you actually check which package versions you have (also we need to improve our CLI to print all the packages #3552)?

If you're on `alpha` for all the packages auth gets resolved to `2.0.0-alpha.52` while others are on `53` which causes bugs in how TS overrides stuff.

So just pin all packages to `2.0.0-alpha.54` and it should work

**Comment by karimsx** [comment]
updated all versions to alpha 55, working like a charm

**Comment by beerose** [comment]
Thanks for the update @karimsx! I'm closing the issue then
