### ISSUE TITLE
alpha install fails from workspace dir @alpha.54

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#3558]
### What is the problem?

i installed a fresh alpha app and received the error mentioned in the paste log section when i try to `blitz dev`

### Paste all your error logs here:

```
John Vandivier@DESKTOP-MMSRKCH MINGW64 /d/workspace/github
$ blitz dev
Error: Cannot find module 'next'
Require stack:
- D:\workspace\github\noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at resolveFileName (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\resolve-from\index.js:46:47)
    at module.exports (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\resolve-cwd\index.js:4:30)
    at resolveBinAsync (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\chunks\index.cjs:104:44)
    at getCommandBin (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\chunks\index.cjs:143:21)
    at Object.normalize (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\chunks\index.cjs:139:20)
    at async Module.dev (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\chunks\next-commands.cjs:242:35)
    at async dev (C:\Users\John Vandivier\AppData\Local\Yarn\Data\global\node_modules\blitz\dist\chunks\dev.cjs:26:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\workspace\\github\\noop.js' ]
}
```

### Paste all relevant code snippets here:

n/a

### What are detailed steps to reproduce this?

1. on windows, using git bash, globally install blitz at alpha via yarn (Note: `blitz -v` mentions npm package mgr but I did not used npm and neither did I select npm during `blitz new` prompt flow)
2. have a workspace folder with many github projects
3. in the workspace folder, not the project repo folder, run `blitz new kahneman`
4. content is correctly populated within project repo folder, but when I `blitz dev` in the folder, it looks for a noop.js file in the workspace dir and doesn't find it

### Run `blitz -v` and paste the output here:

```
John Vandivier@DESKTOP-MMSRKCH MINGW64 /d/workspace/github
$ blitz --version
Blitz version: 2.0.0-alpha.54 (global)
Windows 10 | win32-x64 | Node: v16.2.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 10.56 GB / 19.86 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by Vandivier** [comment]
wow now i feel dumb plz give me a few hours to check smth - I'm not sure I ever did `cd kahneman` after `blitz new kahneman`...

**Comment by Vandivier** [comment]
what I've done since:
1. rm -rf /d/workspace/github/kahneman
2. re-clone kahneman folder and cd into it, blitz new, blitz dev; UI is successfully spun up this time BUT
3. `getCurrentUser` fails out of the box resulting in the default view being a 500 page instead of the blitz app default homepage

UI err details:
```
The above error occurred in the <UserInfo> component:
at UserInfo (webpack-internal:///./pages/index.tsx:43:100)
    at Suspense
    at div
    at main
    at div
    at Layout (webpack-internal:///./app/core/layouts/Layout.tsx:13:23)
    at Home
    at AuthRoot
...
```

server side err logs/details:
```
event - compiled successfully in 161 ms (117 modules)
[blitzSessionMiddleware] Starting handler...
Starting sessionMiddleware...
error - Error: No query or mutation resolvers found
    at Object.assert (D:\workspace\github\kahneman\kahneman\node_modules\blitz\dist\index-browser.cjs:113:11)
    at handleRpcRequest (D:\workspace\github\kahneman\kahneman\node_modules\@blitzjs\rpc\dist\index-server.cjs:122:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/api/rpc/[[...blitz]]'
}
```

I tried `blitz prisma migrate dev` which worked but didn't seem to fix the issue.

nit, semirelated: `UserInfo` is defined inside of index.tsx, are yall open to me moving it to app/users/components?

**Comment by Vandivier** [comment]
seems related to latest comment: https://github.com/blitz-js/blitz/issues/3478

**Comment by Vandivier** [comment]
updated version info after install success (w typescript)
```
John Vandivier@DESKTOP-MMSRKCH MINGW64 /d/workspace/github/kahneman/kahneman (master)
$ blitz --version
Loaded env from D:\workspace\github\kahneman\kahneman\.env.local
Loaded env from D:\workspace\github\kahneman\kahneman\.env
Blitz version: 2.0.0-alpha.54 (global)
Blitz version: 2.0.0-alpha.54 (local)
Windows 10 | win32-x64 | Node: v16.2.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 10.92 GB / 19.86 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @prisma/client: 3.9.0 => 3.9.0
    blitz: 2.0.0-alpha.54 => 2.0.0-alpha.54
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

**Comment by Vandivier** [comment]
this might be obv to someone more familiar w the code, but the root cause of the error is that `const resolverMap = await getResolverMap();` is undefined inside of `function rpcHandler(config)` in the module @blitzjs/rpc

maybe later I'll investigate why that is the case, but atm that's as far as I've gone.

also, closing issue bc I was able to `blitz dev` in the top folder. again i think originally I didn't `cd kahneman`

**Comment by Vandivier** [comment]
![image](https://user-images.githubusercontent.com/5559355/179436285-fe78a5b3-bdcb-4ac1-a0b9-ec0737dde9ed.png)

everything is basically in its default + unset state

getResolverMap() -> loadBlitzRpcResolverFilesWithInternalMechanism() ->g.blitzRpcResolverFilesLoaded

not sure how that's supposed to get populated but it seems like it's just...not being populated
