### ISSUE TITLE
pnpm: Brand new app fails with Error: No QueryClient set

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3579]
1. Generate a brand new app with `2.0.0-alpha.56` 
   - have to use `blitz new testblitz --skip-upgrade` flag because of https://github.com/blitz-js/blitz/issues/3566
   - select pnpm
2. Run `blitz build`

Get failed build with this:

```
Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (/private/tmp/testblitz/node_modules/.pnpm/react-query@3.39.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/react-query/lib/react/QueryClientProvider.js:36:11)
    at useBaseQuery (/private/tmp/testblitz/node_modules/.pnpm/react-query@3.39.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/react-query/lib/react/useBaseQuery.js:24:61)
    at Object.useQuery (/private/tmp/testblitz/node_modules/.pnpm/react-query@3.39.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/react-query/lib/react/useQuery.js:14:41)
    at useQuery (/private/tmp/testblitz/node_modules/.pnpm/@blitzjs+rpc@2.0.0-alpha.56_mwbxcnklvkvmbhor4xlfqgl32e/node_modules/@blitzjs/rpc/dist/index-browser.cjs:29:45)
    at useCurrentUser (/private/tmp/testblitz/.next/server/pages/index.js:64:37)
    at UserInfo (/private/tmp/testblitz/.next/server/pages/index.js:97:25)
    at Hc (/private/tmp/testblitz/node_modules/.pnpm/react-dom@18.0.0_react@18.0.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
    at Kc (/private/tmp/testblitz/node_modules/.pnpm/react-dom@18.0.0_react@18.0.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
    at Z (/private/tmp/testblitz/node_modules/.pnpm/react-dom@18.0.0_react@18.0.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Lc (/private/tmp/testblitz/node_modules/.pnpm/react-dom@18.0.0_react@18.0.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
info  - Generating static pages (6/6)

> Build error occurred
Error: Export encountered errors on following paths:
	/auth/forgot-password
	/auth/login
	/auth/signup
```

## Workaround

```
pnpm i react-query@3.39.0
```

## Debug Info

```
/t/testblitz> pnpm why react-query
Legend: production dependency, optional only, dev only

testblitz@1.0.0 /private/tmp/testblitz

dependencies:
@blitzjs/next 2.0.0-alpha.56
├─┬ @blitzjs/rpc 2.0.0-alpha.56
│ └── react-query 3.39.0
└── react-query 3.39.0
@blitzjs/rpc 2.0.0-alpha.56
└── react-query 3.39.0
```

This *might* be because there are 3 different versions of react-query in the node_modules. I had an issue related to this earlier on with toolkit dev. Me may need to export RQ stuff from blitzjs/rpc?

But that wouldn't really explain why adding RQ to the app directly fixes it.

**Comment by Zeko369** [comment]
@flybayer could you try this adding this to the `.npmrc`, if so I'll PR it to the template / codemod

```
public-hoist-pattern[]=react-query
```

**Comment by jmcelreavey** [comment]
This still seems to be an issue for me, I can confirm that it is hoisting the file and `pnpm config list` states this but I still receive the error 🤔

**Comment by jmcelreavey** [comment]
Just to add to this, it actually works fine on the root of the site but on my additional pages it doesn't..

**Comment by Zeko369** [comment]
@jmcelreavey which version? if you upgraded to lates it's moved to `@tanstack/react-query` from `react-query` so you'll need to change it to `@tanstack/react-query`

I tried doing `blitz new my-app` and then `pnpm build` and it worked
