### ISSUE TITLE
Env variable not working with Typescript?

### ISSUE THREAD

**Issue by sherryxiao1988** [blitz-js/blitz#3612]
### What is the problem?

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1202426/181122466-8307bf36-5797-4976-af52-dd6c48f0d436.png">

It works if I replace these env variables with strings directly

### Paste all your error logs here:

```
error - TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/xiaoshundan/workspace/tokenpass/node_modules/passport-oauth2/lib/strategy.js:87:34)
    at new Strategy (/Users/xiaoshundan/workspace/tokenpass/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at eval (webpack-internal:///(api)/./pages/api/auth/[...auth].ts:23:23)
    at Object.(api)/./pages/api/auth/[...auth].ts (/Users/xiaoshundan/workspace/tokenpass/.next/server/pages/api/auth/[...auth].js:281:1)
    at __webpack_require__ (/Users/xiaoshundan/workspace/tokenpass/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (/Users/xiaoshundan/workspace/tokenpass/.next/server/pages/api/auth/[...auth].js:313:39)
    at /Users/xiaoshundan/workspace/tokenpass/.next/server/pages/api/auth/[...auth].js:314:28
    at Object.<anonymous> (/Users/xiaoshundan/workspace/tokenpass/.next/server/pages/api/auth/[...auth].js:317:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

### Paste all relevant code snippets here:

```
    strategies: [
      {
        authenticateOptions: { scope: "openid profile email" },
        strategy: new GoogleStrategy(
          {
            clientID: process.env.GOOGLE_CLIENT_ID || "",
            clientSecret: process.env.GOOGLE_CLIENT_SECRET || "",
            callbackURL: "http://localhost:3000/api/auth/google/callback",
          },
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env.local
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env
Blitz version: 2.0.0-alpha.58 (global)
Blitz version: 2.0.0-alpha.58 (local)
macOS Monterey | darwin-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.17 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-alpha.58 => 2.0.0-alpha.58
    @blitzjs/next: 2.0.0-alpha.58 => 2.0.0-alpha.58
    @blitzjs/rpc: 2.0.0-alpha.58 => 2.0.0-alpha.58
    @prisma/client: 4.1.0 => 4.1.0
    blitz: 2.0.0-alpha.58 => 2.0.0-alpha.58
    next: 12.2.0 => 12.2.0
    prisma: 4.1.0 => 4.1.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

**Comment by beerose** [comment]
How do you start your app? I just tested it with a sample app in Blitz repo and it seems to work. Do you see logs that your env files were loaded when starting the app?

**Comment by sherryxiao1988** [comment]
I started it using `blitz dev`. Log says the env are loaded:
```
xiaoshundan-macbookpro2:tokenpass xiaoshundan$ blitz dev
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env.local
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env
```

It worked with pure javasript but wasn't working with Typescript somehow for me.

**Comment by sherryxiao1988** [comment]
Closing since apparently this was due to my files aren't saved somehow lol

**Comment by beerose** [comment]
I'm glad it's solved!
