### ISSUE TITLE
@blitzjs/rpc should not have zod as a dependency

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3649]
### What is the problem?

`@blitzjs/rpc` has `zod` as a dependency, causing the app build to fail if the user tries to use a different zod version

### Paste all your error logs here:

```
/t/testblitz> blitz build
Loaded env from /private/tmp/testblitz/.env.local
Loaded env from /private/tmp/testblitz/.env
info  - Linting and checking validity of types ..Failed to compile.

./app/auth/mutations/changePassword.ts:9:16
Type error: Argument of type 'ZodObject<{ currentPassword: ZodString; newPassword: ZodEffects<ZodString, string, string>; }, "strip", ZodTypeAny, { currentPassword: string; newPassword: string; }, { ...; }>' is not assignable to parameter of type 'ZodTypeAny'.
  Types of property '_getOrReturnCtx' are incompatible.
    Type '(input: Zod.ParseInput, ctx?: Zod.ParseContext | undefined) => Zod.ParseContext' is not assignable to type '(input: import("/private/tmp/testblitz/node_modules/.pnpm/zod@3.17.3/node_modules/zod/lib/helpers/parseUtil").ParseInput, ctx?: import("/private/tmp/testblitz/node_modules/.pnpm/zod@3.17.3/node_modules/zod/lib/helpers/parseUtil").ParseContext | undefined) => import("/private/tmp/testblitz/node_modules/.pnpm/zod@3.17...'.

   7 |
   8 | export default resolver.pipe(
>  9 |   resolver.zod(ChangePassword),
     |                ^
  10 |   resolver.authorize(),
  11 |   async ({ currentPassword, newPassword }, ctx) => {
  12 |     const user = await db.user.findFirst({ where: { id: ctx.session.userId as number } })

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/private/tmp/testblitz/node_modules/.pnpm/next@12.2.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/private/tmp/testblitz/node_modules/.pnpm/next@12.2.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
info  - Linting and checking validity of types .⏎
```

### What are detailed steps to reproduce this?

1. Generate new blitz app
2. Upgrade zod to latest version
3. Run `blitz build`

### Run `blitz -v` and paste the output here:

```
Loaded env from /private/tmp/testblitz/.env.local
Loaded env from /private/tmp/testblitz/.env
Blitz version: 2.0.0-alpha.64 (global)
Blitz version: 2.0.0-alpha.64 (local)
macOS Monterey | darwin-arm64 | Node: v16.14.2


 Package manager: pnpm

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.26 GB / 64.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.14.2 - /var/folders/gf/xyzbs8n52kz_sxxvpw2psh1r0000gn/T/fnm_multishells/71365_1659370519007/bin/node
    Yarn: 1.22.1 - /opt/homebrew/bin/yarn
    npm: 8.1.4 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: alpha => 2.0.0-alpha.64
    @blitzjs/next: alpha => 2.0.0-alpha.64
    @blitzjs/rpc: alpha => 2.0.0-alpha.64
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-alpha.64 => 2.0.0-alpha.64
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

**Comment by chaiwattsw** [comment]
So I can simply delete this line to fix this right?
https://github.com/blitz-js/blitz/blob/890b0c0c9ded4c4a464bda2c09b1ff0085f79b2e/packages/blitz-rpc/package.json#L30

**Comment by flybayer** [comment]
@chaiwattsw move that to `devDependencies`, and I think you'll need to add zod to this externals array: https://github.com/blitz-js/blitz/blob/main/packages/blitz-rpc/build.config.ts#L11-L17

**Comment by chaiwattsw** [comment]
> @chaiwattsw move that to `devDependencies`, and I think you'll need to add zod to this externals array: https://github.com/blitz-js/blitz/blob/main/packages/blitz-rpc/build.config.ts#L11-L17

I got it, Thanks!
