### ISSUE TITLE
error when blitz prisma migrate dev

### ISSUE THREAD

**Issue by cesarve78** [blitz-js/blitz#3864]
### What is the problem?

In a fresh project.

I changed prisma.schema

and run: 

```
blitz prisma migrate dev
```

but it throw an error

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
$ blitz prisma migrate dev
/Users/cesar/.config/yarn/global/node_modules/blitz/dist/chunks/index.cjs:60
          parsed[key] = result.parsed?.[key];
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/cesar/.config/yarn/global/node_modules/blitz/dist/index.cjs:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

### What are detailed steps to reproduce this?

1. create a fresh project
2. change the DATABASE_URL to postgress (my case supabase)
3. change the database provider in prisma.schema
4. change the model
5. run blitz prisma migrate dev

### Run `blitz -v` and paste the output here:

same error
```
/Users/cesar/.config/yarn/global/node_modules/blitz/dist/chunks/index.cjs:60
          parsed[key] = result.parsed?.[key];
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/cesar/.config/yarn/global/node_modules/blitz/dist/index.cjs:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by cesarve78** [comment]
I update to node 16 and now is working.
