### ISSUE TITLE
reset-password page doesn't work when using React-Hook-Form library

### ISSUE THREAD

**Issue by benwhut** [blitz-js/blitz#3897]
### What is the problem?

The reset-password page doesn't work when using "React-Hook-Form" library setup in a new Blitz project

This error is similar to the one found [here](https://github.com/blitz-js/legacy-framework/issues/353), but I get this using [Blitz v2.0.0-beta.11](https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.11).

When opening the link to reset-password?token=... it is not possible to submit the form. There is no error message in the browser's console or in the executing terminal. When commenting the form's schema with `//schema={ResetPassword}` in `app\auth\pages\reset-password.tsx`, the form submits, but throws the error:
```
15:00:36.898 INFO  resetPassword() Starting with input: 
{
  password: '[***]',
  passwordConfirmation: '[***]',
  token: undefined
}
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "token"
    ],
    "message": "Required"
  }
]
```

### Paste all your error logs here:

```
15:00:36.898 INFO  resetPassword() Starting with input: 
{
  password: '[***]',
  passwordConfirmation: '[***]',
  token: undefined
}
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "token"
    ],
    "message": "Required"
  }
]
    at handleResult (file:///Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/zod/lib/index.mjs:449:23)
    at ZodEffects.safeParseAsync (file:///Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/zod/lib/index.mjs:586:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ZodEffects.parseAsync (file:///Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/zod/lib/index.mjs:564:24)
    at async /Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/@blitzjs/rpc/dist/index-server.cjs:29:20
    at async handleRpcRequest (/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/@blitzjs/rpc/dist/index-server.cjs:172:24)
    at async Object.handleRequestWithMiddleware (/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/blitz/dist/index-server.cjs:40:5)
    at async eval (webpack-internal:///(api)/./node_modules/@blitzjs/next/dist/index-server.cjs:82:14)
    at async Object.apiResolver (/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/next/dist/server/api-utils/node.js:184:9)
    at async DevServer.runApi (/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/next/dist/server/next-server.js:403:9) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  name: 'ZodError',
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}
15:00:36.901 ERROR resetPassword() 
 ZodError  [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "token"
    ],
    "message": "Required"
  }
]
details:
{
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [
        'token'
      ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)]
}
error stack:
• index.mjs:449 handleResult
    file:/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/zod/lib/index.mjs:449:23

• index.mjs:586 safeParseAsync
    file:/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/zod/lib/index.mjs:586:16

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

• index.mjs:564 parseAsync
    file:/Users/boltdozer/Web/takedownscout2/blitz-test3/node_modules/zod/lib/index.mjs:564:24

• index-server.cjs:29 <anonymous>
    node_modules/@blitzjs/rpc/dist/index-server.cjs:29:20

• index-server.cjs:172 handleRpcRequest
    node_modules/@blitzjs/rpc/dist/index-server.cjs:172:24

• index-server.cjs:40 handleRequestWithMiddleware
    node_modules/blitz/dist/index-server.cjs:40:5

• node.ts:269 apiResolver
    node_modules/next/server/api-utils/node.ts:269:5

• next-server.ts:612 runApi
    node_modules/next/server/next-server.ts:612:5
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. blitz new app
**- select "React Hook Form" as the form library (IMPORTANT)**
2. run blitz, create an account and logout
3. go to forget-password and insert email, then click on the generated reset-password link
4. insert new password and confirm password, submit -> nothing happens
5. comment schema={ResetPassword} in app\auth\pages\reset-password.tsx -> submitting works, but throws error invalid_type 

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.11 (global)
Blitz version: 2.0.0-beta.11 (local)
macOS Ventura | darwin-arm64 | Node: v16.17.1


 Package manager: npm

  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 463.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.11 => 2.0.0-beta.11 
    @blitzjs/next: 2.0.0-beta.11 => 2.0.0-beta.11 
    @blitzjs/rpc: 2.0.0-beta.11 => 2.0.0-beta.11 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.11 => 2.0.0-beta.11 
    next: 12.2.5 => 12.2.5 
    prisma: 4.0.0 => 4.0.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.8.4 
```

**Comment by dillonraphael** [comment]
Oh interesting. Looks like the react hook form templates aren't appeasing the zod validation.

**Comment by beerose** [comment]
> Oh interesting. Looks like the react hook form templates aren't appeasing the zod validation.

No, that's not it. The `useRouter` returns undefined on the initial load. Hence the token goes as `undefined` to the mutation and validation fails.

**Comment by beerose** [comment]
Previously we were using `useRouterQuery`, so we didn't have this issue.
