### ISSUE TITLE
Blitz install graphql-apollo-server is not working 

### ISSUE THREAD

**Issue by WaysToGo** [blitz-js/blitz#3904]
### What is the problem?

Blitz install graphql-apollo-server is not working 

### Paste all your error logs here:

```
blitz install graphql-apollo-server
Loaded env from .env.local
Loaded env from .env
Error generating api/graphql.ts

+––––––––––––––––––––––+
⎪   Add dependencies   ⎪
+––––––––––––––––––––––+
Add dependencies for defining and handling a GraphQL endpoint.

Hang tight! Installing dependencies...

Dependencies to be installed:
   📦 apollo-server-micro@3.x
   📦 graphql@15.x
   📦 nexus@1.x
   📦 nexus-prisma@0.34.x

node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: app/graphql/api/graphql.ts
    at EditionInterface.exports.copy (node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as move] (node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at TempGenerator.write (node_modules/@blitzjs/generator/dist/index.cjs:441:19)
    at async TempGenerator.run (node_modules/@blitzjs/generator/dist/index.cjs:478:5)
    at async createNewFiles (node_modules/blitz/dist/installer.cjs:489:25) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.7.0
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.blitz install graphql-apollo-server

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.12 (global)
Blitz version: 2.0.0-beta.12 (local)
macOS Monterey | darwin-arm64 | Node: v18.7.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 212.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.12 => 2.0.0-beta.12 
    @blitzjs/next: 2.0.0-beta.12 => 2.0.0-beta.12 
    @blitzjs/rpc: 2.0.0-beta.12 => 2.0.0-beta.12 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.12 => 2.0.0-beta.12 
    next: 12.2.5 => 12.2.5 
    prisma: 4.0.0 => 4.0.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.8.4 

```

**Comment by dillonraphael** [comment]
There are some issues with blitz install currently. Sorry about that. Working on fixes.

**Comment by beerose** [comment]
Should be fixed by https://github.com/blitz-js/blitz/pull/3909
