### ISSUE TITLE
Vercel OG (Edge Function) fails in Blitz app

### ISSUE THREAD

**Issue by jasperhartong** [blitz-js/blitz#3917]
### What is the problem?

The serverless functions for the newly introduced [Vercel OG Image api](https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images) fail in a Blitz project with an internal 500 error.

Removing the wrappers on `_app`, and `next.config.js` fixes the issue (but removes most Blitz functionality).

### Paste all your error logs here:

```
[GET] /api/og
10:35:43:31
2022-10-19T08:35:43.987Z	07ecfd4c-572b-43ca-b0ae-64c8af4dd017	ERROR	Unhandled error during request: ReferenceError: self is not defined
    at Object.<anonymous> (/var/task/.next/serverless/pages/api/og.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /api/og (/var/task/___next_launcher.cjs:26:38)
    at Server.page (/var/task/___next_launcher.cjs:95:31)
    at Server.emit (node:events:527:28)
2022-10-19T08:35:43.987Z	07ecfd4c-572b-43ca-b0ae-64c8af4dd017	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"self is not defined","stack":["ReferenceError: self is not defined","    at Object.<anonymous> (/var/task/.next/serverless/pages/api/og.js:1:1)","    at Module._compile (node:internal/modules/cjs/loader:1105:14)","    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)","    at Module.load (node:internal/modules/cjs/loader:981:32)","    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","    at Module.require (node:internal/modules/cjs/loader:1005:19)","    at require (node:internal/modules/cjs/helpers:102:18)","    at /api/og (/var/task/___next_launcher.cjs:26:38)","    at Server.page (/var/task/___next_launcher.cjs:95:31)","    at Server.emit (node:events:527:28)"]}
Unknown application error occurred
```

### Paste all relevant code snippets here:

```
// api/og.tsx
import { ImageResponse } from "@vercel/og"

export const config = {
  runtime: "experimental-edge",
}

export default function () {
  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          fontSize: 128,
          background: "white",
          width: "100%",
          height: "100%",
        }}
      >
        Hello, World!
      </div>
    )
  )
}

```

### What are detailed steps to reproduce this?

1. Create new Blitz app
2. `yarn add @vercel/og`
3. Create the `/pages/api/og.tsx` above
4. Deploy to Vercel
5. Visit <deploy>/api/og

I've created a Blitz app as reproduction:

- repo: https://github.com/jasperhartong/blitz-vercel-og-issue
- failing URL: https://blitz-vercel-og-issue.vercel.app/api/og

Also see the working branch (with Blitz wrappers removed):

- PR: https://github.com/jasperhartong/blitz-vercel-og-issue/pull/2
- successful URL: https://blitz-vercel-og-issue-git-no-blitz-works-jasperhartongprivate.vercel.app/api/og

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.13 (global)
Blitz version: 2.0.0-beta.13 (local)
macOS Monterey | darwin-x64 | Node: v16.17.1


 Package manager: npm

  System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 7.03 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.13 => 2.0.0-beta.13 
    @blitzjs/next: 2.0.0-beta.13 => 2.0.0-beta.13 
    @blitzjs/rpc: 2.0.0-beta.13 => 2.0.0-beta.13 
    @prisma/client: Not Found
    blitz: 2.0.0-beta.13 => 2.0.0-beta.13 
    next: 12.2.5 => 12.2.5 
    prisma: Not Found
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.8.4 
```

### Please include below any other applicable logs and screenshots that show your problem:

Working endpoint image:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/47074382/196654346-46d49bf2-f035-496a-a0fe-e26711373851.png">

**Comment by beerose** [comment]
Thanks for reporting! We'll take a look and fix it soon.
