### ISSUE TITLE
Eslint cannot find blitz config

### ISSUE THREAD

**Issue by Nfinished** [blitz-js/blitz#3935]
### What is the problem?

After running the codemod using beta 14, Eslint throws errors because it cannot find blitz config.

### Paste all your error logs here:

```
[Error - 8:12:34 PM] ESLint stack trace:
[Error - 8:12:34 PM] Error: Failed to load config "blitz" to extend from.
Referenced from: /Users/atrager/Nfinished/timerboard/.eslintrc.js
    at configInvalidError (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/atrager/Nfinished/timerboard/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)
```

### Paste all relevant code snippets here:

```js
// .eslint.js
module.exports = {
  extends: ['blitz', 'plugin:prettier/recommended'],
  plugins: ['simple-import-sort'],
  rules: {
    'simple-import-sort/imports': [
      'error',
      {
        groups: [
          // Side effect imports.
          ['^\\u0000'],
          // Packages.
          // Things that start with a letter (or digit or underscore), or `@` followed by a letter.
          ['^@?(?!app|public)\\w'],
          // Absolute imports and other imports such as Vue-style `@/foo`.
          // Anything that does not start with a dot.
          ['^[^.]'],
          // Relative imports.
          // Anything that starts with a dot.
          ['^\\.'],
          // Style imports.
          ['^.+\\.s?css$'],
        ],
      },
    ],
    'no-console': 'warn',
  },
}
```

### What are detailed steps to reproduce this?

Couldn't say, my codemod reported successful completion and there's nothing outstanding about my tooling setup.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.14 (local)
macOS Monterey | darwin-x64 | Node: v16.14.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 135.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /var/folders/34/c8tk0fm52hz6z0288x5npsp80000gp/T/yarn--1667261914547-0.13543467715719149/node
    Yarn: 1.22.19 - /var/folders/34/c8tk0fm52hz6z0288x5npsp80000gp/T/yarn--1667261914547-0.13543467715719149/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.14 => 2.0.0-beta.14 
    @blitzjs/next: 2.0.0-beta.14 => 2.0.0-beta.14 
    @blitzjs/rpc: 2.0.0-beta.14 => 2.0.0-beta.14 
    @prisma/client: ^3.14.0 => 3.14.0 
    blitz: 2.0.0-beta.14 => 2.0.0-beta.14 
    next: 12.2.0 => 12.2.0 
    prisma: ^3.14.0 => 3.14.0 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ~4.7.2 => 4.7.2 
```

**Comment by dillonraphael** [comment]
Seems you found a few codemod errors. Odd, not sure if we had this before. Like the other issues, I'll take a look.
