### ISSUE TITLE
Support Next 13

### ISSUE THREAD

**Issue by bitabs** [blitz-js/blitz#3979]
### What do you want and why?

Please support Next 13 as Vercel deployment fails due to the following error: `The "target" property is no longer supported in next.config.js.`. I believe the `withBlitz({...})` maps config from Next 12 which has `target` that is deprecated in Next 13.

### Possible implementation(s)

Bump Next 12 to 13

### Additional context
<img width="1194" alt="Screenshot 2022-11-18 at 18 15 31" src="https://user-images.githubusercontent.com/16179773/202774769-9db083f7-5b6b-4c7d-a71d-237b08d45d23.png">

**Comment by bitabs** [comment]
@dillonraphael Sorry - do we have an ETA on this? It's a blocker for us unfortunately 😞

**Comment by datner** [comment]
@bitabs 
as a patch, for now do something like 
```ts
const config = withBlitz({...stuff})
delete config.target
module.exports = config
```

it should work

**Comment by bitabs** [comment]
That's not a bad shout @datner 😅. Works for the time being 🙏🏻

**Comment by datner** [comment]
@blakeley 
idk what to tell you, the `delete` reserved word removes the property from the js object. 
If you're still getting the same error then either the deletion missed timing or something else is still setting (re-setting?) that property..

either that or your js runtime is broken (which i doubt hahahah)

**Comment by bitabs** [comment]
If your running it via Vercel, be sure to invalidate your cache deployment. @blakeley

**Comment by osarogie** [comment]
Adding `reactStrictMode: true,` to next.config.js fixed the issue for me

**Comment by FlorianWendelborn** [comment]
@tordans what's missing for me personally is an overview about if we can finally upgrade to next 13. E.g. a documentation entry for migrating

Note that upgrading to next 13 doesn't imply everything must work. For example, I'm not concerned about the optional/experimental app folder personally.

I'd just like to have some sort of official statement/docs entry that upgrading to next 13 is safe and/or recommended even if there's some small caveats like "don't use app folder for now"

**Comment by dzcpy** [comment]
app folder is a very cool feature though. Hopefully Blitz can support it soon

**Comment by flybayer** [comment]
closed in https://github.com/blitz-js/blitz/pull/4079

**Comment by siddharthsharma94** [comment]
> I ran it with `vercel --force` to invalidate the cache build, but got the same error.
> 
> The last few lines of my `next.config.js` file are:
> 
> ```
> delete config.target
> console.log(config)
> module.exports = config
> ```
> 
> And the vercel logs show the following:
> 
> ```
> {
> webpack: [Function: webpack],
> images: {
> domains: [ 'ucarecdn.com', <redacted> ],
> loader: 'custom'
> },
> pageExtensions: [ 'ts', 'tsx', 'js', 'jsx' ],
> experimental: { swcMinify: true },
> reactStrictMode: true,
> output: 'standalone',
> redirects: [AsyncFunction: redirects],
> onDemandEntries: { maxInactiveAge: 3600000 }
> }
> ```
> 
> which suggests that `target` was successfully deleted.
> 
> How could `target` possibly still be defined given this output? Is there somewhere else that I should be checking?

did you ever figure this out? still running into the same issue

**Comment by ShaharIlany** [comment]
Same here, can't deploy Next 13 app to Vercel (Both pages dir and app dir doesn't works).

Log from vercel.com below:
```
[23:01:22.623] Running build in Washington, D.C., USA (East) – iad1
[23:01:22.668] Cloning github.com/... (Branch: main, Commit: ...)
[23:01:22.973] Previous build cache not available
[23:01:23.123] Cloning completed: 454.062ms
[23:01:23.267] Running "vercel build"
[23:01:23.829] Vercel CLI 28.18.3
[23:01:24.134] Installing dependencies...
[23:01:24.494] yarn install v1.22.17
[23:01:24.587] [1/4] Resolving packages...
[23:01:25.111] [2/4] Fetching packages...
[23:02:10.586] [3/4] Linking dependencies...
[23:02:10.588] warning " > @blitzjs/rpc@2.0.0-beta.25" has unmet peer dependency "@tanstack/query-core@4.24.4".
[23:02:10.591] warning "blitz > jscodeshift@0.13.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[23:02:10.591] warning "blitz > ink > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".
[23:02:10.602] warning " > @testing-library/react-hooks@8.0.1" has incorrect peer dependency "react@^16.9.0 || ^17.0.0".
[23:02:10.602] warning " > @typescript-eslint/eslint-plugin@5.42.1" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
[23:02:10.603] warning " > @vitejs/plugin-react@2.2.0" has unmet peer dependency "vite@^3.0.0".
[23:02:10.606] warning " > vite-tsconfig-paths@3.6.0" has unmet peer dependency "vite@>2.0.0-0".
[23:02:32.578] [4/4] Building fresh packages...
[23:02:34.017] Done in 69.53s.
[23:02:34.051] Detected Next.js version: 13.2.4
[23:02:34.054] Running "yarn run build"
[23:02:34.312] yarn run v1.22.17
[23:02:34.366] $ blitz build
[23:02:34.498] Loaded env from /vercel/path0/.env
[23:02:34.733] ✔ Routes manifest was successfully generated
[23:02:35.525] 
[23:02:35.526] > Build error occurred
[23:02:35.528] Error: The "target" property is no longer supported in next.config.js.
[23:02:35.528] See more info here https://nextjs.org/docs/messages/deprecated-target-config
[23:02:35.528]     at Object.loadConfig [as default] (/vercel/path0/node_modules/next/dist/server/config.js:121:19)
[23:02:35.529]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[23:02:35.529]     at async /vercel/path0/node_modules/next/dist/build/index.js:78:28
[23:02:35.529]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[23:02:35.529]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:73:29)
[23:02:35.554] error Command failed with exit code 1.
[23:02:35.555] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[23:02:35.577] Error: Command "yarn run build" exited with 1
[23:02:35.861] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**Comment by datner** [comment]
@Siarune 
>Here's my next.config.js, and the build fails with and without the delete line

Your're not deleting the target though, you're doing it too early 😅 

```js
// @ts-check
const { withBlitz } = require("@blitzjs/next")

/**
 * @type {import('@blitzjs/next').BlitzConfig}
 **/
const config = withBlitz({}) // withBlitz adds the 'target'
delete config.target

module.exports = config
```

Not sure if it'll even help, but at least you'll delete the `target` correctly

**Comment by jhonnymichel** [comment]
In case someone is still having this issue even after updating to the latest blitz/next versions, for me the issue was that I was still using the `blitz` preset in the project settings at Vercel's dashboard. Just change it to `next` and you're good to go.
