### ISSUE TITLE
Undefined reading 'anonSessionExpiryMinutes' when creating sessions from api handler

### ISSUE THREAD

**Issue by jgable** [blitz-js/blitz#4063]
### What is the problem?

We are implementing a "one click signup" process from our main marketing homepage to our app that is on a subdomain and running into intermittent errors during session creation. Our main marketing homepage is at https://company.com and the app is hosted at https://app.company.com.

The way this is implemented is a `<form>` element on the marketing homepage POST's to an auth endpoint on the subdomain. The auth endpoint does some validation of the email and creates an account with a generated password, then creates a session and redirects them to a page in the app.

The error we are seeing is `TypeError: Cannot read properties of undefined (reading 'anonSessionExpiryMinutes')` inside of index-server.cjs in the createNewSession method. Sometimes there is also an error about `BLITZ_SESSION_COOKIE_PREFIX` not being set. I think the anonSessionExpiryMinutes happens when createNewSession thinks it's an anonymous session but the cookie one happens the first time when no anonymous session has been created yet. Should I be using a different way to create the session?

### Paste all your error logs here:

```
error - TypeError: Cannot read properties of undefined (reading 'anonSessionExpiryMinutes')
    at /Users/jgable/projects/blitzApp2/node_modules/@blitzjs/auth/dist/index-server.cjs:625:30
    at Generator.next (<anonymous>)
    at /Users/jgable/projects/blitzApp2/node_modules/@blitzjs/auth/dist/index-server.cjs:150:61
    at new Promise (<anonymous>)
    at __async$2 (/Users/jgable/projects/blitzApp2/node_modules/@blitzjs/auth/dist/index-server.cjs:134:10)
    at createNewSession (/Users/jgable/projects/blitzApp2/node_modules/@blitzjs/auth/dist/index-server.cjs:607:10)
    at /Users/jgable/projects/blitzApp2/node_modules/@blitzjs/auth/dist/index-server.cjs:690:18
    at Generator.next (<anonymous>)
    at /Users/jgable/projects/blitzApp2/node_modules/@blitzjs/auth/dist/index-server.cjs:150:61
    at new Promise (<anonymous>) {
  page: '/api/auth/one-click-signup'
}
```

### Paste all relevant code snippets here:

```typescript
const oneClickSignupHandler: NextApiHandler = async (req: NextApiRequest, res: NextApiResponse) => {
  const { email } = OneClickSignupSchema.parse(req.body)

  // Check for existing user, validate details... etc.
  // ..snip...

  // Create the user with a random password
  const hashedPassword = await SecurePassword.hash(uuid().trim())

  const newUser = await db.user.create({
    data: { email, hashedPassword },
  })

  // Create the session
  const session = await getSession(req, res)
  await session.$create({ userId: newUser.id, role: "USER" })

  // Redirect to home page
  void res.redirect(302, Routes.Home().pathname + "?one-click=true").end()

  // Do other signup stuff...
}
```

### What are detailed steps to reproduce this?

I have created a repro in this repository: https://github.com/jgable/blitzjs-session-repro.

Steps to repro:
- Clone the repo down, install dependencies and run server via `yarn dev`
- Load this stackblitz page (https://react-ts-j4d3sb.stackblitz.io/) with a basic form that posts to `http://localhost:3000/api/auth/one-click-signup`
- Enter an email in the form and submit
- View server error

### Run `blitz -v` and paste the output here:

```
yarn blitz -v
yarn run v1.22.17
$ /Users/jgable/projects/blitzApp2/node_modules/.bin/blitz -v
Blitz version: 2.0.0-beta.20 (local)
macOS Monterey | darwin-x64 | Node: v16.14.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 428.71 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /var/folders/1h/qt0rhhdd2rsgtxzcmk80lgsm0000gn/T/yarn--1674065108860-0.7372363219470084/node
    Yarn: 1.22.17 - /var/folders/1h/qt0rhhdd2rsgtxzcmk80lgsm0000gn/T/yarn--1674065108860-0.7372363219470084/yarn
    npm: 8.3.1 - ~/.nodenv/versions/16.14.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.20 => 2.0.0-beta.20 
    @blitzjs/next: 2.0.0-beta.20 => 2.0.0-beta.20 
    @blitzjs/rpc: 2.0.0-beta.20 => 2.0.0-beta.20 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.20 => 2.0.0-beta.20 
    next: 12.2.5 => 12.2.5 
    prisma: 4.0.0 => 4.0.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.9.4 

✨  Done in 0.70s.
```

**Comment by jgable** [comment]
I think I figured out the problem. I needed to wrap the handler with the `api(...)` exported from `app/blitz-server`.

```diff
+ import { api } from "app/blitz-server"

- const oneClickSignupHandler = async (req: NextApiRequest, res: NextApiResponse) => {
+ const oneClickSignupHandler = api(async (req, res) => {
```
