### ISSUE TITLE
blitz generate all project does not works

### ISSUE THREAD

**Issue by cesarve77** [blitz-js/blitz#4075]
### What is the problem?

in a fresh project
blitz generate all project does not works
```
blitz new myAppName
cd myAppName
blitz dev
```

```
blitz generate all project
```

### Paste all your error logs here:

```
blitzServer.at is not a function
    at /Users/xxxx/.nvm/versions/node/v14.21.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:309:75
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxxx/.nvm/versions/node/v14.21.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:273:24)

```

### Paste all relevant code snippets here:

```
blitz new myAppName
cd myAppName
blitz dev
```

```
blitz generate all project
```

throw:

```
blitzServer.at is not a function
    at /Users/xxxx/.nvm/versions/node/v14.21.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:309:75
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxxx/.nvm/versions/node/v14.21.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:273:24)

```

### What are detailed steps to reproduce this?

```
blitz new myAppName
cd myAppName
blitz dev
```

```
blitz generate all project
```

### Run `blitz -v` and paste the output here:

```

$ 50 % blitz -v
Blitz version: 2.0.0-beta.22 (global)
Blitz version: 2.0.0-beta.22 (local)
macOS Ventura | darwin-arm64 | Node: v14.21.1


 Package manager: npm

  System:
    OS: macOS 13.1
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 37.95 GB / 128.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.1/bin/yarn
    npm: 9.1.1 - ~/.nvm/versions/node/v14.21.1/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.22 => 2.0.0-beta.22 
    @blitzjs/next: 2.0.0-beta.22 => 2.0.0-beta.22 
    @blitzjs/rpc: 2.0.0-beta.22 => 2.0.0-beta.22 
    @prisma/client: 4.6.0 => 4.6.0 
    blitz: 2.0.0-beta.22 => 2.0.0-beta.22 
    next: 13.1 => 13.1.6 
    prisma: 4.6.0 => 4.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.5 

```

### Please include below any other applicable logs and screenshots that show your problem:

nothing

**Comment by cesarve77** [comment]
Fixed with node 16, sorry!
