### ISSUE TITLE
`LoginPage.redirectAuthenticatedTo = "/"` causes an error and shows a blank page after logging-in on production

### ISSUE THREAD

**Issue by exKAZUu** [blitz-js/blitz#4084]
### What is the problem?

When we add `redirectAuthenticatedTo` to a login page, the following error sometimes (about 50%?) occurs and a blank page is shown after logging-in.
Note that this issue occurs ONLY ON production build (`blitz build && blitz start`).

![image](https://user-images.githubusercontent.com/436237/219534462-5e5baedb-09f0-4043-9a16-0a346ed4dab5.png)

### Paste all your error logs here:

![image](https://user-images.githubusercontent.com/436237/219534553-5490c609-4c81-4a1b-baf2-dd1066ed3bbe.png)

There is no log on the server side.

### Paste all relevant code snippets here:

```
import { BlitzPage } from "@blitzjs/next"
import Layout from "src/core/layouts/Layout"
import { LoginForm } from "src/auth/components/LoginForm"
import { useRouter } from "next/router"

const LoginPage: BlitzPage = () => {
  const router = useRouter()

  return (
    <Layout title="Log In">
      <LoginForm
        onSuccess={(_user) => {
          const next = router.query.next ? decodeURIComponent(router.query.next as string) : "/"
          return router.push(next)
        }}
      />
    </Layout>
  )
}


// !!!!!! ADD ONLY THE FOLLOWING CODE TO INITIAL GENERATED CODE. !!!!!!
LoginPage.redirectAuthenticatedTo = "/";

export default LoginPage
```

### What are detailed steps to reproduce this?

1. `blitz new app` 
2. `vim src/pages/auth/login.tsx`
3. Add `LoginPage.redirectAuthenticatedTo = "/"`
4. `blitz build`
5. `blitz start`
6. open http://localhost:3000/auth/login
7. Login an existing account
8. The above error occurs

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.23 (local)
macOS Ventura | darwin-arm64 | Node: v19.6.0


 Package manager: npm

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 38.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /private/var/folders/9p/8yqjg80d1n9dpmz33_v4hgj80000gn/T/xfs-84a7d459/node
    Yarn: 4.0.0-rc.39 - /private/var/folders/9p/8yqjg80d1n9dpmz33_v4hgj80000gn/T/xfs-84a7d459/yarn
    npm: 9.4.0 - ~/.asdf/shims/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.23 => 2.0.0-beta.23
    @blitzjs/next: 2.0.0-beta.23 => 2.0.0-beta.23
    @blitzjs/rpc: 2.0.0-beta.23 => 2.0.0-beta.23
    @prisma/client: ^4.10.1 => 4.10.1
    blitz: 2.0.0-beta.23 => 2.0.0-beta.23
    next: ^13.1.6 => 13.1.6
    prisma: ^4.10.1 => 4.10.1
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.5 => 4.9.5
```

**Comment by jpmelnik** [comment]
Hi!

Try to add "ErrorBoundary" provider  in your _app.tsx.

https://blitzjs.com/docs/blitzjs-next

**Comment by exKAZUu** [comment]
Thanks. I didn't change `_app.tsx` and the initial version already includes `ErrorBoundary` as follows:

```
function MyApp({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page)
  return (
    <ErrorBoundary FallbackComponent={RootErrorFallback}>
      {getLayout(<Component {...pageProps} />)}
    </ErrorBoundary>
  )
}
```

**Comment by siddhsuresh** [comment]
Hey @exKAZUu are you sure these are the steps to reproduce this. I am not able to replicate this and the functionality is working correctly in my production apps.

**Comment by exKAZUu** [comment]
Okay, I will create a reproducible repository and mention.

**Comment by jan-wilhelm** [comment]
I am having the same problem right now. This is the error message I am getting:

```
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
error - unhandledRejection: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at _res.setHeader (/Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:180:24)
    at setHeader (/Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:466:7)
    at setPublicDataCookie (/Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:512:3)
    at /Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:745:9
    at Generator.next (<anonymous>)
    at /Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:71:61
    at new Promise (<anonymous>)
    at __async$1 (/Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:55:10)
    at refreshSession (/Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:727:10)
    at /Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:861:11
    at Generator.next (<anonymous>)
    at fulfilled (/Users/janwilhelm/Desktop/coding/avanty/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.25_blitz@2.0.0-beta.25_next@13.2.4_secure-password@4.0.0/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:58:24) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
``` 

And this is the code I am using:
```tsx

SignupPage.getLayout = (page) => (
  <Layout title="Sign Up">
    <AuthLayout>{page}</AuthLayout>
  </Layout>
);
SignupPage.redirectAuthenticatedTo = Routes.OnboardingPage();

export const getServerSideProps: GetServerSideProps = gSSP(
  async ({ ctx, query, params }) => {
    ctx.session.$setPublicData({ signupPlan: query.plan as string });
    return { props: {} };
  }
);
```

⚠️ Perhaps the combination of gSSP and redirectAuthenticatedTo is what causes this?

My current workaround looks like this:
```tsx
SignupPage.getLayout = (page) => (
  <Layout title="Sign Up">
    <AuthLayout>{page}</AuthLayout>
  </Layout>
);

export const getServerSideProps: GetServerSideProps = gSSP(
  async ({ ctx, query }) => {
    if (ctx.session.userId) {
      return {
        redirect: {
          destination: Routes.OnboardingPage().pathname,
          permanent: false
        }
      };
    }
    ctx.session.$setPublicData({ signupPlan: query.plan as string });
    return { props: {} };
  }
);
```

Hope this helps.
