### ISSUE TITLE
Getting @blitzjs/next not found after codemod upgrade

### ISSUE THREAD

**Issue by MadcowD** [blitz-js/blitz#4098]
### What is the problem?

Upgraded to the latest @blitzjs using codemod and when I attempt to run blitz dev I get the following error

### Paste all your error logs here:

```
Error: Cannot find module '@blitzjs/next'
Require stack:
- /opt/homebrew/lib/node_modules/blitz/dist/chunks/next-commands.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at eval (eval at readBlitzConfig (/opt/homebrew/lib/node_modules/blitz/dist/chunks/next-commands.cjs:312:22), <anonymous>:2:23)
    at readBlitzConfig (/opt/homebrew/lib/node_modules/blitz/dist/chunks/next-commands.cjs:312:22)
    at Module.<anonymous> (/opt/homebrew/lib/node_modules/blitz/dist/chunks/next-commands.cjs:371:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/homebrew/lib/node_modules/blitz/dist/chunks/next-commands.cjs:339:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebrew/lib/node_modules/blitz/dist/chunks/next-commands.cjs'
  ]
}
```

### Paste all relevant code snippets here:

```
const { withBlitz } = require("@blitzjs/next") <-- the offending line


const hostname = process.env.BLITZ_PUBLIC_APP_URL

const allAccessCORS = {
  headers: [
    {
      key: "Access-Control-Allow-Origin",
      value: "*",
    },
  ],
}

const config = {
  log: {
    level: "warn",
  },

  async redirects() {
    const l = [
      {
        source: "/get",
        destination:
          "https://chrome.google.com/webstore/detail/ghostwrite-ai-email-assis/fbjnnjochaopepfjpngghafgnafebkjh?hl=en&authuser=0",
        permanent: true,
      },
      {
        source: "/get-chrome",
        destination: "https://google.com/chrome/browser/desktop/index.html",
        permanent: true,
      },
      {
        source: "/:path*",
        has: [
          {
            type: "header",
            key: "X-Forwarded-Proto",
            value: "http",
          },
        ],
        permanent: false,
        destination: hostname + "/:path*",
      },
    ]
    if (process.env.DISABLE_EXTENSION === "true")
      l.push({ source: "/extension.bundle.js", destination: "/disabled", permanent: false })

    return l
  },

  api: {
    bodyParser: false,
  },

  async headers() {
    return [
      {
        source: "/extension.bundle.js",
        // Allow cross origin requests from the extension.
        ...allAccessCORS,
      },
      {
        source: "/extension.js",
        // Allow cross origin requests from the extension.1
        ...allAccessCORS,
      },
      {
        source: "/analytics_standalone.js",
        ...allAccessCORS,
      },
      {
        source: "/extension.crx",
        ...allAccessCORS,
      },
    ]
  },

  // /* Uncomment this to customize the webpack config
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    //   // Note: we provide webpack above so you should not `require` it
    //   // Perform customizations to webpack config
    //   // Important: return the modified config
    return config
  },
}
module.exports = withBlitz(config)

```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.23 (global)
Blitz version: 2.0.0-beta.23 (local)
macOS Ventura | darwin-arm64 | Node: v18.0.0


 Package manager: npm

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 81.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.23 => 2.0.0-beta.23 
    @blitzjs/next: 2.0.0-beta.23 => 2.0.0-beta.23 
    @blitzjs/rpc: 2.0.0-beta.23 => 2.0.0-beta.23 
    @prisma/client: 3.14.0 => 3.14.0 
    blitz: 2.0.0-beta.23 => 2.0.0-beta.23 
    next: 12.2.0 => 12.2.0 
    prisma: 3.14.0 => 3.14.0 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript: Not Found
```

**Comment by siddhsuresh** [comment]
Hey @MadcowD could you try to delete the `node_modules` folder and perform a clean reinstall?

**Comment by MadcowD** [comment]
I deleted node modules and tried with a clean isntall same outcome

**Comment by MadcowD** [comment]
Willing to pay to have someone consult me on this, please let me know
