### ISSUE TITLE
Issue creating a Blitz project

### ISSUE THREAD

**Issue by KentHHarris** [blitz-js/blitz#4126]
### What is the problem?

I installed Blitz CLI and following the **[Get Started](https://blitzjs.com/docs/get-started#set-up-your-computer)** instructions, tried creating a new application but am running into Assertion Errors saying files are missing. Any help is appreciated.

### Paste all your error logs here:

```
Hang tight while we set up your new Blitz app!
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/kent/Development/workspace (VSC)/smpt/gitignore
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as move] (/usr/local/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at AppGenerator.<anonymous> (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1535:15)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1509:61
    at new Promise (<anonymous>)
    at __async$a (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1493:10)
    at AppGenerator.preCommit (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1534:12)
    at AppGenerator.<anonymous> (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1275:18)
    at Generator.next (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

### Paste all relevant code snippets here:

Not applicable.

### What are detailed steps to reproduce this?

1. `blitz new smpt`
2. Yes to all (four) options

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.26 (global)
macOS Ventura | darwin-x64 | Node: v16.5.0


 Package manager: npm

  System:
    OS: macOS 13.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 176.46 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: Not Found
    npm: 8.6.0 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by siddhsuresh** [comment]
This will be followed in https://github.com/blitz-js/blitz/issues/4116
