### ISSUE TITLE
A new app generated by `v2.0.0-beta.27` causes Error: DYNAMIC_SERVER_USAGE

### ISSUE THREAD

**Issue by exKAZUu** [blitz-js/blitz#4149]
### What is the problem?

The issue (#4112) still exists, so I've re-created reproduciton repo.

A new app generated by `blitz new` (Blitz version: v2.0.0-beta.27) causes `Error: DYNAMIC_SERVER_USAGE`.
Reproduction repo: https://github.com/exKAZUu/blitz-new-issue-v2.0.0-beta.27

### Paste all your error logs here:

```
react-dom.development.js:20662 Uncaught Error: DYNAMIC_SERVER_USAGE
    at updateDehydratedSuspenseComponent (react-dom.development.js:20662:1)
    at updateSuspenseComponent (react-dom.development.js:20362:1)
    at beginWork (react-dom.development.js:21624:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
```

### Paste all relevant code snippets here:

Nothing due to a completely new app.

### What are detailed steps to reproduce this?

Note that the following steps avoid installing blitz globally.

1. `cd ~`
2. `mkdir temp`
3. `cd temp`
4. `yarn add -D blitz`
5. `yarn blitz new blitz-new-issue-v2.0.0-beta.27`
6. Select the following items
   ```
   ✔ Pick a new project's language › TypeScript
   ✔ Pick your new app template › Full - includes DB and auth (Recommended)
   ✔ Install dependencies? › yarn
   ✔ Pick a form library (you can switch to something else later if you want) › React Final Form (recommended)
   ```
7. `rm -Rf node_modules package.json yarn.lock` (make sure that there is no `node_modules` in ascendant directories)
8. `cd blitz-new-issue-v2.0.0-beta.27`
9. `yarn install` (make sure that there is`node_modules` only in `blitz-new-issue-v2.0.0-beta.27` directory)
10. `yarn dev`
11. The following error is shown

<img width="882" alt="image" src="https://github.com/blitz-js/blitz/assets/436237/2538ae9b-22fa-4590-b3cf-800009360204">

### Run `blitz -v` and paste the output here:

```
$ yarn blitz -v
yarn run v1.22.19
$ /Users/exkazuu/temp/blitz-new-issue-v2.0.0-beta.27/node_modules/.bin/blitz -v
Blitz version: 2.0.0-beta.27 (local)
macOS Ventura | darwin-arm64 | Node: v20.1.0


 Package manager: npm

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 108.48 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /var/folders/xh/crfpr2zs2j136x6q01gk30fr0000gn/T/yarn--1685142904583-0.5321711978605883/node
    Yarn: 1.22.19 - /var/folders/xh/crfpr2zs2j136x6q01gk30fr0000gn/T/yarn--1685142904583-0.5321711978605883/yarn
    npm: 9.6.4 - ~/.asdf/shims/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.27 => 2.0.0-beta.27
    @blitzjs/next: 2.0.0-beta.27 => 2.0.0-beta.27
    @blitzjs/rpc: 2.0.0-beta.27 => 2.0.0-beta.27
    @prisma/client: 4.6.1 => 4.6.1
    blitz: 2.0.0-beta.27 => 2.0.0-beta.27
    next: ^13.3.0 => 13.4.4
    prisma: 4.6.1 => 4.6.1
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

### Please include below any other applicable logs and screenshots that show your problem:

The section of the reproduction steps includes a screenshot.

**Comment by exKAZUu** [comment]
As you can see the `package.json` include the followin line `"next": "^13.3.0",`, so the latest `next` (13.4.4).
I expect the blitz should generate `"next": "13.3.4",` instead of `"next": "^13.3.0",`.
