### ISSUE TITLE
New app generated by blitz new doesn't start at all

### ISSUE THREAD

**Issue by scshiv29-dev** [blitz-js/blitz#4161]
### What is the problem?

New app generated by blitz new command does not work

### Paste all your error logs here:

```
❯ blitz dev
Error: Cannot find module '@blitzjs/cli'
Require stack:
- D:\Projects\self-hosted\git\flDB\node_modules\blitz\dist\index-server.cjs\noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (C:\Users\user\AppData\Roaming\npm\node_modules\blitz\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\user\AppData\Roaming\npm\node_modules\blitz\node_modules\resolve-from\index.js:43:9)
    at Object.module.exports [as default] (C:\Users\user\AppData\Roaming\npm\node_modules\blitz\node_modules\resolve-from\index.js:46:47)
    at main (C:\Users\user\AppData\Roaming\npm\node_modules\blitz\cli\dist\blitz-cli.cjs.dev.js:53:51)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\blitz\cli\dist\blitz-cli.cjs.dev.js:122:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\self-hosted\\git\\flDB\\node_modules\\blitz\\dist\\index-server.cjs\\noop.js'
  ]
}
```
![image](https://github.com/blitz-js/blitz/assets/68141773/a04a12e6-e064-4703-8937-4c484d70031f)

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.create new app
2. run it

### Run `blitz -v` and paste the output here:

```
❯ yarn blitz -v
yarn run v1.22.18
$ D:\Projects\self-hosted\git\flDB\node_modules\.bin\blitz -v
Blitz version: 2.0.0-beta.29 (local)
Windows 10 | win32-x64 | Node: v16.15.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.31 GB / 15.93 GB
  Binaries:
    Node: 16.15.0 - ~\AppData\Local\Temp\yarn--1687337574901-0.5353286927892231\node.CMD
    Yarn: 1.22.18 - ~\AppData\Local\Temp\yarn--1687337574901-0.5353286927892231\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: 3.x => 3.15.2
    blitz: 2.0.0-beta.29 => 2.0.0-beta.29
    next: Not Found
    prisma: 3.x => 3.15.2
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ~4.5 => 4.5.5

Done in 1.55s.
❯ yarn blitz -v
yarn run v1.22.18
$ D:\Projects\self-hosted\git\flDB\node_modules\.bin\blitz -v
Blitz version: 2.0.0-beta.29 (local)
Windows 10 | win32-x64 | Node: v16.15.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.31 GB / 15.93 GB
  Binaries:
    Node: 16.15.0 - ~\AppData\Local\Temp\yarn--1687337574901-0.5353286927892231\node.CMD
    Yarn: 1.22.18 - ~\AppData\Local\Temp\yarn--1687337574901-0.5353286927892231\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: 3.x => 3.15.2
    blitz: 2.0.0-beta.29 => 2.0.0-beta.29
    next: Not Found
    prisma: 3.x => 3.15.2
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ~4.5 => 4.5.5

Done in 1.55s.

```

**Comment by googamanga** [comment]
Run this, and restart the app, be on the lookout for any other missing dependencies

```javascript
yarn add @blitzjs/cli
```
