### ISSUE TITLE
Project starter does not build project

### ISSUE THREAD

**Issue by MaxOrelus** [blitz-js/blitz#4166]
### What is the problem?

Trying to give this a go and can't seem to find a configuration that works.

### Paste all your error logs here:

```
blitz new blitz-flow-max
✔ Pick a new project's language › JavaScript
✔ Pick your new app template › Full - includes DB and auth (Recommended)
✔ Install dependencies? › yarn
✔ Pick a form library (you can switch to something else later if you want) › React Hook Form
Hang tight while we set up your new Blitz app!
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/user/pkgs/blitz-flow-max/_forms/hookform/Form.js
    at exports.copy (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at module.exports [as move] (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at AppGenerator.updateForms (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1739:13)
    at AppGenerator.<anonymous> (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1538:14)
    at Generator.next (<anonymous>)
    at /home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1498:61
    at new Promise (<anonymous>)
    at __async$a (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1482:10)
    at AppGenerator.preCommit (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1523:12)
    at AppGenerator.<anonymous> (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1264:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
➜  node -v
v18.12.1```

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. Install blitz globally
2. blitz new blitz-flow-max

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.29 (global)
Linux 5.15 | linux-x64 | Node: v18.12.1

 Package manager: npm

  System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (16) x64 AMD Ryzen 9 5980HX with Radeon Graphics
    Memory: 56.47 GB / 62.21 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```


### Please include below any other applicable logs and screenshots that show your problem:

_No response_

**Comment by PerfectProductions** [comment]
Works under the following config on my production server with;
