### ISSUE TITLE
ReferenceError: Headers is not defined on next 13.5.4

### ISSUE THREAD

**Issue by Daidalos117** [blitz-js/blitz#4226]
### What is the problem?

When upgrading next.js to `13.5.4` (needed because of one specific fix) I am getting: ReferenceError: Headers is not defined

### Paste all your error logs here:

```
ReferenceError: Headers is not defined
    at Object../dist/esm/server/web/spec-extension/adapters/headers.js (/project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:3944)
    at r (/project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:8010)
    at Object../dist/esm/server/api-utils/index.js (/project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:11:7223)
    at r (/project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:8010)
    at /project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:9593
    at /project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:50:888
    at Object.<anonymous> (/project/home/daidalos117/workspace/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:50:909)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. install blitz.js
2. upgrade next.js

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

### Please include below any other applicable logs and screenshots that show your problem:

[Reproduced issue here](https://codesandbox.io/p/github/Daidalos117/blitz-next-13-5-4/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnbzcwwf00073b6kkoz4h0hh%2522%252C%2522sizes%2522%253A%255B53.25%252C46.75%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnbzcwwe00033b6km1bftbho%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnbzcwwe00053b6khaerphiw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnbzcwwe00063b6ksof78a9a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnbzcwwe00033b6km1bftbho%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnbzcwwe00023b6k4cofbd67%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clnbzcwwe00033b6km1bftbho%2522%252C%2522activeTabId%2522%253A%2522clnbzcwwe00023b6k4cofbd67%2522%257D%252C%2522clnbzcwwe00063b6ksof78a9a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clnbzcwwe00063b6ksof78a9a%2522%257D%252C%2522clnbzcwwe00053b6khaerphiw%2522%253A%257B%2522id%2522%253A%2522clnbzcwwe00053b6khaerphiw%2522%252C%2522activeTabId%2522%253A%2522clnbzcwwe00043b6kov0h7sht%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnbzcwwe00043b6kov0h7sht%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clnbzcx12002ce5hrhqbr7e91%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clnbzf3j1008l3b6ksda37500%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Just run `yarn dev`

**Comment by Daidalos117** [comment]
@siddhsuresh ok, it works. Thanks!!
