### ISSUE TITLE
npm run dev in fresh project -> ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by MartinMuzatko** [blitz-js/blitz#4245]
### What is the problem?

I installed a fresh version of blitz using npm

`sudo npm i -g blitz`
`blitz new domika`
`cd domika`
`npm run dev` (`blitz run dev` yields the same problem)

I get the following error: `ReferenceError: Headers is not defined`

Do I need to use a more recent version of nodejs? ubuntu?

### Paste all your error logs here:

```js
ReferenceError: Headers is not defined
    at Object../dist/esm/server/web/spec-extension/adapters/headers.js (/home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:3944)
    at r (/home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:8010)
    at Object../dist/esm/server/api-utils/index.js (/home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:11:7223)
    at r (/home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:8010)
    at /home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:28:9593
    at /home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:50:888
    at Object.<anonymous> (/home/misan/dev/github/domika/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:50:909)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

`sudo npm i -g blitz`
`blitz new domika`
`cd domika`
`npm run dev` (`blitz run dev` yields the same problem)

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.35 (global)
Blitz version: 2.0.0-beta.35 (local)
Linux 5.15 | linux-x64 | Node: v16.16.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 4.86 GB / 5.79 GB
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 9.8.1 - /usr/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.35 => 2.0.0-beta.35
    @blitzjs/next: 2.0.0-beta.35 => 2.0.0-beta.35
    @blitzjs/rpc: 2.0.0-beta.35 => 2.0.0-beta.35
    @prisma/client: 5.4.2 => 5.4.2
    blitz: 2.0.0-beta.35 => 2.0.0-beta.35
    next: 13.5.4 => 13.5.4
    prisma: 5.4.2 => 5.4.2
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

### Please include below any other applicable logs and screenshots that show your problem:

interestingly, it outputs a lot of code on the screen:

![image](https://github.com/blitz-js/blitz/assets/2950505/94db055c-539e-4d4e-8966-b6365f43ca76)

**Comment by MartinMuzatko** [comment]
That fixed it for me. Thank you very much :)

**Comment by baixiaoji** [comment]
switch node@18 is fine to me #4226

**Comment by MartinMuzatko** [comment]
blitz should set required node version to 18 then :)
But yes, that resolves the problem for me. Thank you.
