### ISSUE TITLE
Runtime Error - No Native Build [Windows 10]

### ISSUE THREAD

**Issue by Fefe-Hern** [blitz-js/blitz#4271]
### What is the problem?

I wanted to try out Blitz, but upon going through Get Started and then clicking on the test "Sign Up" Button I'm presented with an error saying there's no native build.
I've tried using WSL as well (node version 21), but ran across the same issue.

### Paste all your error logs here:

```
C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18(master)
λ npm run dev

> BlitzTryout18@1.0.0 dev
> blitz dev

Loaded env from C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.env.local
Loaded env from C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.env
✔ Next.js was successfully patched with a React Suspense fix
✔ Routes manifest was successfully generated
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Environments: .env.local, .env
  - Experiments (use at your own risk):
     · typedRoutes

 ✓ Ready in 4.1s
 ○ Compiling /(auth)/signup/page ...
 ✓ Compiled /(auth)/signup/page in 4.8s (1630 modules)
 ⨯ node_modules\node-gyp-build\node-gyp-build.js (60:0) @ load.resolve.load.path
 ⨯ Error: No native build was found for platform=win32 arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.16.1 webpack=true
    loaded from: C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\vendor-chunks

    at __webpack_require__ (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\webpack-runtime.js:33:43)
    at eval (mutations/signup.ts:6:87)
    at (ssr)/./src/app/(auth)/mutations/signup.ts (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\app\(auth)\signup\page.js:474:1)
    at __webpack_require__ (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\webpack-runtime.js:33:43)
    at eval (components/SignupForm.tsx:9:75)
    at (ssr)/./src/app/(auth)/components/SignupForm.tsx (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\app\(auth)\signup\page.js:485:1)
    at __webpack_require__ (C:\Users\USERNAME\FOLDER1\FOLDER2\BlitzTryout18\.next\server\webpack-runtime.js:33:43)
null
```

### Paste all relevant code snippets here:

```
N/A
```

### What are detailed steps to reproduce this?

1. Windows 10 Pro, using npm 18.16.1 or 20.10.0 from nvm
2. `npm install -g blitz` & `blitz new BlitzTest`
3. All recommended options and install dependencies, then `npm run dev`
4. Navigate to the provided Sign Up page

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.2 (global)
Blitz version: 2.0.2 (local)
Windows 10 | win32-x64 | Node: v18.16.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 17.81 GB / 31.94 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.2 => 2.0.2
    @blitzjs/next: 2.0.2 => 2.0.2
    @blitzjs/rpc: 2.0.2 => 2.0.2
    @prisma/client: 5.4.2 => 5.4.2
    blitz: 2.0.2 => 2.0.2
    next: 13.5.4 => 13.5.4
    prisma: 5.4.2 => 5.4.2
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```

### Please include below any other applicable logs and screenshots that show your problem:

![blitz-error](https://github.com/blitz-js/blitz/assets/7971847/bfbfd284-dcbc-4cda-8665-4d56c67c56e8)

**Comment by siddhsuresh** [comment]
Related issue https://github.com/blitz-js/blitz/issues/4234

**Comment by guilt** [comment]
+1, chimed on the related issue. Can confirm this is broken because of SecurePassword

**Comment by siddhsuresh** [comment]
@Fefe-Hern the fix is available with the tag `next--missing-prebuilds`, if you can please try it out and let know if it solves the issue on your end. Thanks!

**Comment by nstelmach** [comment]
@siddhsuresh hi, wdym "the fix is available with the tag next--missing-prebuilds"? I have a similar issue and don't know how to fix it.
