### ISSUE TITLE
`yarn dev` errors

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#431]
### What is the problem?

`yarn dev` generates errors

### Steps to Reproduce: 

1. clone canary 
1. `yarn` 
1. `yarn build`
1. `yarn dev`
1. Notice errors:
```
➜ y dev   
yarn run v1.19.1
$ lerna run dev --no-private --stream --parallel
lerna notice cli v3.20.2
lerna info Executing command in 5 packages: "yarn run dev"
@blitzjs/core: $ tsdx watch --verbose
blitz: $ wait-on -d 500 ../core/dist/packages/core/src/index.d.ts && wait-on ../server/dist/packages/server/src/index.d.ts
@blitzjs/generator: $ tsdx watch --verbose
@blitzjs/server: $ tsdx watch --verbose
@blitzjs/cli: $ wait-on -d 500 ../server/dist/packages/server/src/index.d.ts
@blitzjs/cli: $ rimraf lib && tsc --watch --preserveWatchOutput
@blitzjs/core: - 
@blitzjs/server: - 
@blitzjs/generator: - 
@blitzjs/cli: 12:13:12 PM - Starting compilation in watch mode...
@blitzjs/core: - Compiling modules...
@blitzjs/server: - Compiling modules...
@blitzjs/generator: - Compiling modules...
@blitzjs/generator: ✖ Failed to compile
@blitzjs/generator: (typescript) Error: /Users/rudiyardley/projects/blitz/blitz/packages/generator/src/generators/app-generator.ts(8,19): semantic error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/node_modules/@blitzjs/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/generator:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/generator: Error: /Users/rudiyardley/projects/blitz/blitz/packages/generator/src/generators/app-generator.ts(8,19): semantic error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/node_modules/@blitzjs/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/generator:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/generator:     at error (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup/dist/shared/node-entry.js:5400:30)
@blitzjs/generator:     at throwPluginError (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup/dist/shared/node-entry.js:11878:12)
@blitzjs/generator:     at Object.error (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup/dist/shared/node-entry.js:12912:24)
@blitzjs/generator:     at Object.error (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup/dist/shared/node-entry.js:12081:38)
@blitzjs/generator:     at RollupContext.error (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
@blitzjs/generator:     at /Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24994:23
@blitzjs/generator:     at arrayEach (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
@blitzjs/generator:     at forEach (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
@blitzjs/generator:     at printDiagnostics (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24967:5)
@blitzjs/generator:     at Object.transform (/Users/rudiyardley/projects/blitz/blitz/node_modules/tsdx/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29049:17)
@blitzjs/cli: src/commands/build.ts(2,21): error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/packages/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/cli: src/commands/console.ts(7,19): error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/packages/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/cli: src/commands/db.ts(1,36): error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/packages/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/cli: src/commands/generate.ts(7,85): error TS7016: Could not find a declaration file for module '@blitzjs/generator'. '/Users/rudiyardley/projects/blitz/blitz/packages/generator/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__generator` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/generator';`
@blitzjs/cli: src/commands/generate.ts(9,19): error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/packages/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/cli: src/commands/new.ts(4,28): error TS7016: Could not find a declaration file for module '@blitzjs/generator'. '/Users/rudiyardley/projects/blitz/blitz/packages/generator/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__generator` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/generator';`
@blitzjs/cli: src/commands/new.ts(7,19): error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/packages/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/cli: src/commands/start.ts(2,25): error TS7016: Could not find a declaration file for module '@blitzjs/server'. '/Users/rudiyardley/projects/blitz/blitz/packages/server/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/server';`
@blitzjs/cli: 12:13:26 PM - Found 8 errors. Watching for file changes.
@blitzjs/core: ✔ Compiled successfully
@blitzjs/core:   Watching for changes
blitz: $ rollup -c rollup.config.js --watch
blitz: rollup v2.7.5
blitz: bundles ./src/index.ts → dist/index.js...
blitz: created dist/index.js in 6s
blitz: bundles ./src/bin/cli.ts → dist/cli.js...
blitz: created dist/cli.js in 856ms
@blitzjs/server: ✔ Compiled successfully
@blitzjs/server:   Watching for changes
```

**Comment by simonpeterdebbarma** [comment]
Just noticed the PR. Changing labels.
