### ISSUE TITLE
[DX] blitz command failure during development should be informative

### ISSUE THREAD

**Issue by abuuzayr** [blitz-js/blitz#519]
### What do you want and why?

Sometimes when developing on `blitz` we run this sequence of commands: 

| Command | Status |
| --- | --- |
| `yarn dev` | started |
| `yarn link-cli` | successful |
| `blitz [command]` | ERROR |

Quite commonly, the error is:

```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '../dist/cli'
Require stack:
- /Users/.../projects/blitz/packages/blitz/bin/blitz
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/.../projects/blitz/packages/blitz/bin/blitz:4:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/.../projects/blitz/packages/blitz/bin/blitz' ]
}
```

After some introspection, it is usually just that `yarn dev` hasn't completed yet, and the `../dist/cli` binary isn't available when we run the blitz command. 

### Possible implementation(s)

We can inform the user on what might be the issue by updating in `packages/blitz/bin/blitz`:

```javascript
#!/usr/bin/env node

try {
  require('../dist/cli')
} catch (e) {
  console.error(`blitz is unavailable yet, make sure "yarn build" or "yarn dev" has completed compiling`)
}
```

### Additional context

We can also add other reasons why it would fail.

**Comment by enzoferey** [comment]
This should be closed via https://github.com/blitz-js/blitz/pull/524, right ?

**Comment by abuuzayr** [comment]
Absolutely, thanks @enzoferey !
