### ISSUE TITLE
Couldn't find a `pages` directory as of 0.11.0

### ISSUE THREAD

**Issue by dajinchu** [blitz-js/blitz#529]
### What is the problem?
`blitz build` triggers `Couldn't find a pages directory` in 0.11.0

0.10.0 is fine

### Steps to Reproduce

1. `blitz new` or use the blitz store example
2. Bump blitz version to 0.11.0
3. `blitz build`

### Versions

```
blitz: 0.11.0 (global)
blitz: 0.11.0 (local)

```

### Other
```
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()


Explore the full API: http://pris.ly/d/client

You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

✔ Prepped for launch
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.


> Build error occurred
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at findPagesDir (/home/dajinchu/blitz-js/perftest/node_modules/next/dist/lib/find-pages-dir.js:3:170)
    at build (/home/dajinchu/blitz-js/perftest/node_modules/next/dist/build/index.js:4:451)
Creating an optimized production build .'next build' failed with status code: 1
```

**Comment by flybayer** [comment]
@dajinchu do you also Next.js as a dependency in your package json? If so, you'll need to update that to 9.4.1

**Comment by dajinchu** [comment]
bumping next.js in package.json solves it!
