### ISSUE TITLE
First render on server is missing route id

### ISSUE THREAD

**Issue by benjick** [blitz-js/blitz#741]
### What is the problem?

On SSR the first render won't have a route id

### Steps to Reproduce

1. `blitz new myApp`
2. `cd myApp`
3. `blitz generate all project name:string`
4. `blitz db migrate`
5. `blitz start`
6. Go to http://localhost:3000/projects and create a project
7. End up on http://localhost:3000/projects/1 and reload the page
8. Check terminal for error:

<details>
  <summary><code>(node:10863) UnhandledPromiseRejectionWarning: Error:</code></summary>

 ```
(node:10863) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.project.findOne()` invocation in
webpack-internal:///./app/_resolvers/projects/queries/getProject.ts:10:76

{
  where: {
    id: null
        ~~~~
  }
}

Argument id for where.id must not be null. Please use undefined instead.


    at Document.validate (/Users/admin/dev/hikyaku/node_modules/@prisma/client/runtime/index.js:1:49485)
    at Object.s [as Project] (/Users/admin/dev/hikyaku/node_modules/@prisma/client/runtime/index.js:1:208862)
    at Object.n.<computed> [as findOne] (/Users/admin/dev/hikyaku/node_modules/@prisma/client/runtime/index.js:1:210789)
    at getProject (webpack-internal:///./app/_resolvers/projects/queries/getProject.ts:10:76)
    at queryFn (/Users/admin/dev/hikyaku/node_modules/@blitzjs/core/dist/core.cjs.development.js:133:14)
    at /Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:804:26
    at _catch$1 (/Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:377:20)
    at /Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:802:14
    at /Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:406:34
    at /Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:975:40
    at _catch$1 (/Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:377:20)
    at /Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:969:18
    at /Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:406:34
    at Object.<anonymous> (/Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:1006:11)
    at Object.fetch (/Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:406:34)
    at handleSuspense (/Users/admin/dev/hikyaku/node_modules/react-query/dist/react-query.development.js:1588:31)
(node:10863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
```
</details>

### Versions

```
debug: blitzPkgPath: /Users/admin/dev/hikyaku/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/admin/dev/hikyaku/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v14.5.0

blitz: 0.16.3 (global)
blitz: 0.16.3 (local)
```

**Comment by flybayer** [comment]
@benjick thanks for reporting this. After investigation, I realized there's an issue with react-query that prevents us from properly fixing this. I opened [a new react-query issue](https://github.com/tannerlinsley/react-query/issues/744) so we'll see what they say.

For now, you can simply ignore the error in your server logs.
