### ISSUE TITLE
Blitz start is broken

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#91]
## Problem

1. Checkout canary branch
2. yarn install and yarn build
3. cd examples/vanilla-next
4. yarn start

You get the following error:

```
~/c/b/e/vanilla-next> yarn start
yarn run v1.19.1
$ blitz start
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
ReferenceError: _launchEditorFn is not defined
    at Object.<anonymous> (/Users/b/c/blitz/node_modules/next/dist/compiled/launch-editor/index.js:2:77)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (/Users/b/c/blitz/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.newLoader [as .js] (/Users/b/c/blitz/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/b/c/blitz/node_modules/next/dist/server/lib/error-overlay-middleware.js:1:166)
```

**Comment by flybayer** [comment]
I commented out the code in `packages/server/register/index.js`, but then I get the following issue:

```
~/c/b/e/vanilla-next> ys
yarn run v1.19.1
$ blitz start
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
> Using "webpackDevMiddleware" config function defined in default.
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
[ wait ]  compiling ...
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
(node:40050) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:40050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:40050) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:40050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:40050) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:40050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:40050) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:40050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:40050) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:40050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by flybayer** [comment]
So the recursive .blitz/caches/dev/.blitz/caches/dev only happens if the .blitz already exists from a previous blitz start.

**Comment by ryardley** [comment]
There are two bugs here. #92 solves one of them. Investigating the other probably has to do with ignore patterns.

**Comment by ryardley** [comment]
#94 Should fix the rest
