### ISSUE TITLE
Tests won't run on a new blitz app 

### ISSUE THREAD

**Issue by hmbrg** [blitz-js/blitz#923]
### What is the problem?

When running `npm test` on a freshly created blitz app the following error occurs: 

```
 FAIL  app/pages/index.test.tsx
  ✕ renders blitz documentation link (27 ms)

  ● renders blitz documentation link

    TypeError: Cannot read property 'createElement' of undefined

      35 |              )
      36 |      }
    > 37 |      return defaultRender(ui, { wrapper, ...options })
         |             ^
      38 | }
      39 | 
      40 | // --------------------------------------------------

      at wrapUiIfNeeded (node_modules/@testing-library/react/dist/pure.js:94:89)
      at node_modules/@testing-library/react/dist/pure.js:100:32
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:23212:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:963:14)
      at render (node_modules/@testing-library/react/dist/pure.js:96:26)
      at render (test/utils.tsx:37:9)
      at Object.<anonymous> (app/pages/index.test.tsx:10:24)
```

### Steps to Reproduce

1. `blitz new app`
2. In `app/pages/index.test.tsx` remove the `.skip` from the test
3. Run `npm test`

### Versions

```
macOS Catalina | darwin-x64 | Node: v14.8.0

blitz: 0.18.0 (global)
blitz: 0.18.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 20.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.5.0 => 2.5.0 
    @prisma/client: 2.5.0 => 2.5.0 
    blitz: 0.18.0 => 0.18.0 
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    typescript: 3.9.7 => 3.9.7 
```

**Comment by flybayer** [comment]
I can reproduce, definitely a bug! 

Anyone please feel free to dig into this and figure out what's wrong. All the related code is in `test/utils.ts` (no code inside the blitz framework itself).
